from lib import P, Z, theme

NSFW = "photorealistic, detailed skin | hentai, anime coloring | dark fantasy, oil painting | painterly, erotic illustration"

theme("horror", "Horror", [
    P("Haunted mansion", f="victorian nightgown | black lace dress | white dress, barefoot | mourning dress, veil", m="victorian suit | nightshirt | butler uniform | frock coat",
      light="candlelight | moonlight, window | lightning flash | flickering lamp", mood="tense melancholy", surf="bed:four-poster bed|wall:wallpaper|floor:wooden floor|chair:armchair",
      detail="cobwebs | dust sheets | portraits, eyes | creaking door | candle smoke | cracked mirror",
      acts=dict(solo="holding candelabra | looking over shoulder | backing away", pair="clinging to another | whispering, candle | hiding together", groups="seance | exploring, candles"),
      zones=[
          Z("Grand staircase", "haunted mansion, staircase | dark staircase, portraits | mansion hall, stairs", "portraits | banister | chandelier, dusty | ghostly figure",
            solo="climbing stairs, candle | looking up, stairs", pair="descending, holding hands", groups="group, stairs"),
          Z("Nursery", "abandoned nursery | dusty playroom | old toy room", "rocking horse | music box | porcelain doll | dust", solo="opening music box | frozen, fear",
            pair="hiding, wardrobe", groups="entering room, fear"),
          Z("Ballroom", "abandoned ballroom | ghostly ballroom | ballroom, dust sheets", "ghost dancers | broken chandelier | moonlight floor", solo="dancing alone | turning, startled",
            pair="waltz, ghosts", groups="ghost party"),
      ]),
    P("Abandoned hospital", f="hospital gown | nurse uniform | hoodie, flashlight | jacket, jeans", m="hospital gown | doctor coat | hoodie, flashlight | jacket",
      light="flashlight beam | flickering fluorescent | emergency light, red | moonlight", mood="tense", surf="bed:hospital bed|wall:tiled wall|floor:tiled floor|chair:wheelchair",
      detail="peeling paint | rusted beds | scattered files | broken glass | iv stand | dripping water",
      acts=dict(solo="holding flashlight | creeping, corridor | reading file", pair="clutching arm, another | flashlight, back-to-back | running together", groups="exploring, flashlights | running, corridor"),
      zones=[
          Z("Corridor", "hospital corridor, dark | long hallway, flickering | ward corridor", "gurney | wheelchair | exit sign", solo="walking, corridor | looking back, corridor",
            pair="walking close, corridor", groups="group, corridor"),
          Z("Operating room", "operating room, abandoned | surgery room | operating table, rust", "surgical lamp | tools | stains", solo="looking at table | frozen, fear",
            pair="whispering, operating room", groups="gathered, operating room"),
          Z("Ward", "abandoned ward | hospital ward, beds | patient room", "rows of beds | curtains | wheelchair", solo="sitting on bed | pulling curtain", pair="hiding, curtain",
            groups="exploring ward"),
      ]),
    P("Foggy graveyard", f="black coat | mourning dress | cloak, hood | white nightgown", m="black coat | cloak | gravedigger outfit | priest cassock",
      light="moonlight, fog | lantern light | blue hour, fog | lightning", mood="tense melancholy", surf="floor:grass|wall:tombstone",
      detail="fog | crows | tombstones | dead trees | lantern | iron gate",
      acts=dict(solo="holding lantern | kneeling, grave | walking, fog", pair="mourning together | walking, fog, together | digging", groups="funeral | vigil"),
      zones=[
          Z("Tombstones", "graveyard, tombstones | cemetery, fog | old graveyard", "crooked tombstones | fog | crow", solo="placing flowers | reading tombstone", pair="standing by grave",
            groups="mourners"),
          Z("Mausoleum", "mausoleum | crypt entrance | stone tomb, angels", "stone angel | iron door | ivy", solo="opening crypt door | standing, angel", pair="entering crypt",
            groups="gathered, mausoleum"),
          Z("Dead tree", "dead tree, graveyard | gnarled tree, hill | hanging tree", "gnarled branches | full moon | crows", solo="standing under tree | looking at moon",
            pair="leaning, tree", groups="circle, tree"),
      ]),
    P("Cabin in woods", f="flannel shirt | hoodie, jeans | sweater | camping outfit", m="flannel shirt | hoodie | camping outfit | jacket",
      light="campfire | flashlight | moonlight | lamp light", mood="tense", surf="bed:bunk bed|floor:wooden floor|wall:log wall|chair:chair",
      detail="dark woods | mounted antlers | oil lamp | creaking floor | axe | footprints, mud",
      acts=dict(solo="peeking out window | barricading door | holding axe", pair="hiding together | holding flashlight, another | whispering", groups="campfire stories | barricading door"),
      zones=[
          Z("Cabin interior", "log cabin interior | cabin, fireplace | cabin, night", "fireplace | old radio | trophies", solo="sitting by fire | listening, radio",
            pair="huddled, fire", groups="huddled, cabin"),
          Z("Porch", "cabin porch, night | porch, forest | cabin door, woods", "rocking chair | lantern | dark trees", solo="standing on porch | looking into woods",
            pair="porch, together", groups="porch, group"),
          Z("Campfire", "campfire, woods | fire pit, forest | campsite, night", "fire | marshmallows | tents", solo="poking fire | telling story", pair="blanket, fire",
            groups="campfire circle"),
      ]),
    P("Witch hut", f="witch hat, dress | cloak | peasant dress | robe", m="cloak | robe | peasant clothes | hunter outfit",
      light="cauldron glow | candlelight | moonlight | green light", mood="tense playful", surf="table:wooden table|floor:dirt floor|wall:shelves",
      detail="cauldron | herbs, hanging | skulls | potion bottles | black cat | spell book",
      acts=dict(solo="stirring cauldron | reading spell book | holding potion", pair="brewing potion together | casting spell | trading potion", groups="coven | ritual"),
      zones=[
          Z("Cauldron", "witch hut, cauldron | cottage, cauldron | hut interior, fire", "bubbling cauldron | green smoke | ladle", solo="stirring cauldron | adding ingredient",
            pair="tasting potion", groups="circle, cauldron"),
          Z("Herb shelves", "herb shelves | apothecary shelves | witch pantry", "jars | dried herbs | bones", solo="choosing herb | grinding herbs", pair="sorting herbs",
            groups="gathering herbs"),
          Z("Swamp door", "witch hut, swamp | swamp, hut | bayou, shack", "swamp | fireflies | frogs", solo="standing, doorway | gathering mushrooms", pair="rowing, swamp",
            groups="arriving, swamp"),
      ]),
    P("Carnival night", f="ringmaster costume | dress, coat | hoodie | fortune teller outfit", m="ringmaster costume | jacket | clown costume | hoodie",
      light="neon, carnival | string lights | flickering bulbs | moonlight", mood="tense playful", surf="floor:dirt|wall:tent",
      detail="carousel | clown masks | tickets | popcorn | broken lights | mirror maze",
      acts=dict(solo="holding balloon | looking around, nervous | entering tent", pair="riding carousel | fortune telling | lost, maze", groups="crowd, carnival | fleeing"),
      zones=[
          Z("Carousel", "carousel, night | abandoned carousel | merry-go-round", "horses | lights | music", solo="sitting on carousel horse", pair="riding carousel, together",
            groups="carousel, group"),
          Z("Fortune tent", "fortune teller tent | tent, crystal ball | tarot tent", "crystal ball | tarot cards | candles", solo="reading tarot | gazing into crystal ball",
            pair="fortune reading", groups="tent, gathered"),
          Z("Mirror maze", "mirror maze | funhouse | hall of mirrors, carnival", "distorted reflections | lights", solo="touching mirror | lost, mirrors", pair="separated, mirrors",
            groups="lost, maze"),
      ]),
    P("Sunken church", f="white dress, wet | robe | cloak | nightgown", m="robe | cloak | priest cassock | coat",
      light="moonlight, water | candlelight | green light, water | fog light", mood="melancholy tense", surf="water:flooded floor|wall:stone wall|floor:altar steps",
      detail="flooded floor | floating candles | broken pews | algae | stained glass | bell",
      acts=dict(solo="wading, church | holding candle | praying", pair="wading together | lighting candles | holding hands, water", groups="procession, water | choir"),
      zones=[
          Z("Flooded nave", "flooded church | water, nave | sunken church interior", "floating pews | reflections | lilies", solo="wading, nave | floating candle",
            pair="wading, hand in hand", groups="procession"),
          Z("Altar", "altar, ruined church | altar, candles | chancel, water", "altar | candles | cross", solo="kneeling, altar | lighting candles", pair="vows, altar",
            groups="ritual, altar"),
          Z("Belfry", "church belfry | bell tower, ruined | tower, fog", "bell | ropes | fog", solo="ringing bell | looking down", pair="climbing tower", groups="tower, group"),
      ]),
    P("Slasher camp", f="camp counselor shirt, shorts | swimsuit | hoodie | flannel shirt", m="camp counselor shirt | swim trunks | hoodie | letterman jacket",
      light="moonlight | flashlight | campfire | car headlights", mood="tense", surf="bed:cabin bunk|water:lake|floor:dock",
      detail="lake | canoes | camp sign | machete | cabins | fog, water",
      acts=dict(solo="running, woods | hiding | looking back, scared", pair="hiding together | running, hand in hand | kissing, lake", groups="campfire | fleeing"),
      zones=[
          Z("Lake dock", "summer camp, dock | lake dock, night | lake, canoes", "canoes | fog | moon", solo="sitting on dock | swimming, night", pair="swimming together, night",
            groups="dock, group"),
          Z("Cabins", "camp cabins | cabin row, night | bunkhouse", "bunk beds | flashlight | lockers", solo="checking window | hiding, bunk", pair="hiding under bed",
            groups="pillow fight, cabin"),
          Z("Woods", "dark woods, camp | forest path, night | trail, woods", "trees | fog | footprints", solo="running through woods | tripping", pair="running together",
            groups="search party"),
      ]),
    P("Victorian morgue", f="mourning dress | nurse uniform, victorian | lab coat | cloak", m="doctor coat, victorian | top hat | butcher apron | frock coat",
      light="gaslight | candlelight | cold light | lantern", mood="tense melancholy", surf="table:slab|wall:tiled wall|floor:stone floor",
      detail="sheet-covered body | surgical tools | jars | ledger | gas lamp | toe tag",
      acts=dict(solo="lifting sheet | writing ledger | examining jar", pair="autopsy | whispering, lamp | identifying body", groups="inquest | crowd, morgue"),
      zones=[
          Z("Slab room", "morgue, slabs | victorian morgue | mortuary room", "slabs | sheets | drain", solo="standing over slab", pair="examining, slab", groups="gathered, slab"),
          Z("Laboratory", "victorian laboratory | lab, jars | anatomical lab", "jars | specimens | microscope", solo="looking through microscope", pair="experiment",
            groups="lecture, lab"),
          Z("Cellar", "morgue cellar | cold cellar | basement, coffins", "coffins | ice | rats", solo="carrying lantern, cellar", pair="hiding, coffins", groups="cellar, group"),
      ]),
], "horror, dark atmosphere | film still, horror movie | gothic illustration | ink, macabre", NSFW, "cowboy shot | full body | dutch angle | from below", nonhuman="horror")

theme("myth", "Myth", [
    P("Greek temple", f="chiton | peplos, gold jewelry | toga | white robe, laurel", m="chiton | toga | armor, greek | himation",
      light="golden hour | sunbeam | torchlight | divine light", mood="calm serious", surf="floor:marble floor|wall:column|chair:marble bench|water:pool",
      detail="columns | olive branches | incense | laurel wreath | amphora | statues",
      acts=dict(solo="offering, altar | holding torch | praying, statue", pair="oracle reading | offering together | debate, philosophers", groups="procession | symposium"),
      zones=[
          Z("Altar", "temple altar | sacred fire, temple | altar, offerings", "sacred flame | offerings | smoke", solo="kneeling, altar | lighting fire", pair="offering, altar",
            groups="ritual, altar"),
          Z("Oracle chamber", "oracle chamber | delphi, vapor | cave, oracle", "vapor | tripod | laurel", solo="prophecy, eyes glowing | inhaling vapor", pair="asking oracle",
            groups="pilgrims, oracle"),
          Z("Bath", "temple bath | marble pool | sacred spring", "marble pool | flower petals | steam", solo="bathing, pool | sitting, pool edge", pair="bathing together",
            groups="bathing, temple"),
      ]),
    P("Olympus", f="goddess dress | golden armor | flowing robe | white gown, crown", m="god robe | golden armor | toga, crown | chiton",
      light="divine light | clouds, sunlight | golden glow | lightning", mood="cool serious", surf="floor:clouds|chair:throne|wall:pillar",
      detail="clouds | golden thrones | lightning | ambrosia | eagle | harp",
      acts=dict(solo="sitting on throne | holding lightning bolt | looking down, mortals", pair="council | feast, gods | duel, gods", groups="council of gods | feast"),
      zones=[
          Z("Throne hall", "mount olympus, thrones | divine hall | throne room, clouds", "thrones | columns | clouds", solo="pouring ambrosia | raising scepter", pair="judgment", groups="assembly"),
          Z("Cloud garden", "garden, clouds | heavenly garden | celestial garden", "golden apples | fountain | birds", solo="picking golden apple", pair="walking, garden",
            groups="feast, garden"),
          Z("Summit", "mountain summit, clouds | peak, storm | olympus peak", "storm | lightning | eagle", solo="summoning storm", pair="watching world", groups="gods, peak"),
      ]),
    P("Underworld", f="black dress, pomegranate | dark robe | queen dress, dark | shroud", m="dark robe | armor, dark | crown, dark | ferryman cloak",
      light="green fire | dim light | torchlight | soul light", mood="tense melancholy", surf="water:river|floor:stone|chair:throne",
      detail="river styx | souls | cerberus | pomegranate | coins | asphodel",
      acts=dict(solo="holding pomegranate | crossing river | sitting on throne", pair="bargaining | ferry crossing | farewell", groups="souls | procession"),
      zones=[
          Z("River Styx", "river styx | ferry, underworld | dark river", "ferry | coins | souls in water", solo="riding ferry | paying coin", pair="ferry, together",
            groups="souls waiting"),
          Z("Throne", "underworld throne | hades throne room | dark palace", "dark throne | flames | skulls", solo="leaning on throne | holding skull", pair="audience, throne",
            groups="court, underworld"),
          Z("Asphodel", "asphodel fields | fields of ghosts | gray meadow", "pale flowers | ghosts | mist", solo="walking, ghosts", pair="searching, fields",
            groups="wandering souls"),
      ]),
    P("Norse hall", f="viking dress, braids | valkyrie armor | fur cloak | shieldmaiden outfit", m="viking armor | fur cloak | chainmail | tunic, fur",
      light="firelight | torchlight | aurora | cold daylight", mood="happy serious", surf="table:long table|floor:wooden floor|chair:bench",
      detail="mead horns | shields, wall | fire pit | furs | runes | antlers",
      acts=dict(solo="drinking mead | sharpening axe | carving runes", pair="arm wrestling | toast, mead horns | sparring", groups="feast | toasting, hall"),
      zones=[
          Z("Mead hall", "viking mead hall | longhouse | great hall, fire", "long tables | fire pit | shields", solo="raising horn", pair="toasting", groups="feast, long table"),
          Z("Longship", "viking longship | ship, fjord | longship, sea", "dragon prow | oars | shields", solo="standing at prow", pair="rowing", groups="rowing crew"),
          Z("Rune stone", "rune stone, hill | standing stones | stone circle, snow", "runes | snow | ravens", solo="touching runes", pair="oath, stone", groups="ritual, stones"),
      ]),
    P("Celtic grove", f="druid robe | green dress | flower crown, dress | cloak, torc", m="druid robe | cloak | tunic | tattoos, cloak",
      light="dappled light | moonlight | mist | bonfire", mood="calm", surf="floor:moss|wall:standing stone|water:spring",
      detail="standing stones | mistletoe | oak trees | fireflies | moss | carved knots",
      acts=dict(solo="gathering mistletoe | chanting | holding staff", pair="handfasting | ritual together | dancing, fire", groups="bonfire dance | druid circle"),
      zones=[
          Z("Stone circle", "stone circle | henge, mist | standing stones", "stones | mist | moon", solo="standing, stones | arms raised", pair="handfasting",
            groups="circle, stones"),
          Z("Sacred oak", "ancient oak | grove, oak | oak tree, mistletoe", "mistletoe | roots | lanterns", solo="touching oak", pair="sitting, roots", groups="ritual, oak"),
          Z("Spring", "sacred spring | spring, ribbons | holy well", "ribbons | coins | clear water", solo="drinking from spring", pair="washing hands, spring",
            groups="pilgrims, spring"),
      ]),
    P("Egyptian temple", f="egyptian dress, gold collar | linen dress | headdress, gold | priestess robe", m="egyptian kilt, gold collar | pharaoh headdress | priest robe | linen kilt",
      light="sunbeam | torchlight | golden light | desert sun", mood="serious calm", surf="floor:sandstone|wall:hieroglyphs|chair:throne",
      detail="hieroglyphs | lotus | scarab | golden statues | papyrus | incense",
      acts=dict(solo="offering lotus | reading papyrus | sitting on throne", pair="ritual | anointing | fanning", groups="procession | court"),
      zones=[
          Z("Hypostyle hall", "hypostyle hall | temple columns, egypt | karnak", "columns | hieroglyphs | light beams", solo="walking, columns", pair="procession, columns",
            groups="priests"),
          Z("Throne room", "pharaoh throne room | egyptian palace | throne, gold", "throne | fans | guards", solo="crook and flail | standing, dais", pair="audience", groups="court"),
          Z("Nile bank", "nile river | river bank, papyrus | felucca, nile", "papyrus | boats | crocodile", solo="bathing, nile", pair="boat, river", groups="boats"),
      ]),
    P("Japanese shrine", f="miko outfit | kimono | yukata | shrine maiden", m="kannushi robe | yukata | hakama | kimono",
      light="lantern light | morning mist | autumn light | moonlight", mood="calm", surf="floor:shrine steps|wall:torii",
      detail="torii | fox statues | omamori | paper charms | sacred rope | bells",
      acts=dict(solo="praying | sweeping, shrine | ringing bell", pair="praying together | fortune papers | festival", groups="festival | shrine visit"),
      zones=[
          Z("Torii path", "fox shrine, torii | torii path | shrine stairs", "torii | foxes | lanterns", solo="walking, torii", pair="walking, torii, together", groups="procession, torii"),
          Z("Main hall", "shrine hall | honden | shrine, offering box", "offering box | bell rope | coins", solo="clapping, prayer", pair="praying, offering",
            groups="crowd, prayer"),
          Z("Sacred tree", "sacred tree, rope | shrine tree | old cedar", "shimenawa | paper | cedar", solo="touching tree", pair="tying fortune", groups="gathered, tree"),
      ]),
    P("Atlantis", f="mermaid scales, shells | sea goddess dress | pearl jewelry, gown | armor, coral", m="sea king armor | trident, cloak | coral armor | robe, pearls",
      light="underwater light | caustics | bioluminescence | blue light", mood="calm serious", surf="water:water|floor:sand|chair:shell throne",
      detail="bubbles | coral | fish schools | pearls | sunken columns | jellyfish",
      acts=dict(solo="swimming | holding trident | sitting on throne", pair="swimming together | dancing, water | gifting pearl", groups="court, underwater | school of fish"),
      zones=[
          Z("Palace", "underwater palace | atlantis palace | sunken palace", "coral columns | pearls | thrones", solo="sitting, shell throne", pair="court, throne",
            groups="court, palace"),
          Z("Ruins", "sunken ruins | atlantis ruins | underwater city", "broken columns | statues | fish", solo="swimming, ruins", pair="exploring ruins", groups="divers"),
          Z("Kelp forest", "kelp forest | seaweed forest | underwater forest", "kelp | sunbeams | seals", solo="swimming, kelp", pair="hide and seek, kelp", groups="swimming, kelp"),
      ]),
    P("Fae court", f="fairy dress, petals | gown, leaves | crown, flowers | ethereal dress", m="fae armor, leaves | cloak, antlers | crown, thorns | silk robe",
      light="moonlight | fireflies | glowing mushrooms | dappled light", mood="playful calm", surf="floor:moss|chair:throne",
      detail="fireflies | mushroom rings | glowing flowers | dew | butterflies | tiny lanterns",
      acts=dict(solo="dancing, fireflies | sitting on throne | casting spell", pair="dancing, ring | bargaining, fae | crowning another", groups="fae revel | court"),
      zones=[
          Z("Mushroom ring", "fairy ring | mushroom circle | glade, mushrooms", "mushrooms | glow | dew", solo="dancing, ring", pair="dancing, ring, together", groups="revel, ring"),
          Z("Throne", "fae throne | throne, roots | court, forest", "throne | thorns | flowers", solo="sitting, throne", pair="audience, throne", groups="fae court"),
          Z("Moon pool", "moon pool | glowing pond | enchanted pond", "reflection | lilies | glow", solo="gazing into pool", pair="bathing, pool", groups="pool, group"),
      ]),
], "classical oil painting | mythological illustration | fresco | art nouveau", NSFW, "full body | cowboy shot | wide shot | from below", nonhuman="myth")

theme("fantasy", "Fantasy", [
    P("Tavern", f="barmaid dress | adventurer outfit | ranger cloak | mage robe", m="adventurer outfit | ranger cloak | leather armor | bard outfit",
      light="firelight | candlelight | lantern light | warm light", mood="happy playful", surf="table:wooden table|chair:bench|wall:bar|bed:inn bed",
      detail="mugs of ale | roast | quest board | dice | bard, lute | barrels",
      acts=dict(solo="drinking ale | reading quest board | playing lute", pair="arm wrestling | toasting mugs | planning quest", groups="party, tavern | brawl"),
      zones=[
          Z("Main hall", "fantasy tavern | inn, main hall | tavern interior", "long tables | fire | patrons", solo="sitting, table", pair="sitting across, ale", groups="crowded table"),
          Z("Bar", "tavern bar | bar counter, barrels | innkeeper counter", "barrels | mugs | innkeeper", solo="leaning on bar", pair="ordering, bar", groups="bar crowd"),
          Z("Inn room", "inn room | tavern bedroom | attic room, inn", "straw bed | candle | pack", solo="sitting on bed, map", pair="planning, map", groups="party, inn room"),
      ]),
    P("Wizard tower", f="mage robe | witch hat, robe | sorceress gown | apprentice robe", m="wizard robe | mage robe | apprentice robe | cloak, staff",
      light="magic glow | candlelight | moonlight | starlight", mood="calm serious", surf="table:desk|floor:stone floor|wall:bookshelf|chair:chair",
      detail="floating books | crystal ball | potions | star charts | spell circle | owl",
      acts=dict(solo="casting spell | reading grimoire | holding staff", pair="teaching magic | duel, magic | studying together", groups="magic class | ritual"),
      zones=[
          Z("Study", "wizard study | library, magic | tower study", "books | scrolls | quill", solo="writing, quill | reading", pair="studying together", groups="lesson"),
          Z("Observatory", "tower observatory | telescope, stars | astronomy tower", "telescope | stars | orrery", solo="looking through telescope", pair="stargazing", groups="stargazing"),
          Z("Summoning room", "summoning circle | ritual room | magic circle, floor", "glowing circle | candles | runes", solo="summoning", pair="ritual together", groups="circle, ritual"),
      ]),
    P("Elven forest", f="elven dress | ranger outfit | circlet, gown | leaf armor", m="elven armor | ranger cloak | robe, circlet | leaf armor",
      light="dappled sunlight | moonlight | god rays | glowing flowers", mood="calm", surf="floor:moss|water:stream",
      detail="giant trees | glowing flowers | treehouses | lanterns | deer | waterfalls",
      acts=dict(solo="archery | walking, forest | singing", pair="walking together | archery lesson | dancing, forest", groups="elven council | procession"),
      zones=[
          Z("Treetop city", "elven city, trees | treehouses, bridges | tree city", "bridges | lanterns | houses", solo="walking, bridge", pair="leaning, railing", groups="festival, trees"),
          Z("Archery range", "archery range, forest | forest, targets | glade, bows", "targets | bows | arrows", solo="aiming bow", pair="archery lesson", groups="archers"),
          Z("Moon glade", "glade, moonlight | clearing, flowers | elven shrine", "moon | flowers | shrine", solo="praying, moon", pair="dancing, glade", groups="ceremony"),
      ]),
    P("Dwarven forge", f="smith apron | armor, dwarven | work clothes | leather apron", m="smith apron | armor, dwarven | leather apron | work clothes",
      light="forge glow | lava light | torchlight | sparks", mood="serious happy", surf="table:anvil|wall:stone wall|floor:stone floor",
      detail="anvil | sparks | molten metal | hammers | runes | ale",
      acts=dict(solo="hammering, anvil | quenching blade | inspecting sword", pair="forging together | trading | toasting, ale", groups="forge crew | feast"),
      zones=[
          Z("Forge", "dwarven forge | forge, lava | smithy, mountain", "forge | anvil | sparks", solo="hammering", pair="forging together", groups="crew, forge"),
          Z("Mine", "dwarven mine | mine shaft, crystals | mining tunnel", "crystals | cart | pickaxe", solo="mining", pair="pushing cart", groups="miners"),
          Z("Great hall", "dwarven hall | underground hall | mountain hall", "statues | pillars | fire", solo="walking, hall", pair="audience", groups="feast, hall"),
      ]),
    P("Royal castle", f="princess gown | queen dress | knight armor | court dress", m="knight armor | prince outfit | king robe | guard uniform",
      light="window light | candlelight | torchlight | sunbeam", mood="serious calm", surf="bed:canopy bed|chair:throne|wall:stone wall|floor:castle floor",
      detail="banners | tapestries | chandeliers | suits of armor | crests | guards",
      acts=dict(solo="sitting on throne | looking out window | reading letter", pair="dancing, ball | kneeling, knight | secret meeting", groups="royal court | ball"),
      zones=[
          Z("Throne room", "castle throne room | royal hall | throne, banners", "throne | banners | carpet", solo="crown, standing, dais | holding scepter", pair="audience, king", groups="court"),
          Z("Ballroom", "castle ballroom | royal ball | dance hall", "chandeliers | musicians | dancers", solo="dancing", pair="waltz", groups="ball"),
          Z("Royal bedchamber", "royal bedchamber | canopy bed, castle | princess room", "canopy bed | vanity | balcony", solo="sitting, vanity", pair="secret visit",
            groups="handmaidens"),
      ]),
    P("Dungeon crawl", f="adventurer outfit | rogue leather | cleric robe | armor", m="armor | rogue leather | cleric robe | barbarian outfit",
      light="torchlight | magic light | dim light | glowing runes", mood="tense", surf="floor:stone floor|wall:dungeon wall",
      detail="skeletons | traps | treasure chest | torches | cobwebs | runes",
      acts=dict(solo="holding torch | opening chest | sneaking", pair="back-to-back, fight | disarming trap | healing another", groups="adventuring party | battle"),
      zones=[
          Z("Corridor", "dungeon corridor | stone corridor, torches | dungeon passage", "torches | traps | bones", solo="sneaking, corridor", pair="walking, torch", groups="party, corridor"),
          Z("Treasure room", "treasure room | gold hoard | vault, dungeon", "gold | gems | chest", solo="holding gem | counting coins", pair="sharing loot", groups="party, treasure"),
          Z("Boss chamber", "boss chamber | throne room, dungeon | dark chamber", "bones | throne | fog", solo="fighting stance", pair="fighting together", groups="battle"),
      ]),
    P("Floating islands", f="sky pirate outfit | aviator outfit | flowing dress | adventurer outfit", m="sky pirate outfit | aviator jacket | adventurer outfit | captain coat",
      light="sunny sky | golden hour | clouds | sunset", mood="happy", surf="floor:grass|wall:ruins",
      detail="floating rocks | waterfalls, sky | airships | clouds | wind | birds",
      acts=dict(solo="looking over edge | flying | sitting, edge", pair="flying together | airship deck | exploring", groups="airship crew | exploring"),
      zones=[
          Z("Island edge", "floating island edge | cliff, sky | island, clouds", "clouds below | waterfall | wind", solo="dangling legs, edge | wind, cape", pair="sitting, edge, together",
            groups="looking down"),
          Z("Airship deck", "airship deck | sky ship | airship, clouds", "sails | ropes | propellers", solo="steering airship", pair="lookout", groups="crew"),
          Z("Sky ruins", "sky ruins | floating temple | ruins, clouds", "ruins | vines | sky", solo="exploring ruins", pair="exploring, together", groups="expedition"),
      ]),
    P("Fantasy market", f="merchant dress | adventurer outfit | cloak | dancer outfit", m="merchant robe | adventurer outfit | cloak | guard armor",
      light="sunny day | lanterns | dusk | magic light", mood="happy playful", surf="table:stall",
      detail="potions | magic items | exotic fruits | dragon eggs | crowds | banners",
      acts=dict(solo="haggling | browsing stall | holding potion", pair="haggling together | trying potion | pickpocket", groups="crowd, market | parade"),
      zones=[
          Z("Potion stall", "potion stall | market, potions | alchemist stall", "potions | herbs | bubbles", solo="tasting potion", pair="haggling, potions", groups="crowd, stall"),
          Z("Weapon stall", "weapon stall | smith stall, market | armory stall", "swords | shields | armor", solo="testing sword", pair="buying sword", groups="adventurers, stall"),
          Z("Plaza", "market plaza | fountain, market | town square", "fountain | performers | crowd", solo="sitting, fountain", pair="watching performer", groups="festival"),
      ]),
    P("Dragon lair", f="knight armor | mage robe | princess dress | adventurer outfit", m="knight armor | mage robe | adventurer outfit | barbarian outfit",
      light="fire glow | lava light | gold reflections | dim light", mood="tense serious", surf="floor:gold hoard|wall:cave wall",
      detail="gold hoard | dragon bones | smoke | lava | broken armor | scales",
      acts=dict(solo="sneaking, gold | raising sword | hiding, rock", pair="fighting dragon | sneaking together | shielding another", groups="raid | battle"),
      zones=[
          Z("Hoard", "dragon hoard | gold, cave | treasure, dragon", "gold coins | goblets | crowns", solo="grabbing gold", pair="sneaking, gold", groups="raid, hoard"),
          Z("Lava cave", "lava cave | volcano cave | magma river", "lava | smoke | heat", solo="jumping, lava", pair="crossing lava", groups="crossing, cave"),
          Z("Cave mouth", "cave entrance | mountain cave | lair entrance", "bones | smoke | sky", solo="standing, entrance", pair="entering lair", groups="party, entrance"),
      ]),
], "fantasy art, detailed | oil painting, fantasy | anime illustration, fantasy | dungeons and dragons art", NSFW, "full body | cowboy shot | wide shot | dynamic angle", nonhuman="fantasy")
