from lib import P, Z, theme

NSFW = "photorealistic, detailed skin | hentai, anime coloring | painterly, erotic illustration | glamour photography"

theme("fashion", "Fashion", [
    P("Backstage", detail="fashion week passes | coffee cups | rolling racks | stylist, safety pins | phone flash | headset crew", acts=dict(solo="looking at viewer | checking phone | adjusting earring", pair="selfie together | whispering, backstage | helping with zipper", groups="group selfie | rushing past"),
      f="couture gown, pinned | sheer dress | blazer dress | sequin dress", m="tailored suit, unbuttoned | long coat | velvet tuxedo | silk shirt, wide pants",
      light="vanity lights | camera flash | fluorescent light, backstage | spotlight spill", mood="cool serious", surf="chair:makeup chair|table:vanity|wall:mirror",
      zones=[
          Z("Makeup mirror", "backstage, vanity mirror, bulbs | dressing room, mirror lights | backstage, makeup station",
            "makeup brushes | hairspray mist | lipstick | bobby pins | mirror reflection | name cards, mirror", solo="makeup, mirror | applying lipstick | eyes closed, makeup brush | sitting, makeup chair",
            pair="doing makeup, another | fixing hair, another | reflection, mirror, together", groups="lined up at mirrors | makeup rush"),
          Z("Clothing racks", "backstage, clothing racks | wardrobe area, garment bags | backstage, racks, shoes",
            "clothing rack | shoe rows | garment bags | polaroids, wall | steamer", solo="choosing outfit | zipping dress | holding hanger",
            pair="zipping another's dress | fitting, pins | adjusting collar, another", groups="dressing rush | crowded racks"),
          Z("Runway entrance", "runway entrance, curtain | catwalk, backstage door | runway, lights, crowd",
            "runway lights | crowd silhouettes | photographers pit | confetti | curtain", solo="walking, runway | posing at runway end | waiting, curtain",
            pair="walking runway together | waiting, holding hands", groups="final walk, models | lined up, runway"),
      ]),
    P("Atelier", detail="fabric swatches | sketchbook | tailor chalk | spool rack | mood board | steam iron", acts=dict(solo="holding fabric swatch | sketching, pencil | looking at viewer", pair="laughing, fabric | sketch review | pinning hem, another", groups="crowded workroom | measuring, group"),
      f="muslin dress, pins | silk slip, measuring tape | apron, rolled sleeves | linen smock", m="waistcoat, measuring tape | linen shirt, pins | apron, shirt | cardigan, glasses",
      light="skylight | work lamp | north light | soft window light", mood="serious happy", surf="table:cutting table|chair:stool|floor:fabric scraps|wall:pattern wall",
      zones=[
          Z("Dress forms", "atelier, dress forms | sewing studio, mannequins | design studio, fabric bolts",
            "dress form | pins | chalk | fabric bolts | sketches, wall", solo="pinning fabric, dress form | draping fabric | stepping back, looking",
            pair="fitting dress, another | measuring waist, another | choosing fabric", groups="fitting session | gathered around dress form"),
          Z("Cutting table", "atelier, cutting table | workroom, patterns, table | tailor shop, table",
            "scissors | paper patterns | tape measure | chalk | thread spools", solo="cutting fabric | sketching | marking chalk",
            pair="leaning over table, sketch | pattern cutting", groups="meeting, sketches | team at table"),
          Z("Sewing corner", "sewing machine, window | sewing corner, threads | workshop, machines",
            "sewing machine | thread spools | buttons jar | pincushion | iron", solo="sewing, machine | threading needle | hand sewing",
            pair="sewing together | holding fabric", groups="sewing line | busy workshop"),
      ]),
    P("Cyclorama lookbook", detail="softbox | c-stand | camera tripod | wind machine | gaffer tape mark | monitor, tether", acts=dict(solo="hands in pockets | looking over shoulder | head tilt, chin up", pair="posing, close together | holding hands, stride | leaning on another's shoulder", groups="staggered poses | hands on shoulders"),
      f="oversized coat, wide pants | sculptural dress | monochrome streetwear | knit set", m="tailored suit, loafers | puffer jacket | knit set | trench coat, boots",
      light="soft studio light | beauty dish, hard shadow | rim light | flat lighting", mood="cool", surf="floor:white floor|chair:acrylic chair|wall:cyclorama",
      camera="full body | from below | cowboy shot",
      zones=[
          Z("White cyc", "white cyclorama | white background, studio | infinity cove, white",
            "long shadow | fabric motion | wind machine | white floor", solo="walking toward viewer | mid-stride | sitting, acrylic chair | hand in pocket",
            pair="walking side by side | back-to-back", groups="v formation | walking in row"),
          Z("Color cyc", "pastel backdrop | colored seamless paper | orange backdrop, studio",
            "color blocking | props, cubes | balloon | colored shadow", solo="sitting on cube | jumping | leaning, prop", pair="mirror pose | sitting on cubes",
            groups="color blocking, group | sitting on cubes"),
          Z("Concrete set", "concrete wall, studio | industrial set, concrete | brutalist set",
            "concrete | metal chair | dust | steel beam", solo="leaning on wall | crouching | arms crossed", pair="leaning on wall, together",
            groups="standing in row, concrete"),
      ]),
    P("Desert shoot", detail="joshua trees | sunglasses | heat haze | wind, fabric | tire tracks | red rocks", acts=dict(solo="shielding eyes, sun | walking toward viewer | sunglasses, looking at viewer", pair="back-to-back | walking away, together | holding hands, wind", groups="walking in line | silhouettes, horizon"),
      f="flowing gown | linen set | leather jacket, boots | silk scarf, sunglasses", m="linen suit | open shirt, sunglasses | leather jacket | long coat",
      light="harsh sunlight | golden hour | blue hour | dust haze", mood="cool calm", surf="floor:sand|chair:vintage car",
      zones=[
          Z("Dunes", "desert, sand dunes | dunes, wind | desert, ripples, sand", "sand ripples | wind, sand | long fabric | footprints",
            solo="walking on dune | gown, wind | kneeling in sand", pair="walking on dunes | back-to-back, dunes", groups="walking in line, dunes"),
          Z("Highway", "desert highway | empty road, mountains | route 66", "center line | road sign | heat haze | mountains, distance",
            solo="standing on road | sitting on hood, car | walking on center line", pair="leaning on car | road trip", groups="posing on road | car, group"),
          Z("Motel sign", "roadside motel, neon sign | desert motel | gas station, desert", "neon sign | vintage car | ice machine | cactus",
            solo="leaning on car | sitting, motel door", pair="leaning on car, close | standing, neon sign", groups="motel lot, group"),
      ]),
    P("Palace editorial", detail="gilded ceiling | velvet drapes | crystal chandelier | portraits, wall | parquet floor | candelabra", acts=dict(solo="looking over shoulder | hand on banister | holding fan", pair="bowing, hand kiss | waltz | bowing, curtsy", groups="royal court pose | promenade"),
      f="ball gown | silk gown, long train | velvet dress, gloves | tulle dress", m="tuxedo | velvet blazer | military jacket | brocade suit",
      light="chandelier light | window light, palace | candlelight | sunbeam", mood="cool serious", surf="floor:marble floor|wall:marble column|chair:throne",
      zones=[
          Z("Hall of mirrors", "hall of mirrors | palace hall, chandeliers | gilded hallway",
            "chandeliers | mirrors | gilded walls | parquet", solo="walking down hall | looking at mirror | train spread", pair="dancing, hall | walking arm in arm",
            groups="waltz, hall | walking in line"),
          Z("Grand staircase", "grand staircase | marble staircase, palace | sweeping stairs",
            "red carpet | marble steps | balustrade", solo="sitting on stairs | descending stairs | train on stairs", pair="descending stairs, together",
            groups="posing on stairs, tiers"),
          Z("Throne room", "throne room | palace, throne, columns | royal hall", "throne | velvet | banners | columns",
            solo="sitting on throne | leaning on column | crown", pair="throne, standing beside", groups="court, throne"),
      ]),
    P("Street style", detail="street photographers | yellow taxi | fashion week crowd | shopping bags | iced coffee | brick buildings", acts=dict(solo="walking, coffee cup | adjusting sunglasses | looking at viewer, stride", pair="walking, arm in arm | taking photo | sharing headphones", groups="walking abreast | street crew pose"),
      f="oversized blazer, jeans | trench coat, sneakers | mini skirt, boots | leather jacket, dress", m="bomber jacket, cargo pants | suit, sneakers | overcoat, scarf | denim jacket",
      light="overcast | street light | golden hour, city | camera flash", mood="cool happy", surf="wall:shop wall|chair:bench",
      zones=[
          Z("Crosswalk", "crosswalk, city | street crossing, crowd | zebra crossing", "taxi | crowd blur | traffic light | photographers",
            solo="crossing street | mid-stride, coffee | looking at phone", pair="crossing together | laughing, walking", groups="crossing street, group"),
          Z("Shop window", "shop window | boutique, window display | storefront", "mannequins | reflections | shopping bags", solo="looking at window | holding bags",
            pair="window shopping | pointing at window", groups="shopping together"),
          Z("Cafe terrace", "cafe terrace, street | sidewalk cafe | bistro tables", "espresso | sunglasses | newspaper", solo="sitting, espresso | crossed legs",
            pair="coffee together | talking, terrace", groups="crowded table, terrace"),
      ]),
    P("Beach editorial", detail="palm trees | turquoise water | sun hat | sunglasses | beach towels | seagulls", acts=dict(solo="hair blowing | holding sandals | looking at viewer, wind", pair="piggyback | holding hands, waves | lying on towel, together", groups="group pose, sand | beach volleyball"),
      f="swimsuit, sarong | linen dress | one-piece swimsuit, wide hat | crochet top", m="linen shirt, swim trunks | open shirt | white pants | swim trunks",
      light="midday sun | golden hour | overcast, beach | sunset", mood="happy calm", surf="floor:sand|water:waves",
      zones=[
          Z("Shoreline", "beach, shoreline | ocean, waves, sand | white sand, turquoise water", "waves | seashells | footprints | foam",
            solo="walking, shoreline | standing in surf | holding hat", pair="walking on beach | splashing", groups="running into surf"),
          Z("Cabanas", "beach cabana | parasol, sun loungers | beach club", "parasol | sun lounger | towels | cocktails", solo="lying on lounger | sitting, cabana",
            pair="sharing lounger | drinks, cabana", groups="beach club, group"),
          Z("Pier", "wooden pier | boardwalk, sea | jetty", "wooden planks | rope | boats", solo="sitting on pier | leaning on post", pair="sitting on pier, feet dangling",
            groups="pier, group"),
      ]),
    P("Rooftop campaign", detail="skyline | glass towers | wind, hair | champagne flutes | city lights | helicopter", acts=dict(solo="walking toward viewer | adjusting cufflinks | looking at city", pair="power pose, together | walking side by side | leaning on railing, together", groups="posing, skyline | toasting"),
      f="power suit | slip dress, blazer | leather trench | cocktail dress", m="double-breasted suit | turtleneck, coat | leather jacket | tuxedo",
      light="sunset, skyline | blue hour | city lights | camera flash", mood="cool", surf="wall:railing|floor:rooftop|chair:lounge chair",
      zones=[
          Z("Helipad", "helipad, skyline | rooftop helipad | rooftop, city", "helipad marking | wind | skyline", solo="standing, helipad, wind | walking", pair="back-to-back, helipad",
            groups="power pose, group"),
          Z("Pool deck", "rooftop pool | infinity pool, skyline | pool deck", "pool | loungers | city lights", solo="sitting, pool edge | lounging", pair="drinks, pool edge",
            groups="pool party"),
          Z("Glass railing", "glass railing, skyline | penthouse terrace | balcony, city", "glass railing | champagne | skyline", solo="leaning on railing | holding champagne",
            pair="toasting, railing", groups="toasting, terrace"),
      ]),
    P("Vintage market", detail="bunting | cardboard price signs | wicker baskets | old postcards | sunglasses rack | lemonade", acts=dict(solo="holding shopping bag | trying on sunglasses | laughing", pair="holding hands, browsing | sharing lemonade | trying on hats, laughing", groups="friends shopping | walking, market"),
      f="floral dress, cardigan | denim overalls | 70s dress | knit vest, skirt", m="corduroy jacket | knit vest | denim jacket | flannel shirt",
      light="afternoon sun | overcast | string lights | warm light", mood="happy", surf="table:market stall|chair:folding chair",
      zones=[
          Z("Clothes stall", "flea market, clothing stall | vintage market | thrift market", "clothes racks | hats | handbags | price tags",
            solo="trying on hat | browsing rack", pair="trying on clothes, laughing | holding up dress", groups="shopping, market"),
          Z("Record stall", "record stall | vinyl crates | market, records", "vinyl records | turntable | posters", solo="browsing records | holding record",
            pair="listening, headphones", groups="crate digging"),
          Z("Antique stall", "antique stall | flea market, antiques | bric-a-brac", "old cameras | teacups | mirrors", solo="holding camera | looking at mirror",
            pair="bargaining | holding teacup", groups="browsing antiques"),
      ]),
], "high fashion photography, editorial | film photography, lookbook | fashion illustration, marker | magazine cover", NSFW, "full body | cowboy shot | from below")

theme("film", "Film", [
    P("Noir motel", detail="smoke | rain on window | flickering neon | rotary phone | room key, motel | whiskey glass", acts=dict(solo="smoking, looking away | holding gun | hand on doorframe", pair="embrace, tense | lighting cigarette, another | pointing gun, another", groups="huddled, whispering | standoff"),
      f="slip dress | trench coat, red lipstick | pencil skirt, blouse | fur stole, gloves", m="rumpled shirt, suspenders | trench coat, fedora | open collar, shoulder holster | vest, loose necktie",
      light="blinds shadow | neon, window | lamp light | cigarette glow", mood="tense melancholy", surf="bed:motel bed|wall:door|chair:vinyl chair|table:nightstand",
      zones=[
          Z("Bed", "motel room, bed | cheap motel, lamp | motel room, suitcase", "ashtray, cigarette | revolver, nightstand | open suitcase | cash | bible, drawer",
            solo="sitting on bed, smoking | packing suitcase | lying on bed, ceiling", pair="counting money | sharing cigarette | arguing", groups="planning, map | cards game, bed"),
          Z("Window", "motel window, blinds | window, neon sign | blinds, night", "blinds | neon sign | rain | headlights",
            solo="peeking through blinds | leaning on window frame", pair="whispering, window | watching outside", groups="watching outside"),
          Z("Bathroom", "motel bathroom, mirror | tiled bathroom, flickering light | sink, mirror", "cracked mirror | dripping faucet | towel | lipstick, mirror",
            solo="looking in mirror | washing face | lipstick on mirror", pair="mirror, reflection, both | bandaging hand", groups="crowded bathroom"),
      ]),
    P("Western saloon", detail="dust particles | swinging doors | wanted poster | piano | oil lamp | spurs", acts=dict(solo="tipping hat | hand on holster | leaning, arms crossed", pair="back-to-back, guns | handshake | drinking, toast", groups="bar fight | gang pose"),
      f="corset dress | cowboy hat, duster | ruffled skirt | riding outfit", m="cowboy hat, duster | vest, holster | poncho | sheriff star",
      light="dusty sunbeam | oil lamps | sunset | lantern light", mood="tense cool", surf="table:poker table|chair:wooden chair|wall:bar counter",
      zones=[
          Z("Poker table", "saloon, poker table | saloon interior | gambling table", "cards | poker chips | whiskey | revolver", solo="holding cards | tipping hat | shuffling cards | stacking chips",
            pair="staring down, cards | dealing cards", groups="poker game | standoff, table"),
          Z("Bar counter", "saloon bar | bar counter, bottles | wooden bar", "whiskey bottles | shot glass | spittoon | mirror", solo="leaning on bar | drinking whiskey",
            pair="drinking together | sliding glass", groups="crowded bar"),
          Z("Main street", "dusty street, western town | main street, saloon doors | frontier town", "tumbleweed | hitching post | horses | water trough",
            solo="walking, dusty street | hand near holster", pair="duel | walking, horses", groups="posse | standoff"),
      ]),
    P("Sci-fi bridge", detail="holograms | blinking lights | star chart | alarm lights | metal floor | headset", acts=dict(solo="touching hologram | arms crossed, determined | saluting", pair="handshake | pointing at hologram | looking at screen, together", groups="salute, crew | huddled, hologram"),
      f="flight suit | captain uniform | bodysuit | officer uniform", m="captain uniform | flight suit | engineer overalls | officer coat",
      light="console glow | red alert lighting | holographic light | blue light", mood="serious tense", surf="chair:captain chair|table:console|wall:viewport",
      zones=[
          Z("Captain chair", "starship bridge | command deck | bridge, viewscreen", "viewscreen, stars | consoles | crew stations", solo="sitting, captain chair | pointing forward",
            pair="consulting, console | standing by chair", groups="bridge crew | crew at stations"),
          Z("Viewport", "viewport, planet | observation window | stars, viewport", "planet | nebula | stars", solo="looking out viewport | hand on glass",
            pair="watching planet together", groups="crew at window"),
          Z("Engine room", "engine room | reactor core | engineering deck", "reactor glow | pipes | steam | warning lights", solo="repairing panel | holding tool",
            pair="repairing together | shouting over noise", groups="crew, engine room"),
      ]),
    P("Heist", detail="blueprints | earpiece | night vision goggles | security camera | glass cutter | timer", acts=dict(solo="touching earpiece | crouching, stealth | holding blueprints", pair="back-to-back, crouching | fist bump | handing bag", groups="huddled, blueprints | slow motion walk"),
      f="black catsuit | suit, sunglasses | evening gown, gloves | maintenance uniform", m="black suit, sunglasses | turtleneck | security uniform | tuxedo",
      light="laser lights | security light | flashlight | dim light", mood="tense cool", surf="table:display case|wall:vault door|floor:marble floor",
      zones=[
          Z("Vault", "bank vault | vault door, open | safe deposit boxes", "gold bars | cash stacks | vault door | drill", solo="cracking safe | holding gold bar",
            pair="filling bags | stethoscope, safe", groups="crew, vault"),
          Z("Laser hall", "museum, laser grid | gallery, lasers | security corridor", "red lasers | display case | diamond", solo="dodging lasers | bending backward",
            pair="guiding through lasers", groups="crew, lasers"),
          Z("Getaway", "parking garage, getaway car | alley, van | street, night, car", "getaway car | duffel bag | headlights", solo="running, duffel bag | jumping into car",
            pair="driving fast | running together", groups="crew running"),
      ]),
    P("Silent movie set", detail="film grain | intertitle card | piano player | velvet rope | makeup kit | spotlights", acts=dict(solo="hand on forehead, fainting | twirling cane | blowing kiss", pair="tango | slapstick chase | dramatic embrace", groups="taking bow | crowd scene"),
      f="1920s dress, cloche hat | flapper dress | pearl necklace, gloves | stage makeup", m="suit, bowler hat | tuxedo, cane | suspenders, cap | director, megaphone",
      light="stage lights | spotlight | black and white | film projector light", mood="happy playful", surf="chair:director chair|floor:stage floor|wall:painted backdrop",
      zones=[
          Z("Stage", "film set, painted backdrop | silent movie set | soundstage", "film camera | clapperboard | spotlight | painted moon",
            solo="dramatic pose | swooning", pair="dramatic kiss, stage | chase scene", groups="slapstick, stage"),
          Z("Director chair", "director chair, set | film set, crew | studio lot", "megaphone | script | film reels", solo="reading script | sitting, director chair",
            pair="rehearsing lines", groups="crew, set"),
          Z("Projection room", "projection room | cinema, projector | screening room", "projector beam | film reel | dust in light", solo="threading film | watching screen",
            pair="watching, screen", groups="screening, audience"),
      ]),
    P("Road movie", detail="motel sign | cassette tapes | desert road | sunglasses | road map | cigarette pack", acts=dict(solo="sitting on car hood | hitchhiking, thumb up | looking at map", pair="kiss, car | arguing, map | sharing cigarette", groups="singing, car | sitting on car"),
      f="denim jacket, sundress | tank top, jeans | sunglasses, scarf | flannel shirt", m="leather jacket | t-shirt, jeans | flannel shirt | aviator sunglasses",
      light="golden hour | headlights | dusk | harsh sunlight", mood="happy melancholy", surf="chair:car seat|wall:car door",
      zones=[
          Z("Convertible", "convertible, highway | car interior, highway | open road, car", "map | sunglasses | hair blowing | radio",
            solo="driving | feet on dashboard | arm out window", pair="driving together | laughing, car", groups="road trip, car"),
          Z("Diner", "roadside diner | diner booth | 50s diner", "milkshake | jukebox | pie | neon sign", solo="sitting in booth | drinking milkshake",
            pair="sharing milkshake | booth, across", groups="crowded booth"),
          Z("Gas station", "gas station, night | gas pump, desert | rural gas station", "gas pump | vending machine | neon sign", solo="pumping gas | leaning on car",
            pair="buying snacks | leaning on car, together", groups="stretching, gas station"),
      ]),
    P("Gothic horror set", detail="fog | ravens | candle wax | stained glass | rusted keys | portrait, eyes", acts=dict(solo="holding candelabra | looking back, frightened | hand on wall", pair="embrace, fear | hiding behind another | holding candle, together", groups="huddled, candle | fleeing"),
      f="victorian gown | nightgown, candle | black lace dress | widow veil", m="frock coat | cape, vampire | victorian suit | priest cassock",
      light="candlelight | moonlight | lightning | torchlight", mood="tense melancholy", surf="bed:canopy bed|wall:stone wall|floor:stone floor",
      zones=[
          Z("Castle hall", "castle hall | gothic hall, candles | castle interior, stairs", "candelabra | cobwebs | suits of armor | portraits",
            solo="holding candle | walking, hall", pair="waltz, empty hall | confrontation", groups="ballroom, ghosts"),
          Z("Crypt", "crypt | catacombs | tomb, coffins", "coffins | skulls | candles | stone angels", solo="opening coffin | kneeling, tomb",
            pair="holding torch, crypt", groups="exploring crypt"),
          Z("Bedchamber", "canopy bed, castle | gothic bedroom | bedchamber, curtains", "canopy bed | moonlit window | curtains, wind", solo="sleepwalking | sitting up, bed",
            pair="leaning over bed", groups="vigil, bed"),
      ]),
    P("Musical", detail="glitter | feather boas | top hats | staircase, stage | orchestra pit | confetti", acts=dict(solo="jazz hands | high kick | spinning", pair="lift, dance | dip, dance | tap dancing, together", groups="kickline | finale pose"),
      f="sequin dress | tap shoes, skirt | showgirl costume | top hat, tailcoat", m="tailcoat, top hat | sailor uniform | suspenders, tap shoes | white suit",
      light="spotlight | stage lights | footlights | colorful lights", mood="happy playful", surf="floor:stage|wall:curtain",
      zones=[
          Z("Stage", "theater stage | broadway stage | musical stage", "spotlight | curtains | footlights | confetti", solo="singing, spotlight | dancing, kick",
            pair="duet | dancing together, twirl", groups="chorus line | dance number"),
          Z("Rain street set", "street set, rain | studio street, lamp post | rainy set", "lamp post | umbrella | puddle", solo="dancing in rain | swinging, lamp post",
            pair="dancing, umbrella", groups="dancing, umbrellas"),
          Z("Rehearsal room", "rehearsal room, mirrors | dance studio, barre | rehearsal hall", "barre | mirrors | piano", solo="stretching at barre | rehearsing",
            pair="practicing steps", groups="rehearsal, group"),
      ]),
    P("Kung fu film", detail="paper lanterns | incense smoke | calligraphy scroll | falling petals | wooden staff | straw hats", acts=dict(solo="fighting stance | flying kick | bowing, fist and palm", pair="sparring | back-to-back, fighting | bowing, fist and palm", groups="surrounded, fighting | training in rows"),
      f="qipao | martial arts uniform | hanfu | black outfit, sash", m="martial arts uniform | changshan | monk robe | black outfit, headband",
      light="lantern light | dramatic sunset | moonlight | dappled light, bamboo", mood="serious tense", surf="floor:wooden floor|wall:wooden wall|table:tea table",
      zones=[
          Z("Dojo", "dojo | kung fu school | training hall", "wooden dummy | weapons rack | banners", solo="fighting stance | punching | training, wooden dummy",
            pair="sparring | master and student", groups="training, group"),
          Z("Bamboo forest", "bamboo forest | bamboo, mist | forest, bamboo", "bamboo | mist | falling leaves", solo="sword stance | leaping",
            pair="sword fight | duel, bamboo", groups="ambush, bamboo"),
          Z("Tea house", "tea house | inn, wooden | teahouse balcony", "teapot | lanterns | wine jar", solo="pouring tea | drinking tea",
            pair="tea, across table | brawl, tea house", groups="brawl, tea house"),
      ]),
], "cinematic still, anamorphic, film grain | 35mm film, technicolor | film noir, black and white | movie poster", NSFW, "cinematic shot | medium shot | wide shot")
