from lib import P, Z, theme

NSFW = "photorealistic, detailed skin | hentai, anime coloring | painterly, erotic illustration | soft focus photography"

theme("food", "Food", [
    P("Cafe", f="knit sweater | apron, rolled sleeves | sundress, cardigan | blouse, skirt", m="apron, shirt | knit sweater | flannel shirt | denim jacket",
      light="morning light, window | warm pendant lights | afternoon sun | rainy window light", mood="calm happy", surf="table:cafe table|chair:chair|wall:window",
      detail="latte art | steam | pastries | coffee beans | chalkboard menu | potted plants",
      acts=dict(solo="holding cup, steam | reading, cafe | writing in notebook", pair="sitting across table | sharing dessert | laughing, coffee", groups="crowded table | coffee meetup"),
      zones=[
          Z("Window seat", "cafe, window seat | cafe interior, window, street | cozy cafe, window", "rain on window | croissant | open book | smartphone | cinnamon roll",
            solo="sitting by window | looking outside | chin on hand", pair="holding hands, table | window seat, together", groups="squeezed, window table"),
          Z("Counter", "cafe counter, espresso machine | coffee bar | barista counter", "espresso machine | milk pitcher | tip jar | cups stacked | grinder",
            solo="barista, latte art | ordering coffee | tamping espresso", pair="ordering, counter | barista, customer", groups="queue, counter"),
          Z("Terrace", "cafe terrace | sidewalk cafe, umbrellas | outdoor tables, cafe", "parasol | bicycle | street | pigeons | sunglasses",
            solo="sunbathing, terrace | people watching", pair="breakfast, terrace | toast, coffee cups", groups="brunch, terrace"),
      ]),
    P("Ramen shop", f="hoodie | casual clothes | business suit | jacket, scarf", m="business suit | hoodie | work clothes | jacket",
      light="warm light, steam | night, lantern | neon outside | fluorescent light", mood="happy calm", surf="table:counter|chair:stool",
      detail="steam | ramen bowl | chopsticks | noren curtain | menu tickets | soft-boiled egg",
      acts=dict(solo="eating ramen | slurping noodles | blowing on noodles", pair="eating ramen, side by side | sharing gyoza | cheers, beer", groups="ramen, group | crowded counter"),
      zones=[
          Z("Counter seats", "ramen shop counter | ramen bar | noodle counter", "open kitchen | broth pot | chef | stools", solo="sitting at counter | waiting, chopsticks",
            pair="sitting at counter, together | talking, counter", groups="row, counter"),
          Z("Kitchen", "ramen kitchen | noodle kitchen, steam | open kitchen", "boiling pots | noodle baskets | ladles | towels", solo="chef, cooking noodles | straining noodles",
            pair="cooking together", groups="kitchen crew"),
          Z("Entrance", "ramen shop entrance, noren | ticket machine, entrance | night street, ramen shop", "noren | lantern | ticket machine | queue", solo="buying ticket | entering, noren",
            pair="queue, night", groups="queue, entrance"),
      ]),
    P("Bakery", f="apron, flour | cardigan, skirt | linen dress, apron | headscarf, apron", m="apron, flour | baker uniform | flannel shirt | t-shirt, apron",
      light="warm morning light | oven glow | soft window light | golden light", mood="happy calm", surf="table:work table|chair:stool|wall:shelves",
      detail="fresh bread | flour dust | baskets | croissants | rolling pin | wooden shelves",
      acts=dict(solo="kneading dough | holding bread | smelling bread", pair="baking together | flour on face | tasting bread", groups="bakery team | shopping, bakery"),
      zones=[
          Z("Oven", "bakery oven | brick oven, bakery | bakery kitchen, oven", "oven glow | baking trays | peel | heat", solo="taking bread from oven | oven mitts",
            pair="checking oven together", groups="kitchen rush"),
          Z("Counter", "bakery counter | pastry display | bakery shop", "pastry case | price tags | paper bags | cakes", solo="choosing pastry | serving customer",
            pair="buying bread | pointing, pastries", groups="customers, bakery"),
          Z("Work table", "flour-dusted table | bakery workbench | dough table", "dough | flour | scale | knife", solo="shaping dough | rolling dough", pair="flour fight",
            groups="baking class"),
      ]),
    P("Fine dining", f="evening gown | cocktail dress | satin dress, pearls | black dress", m="tuxedo | suit, necktie | velvet blazer | dinner jacket",
      light="candlelight | chandelier | dim warm light | city lights, window", mood="calm cool", surf="table:dining table|chair:velvet chair",
      detail="wine glasses | candles | white tablecloth | silverware | tasting menu | chef plating",
      acts=dict(solo="tasting wine | dining alone | looking at menu", pair="toasting | candlelit dinner | feeding another", groups="dinner party | toast, group"),
      zones=[
          Z("Dining room", "fine dining restaurant | elegant dining room | restaurant, chandeliers", "chandelier | tablecloth | flowers | waiters", solo="sitting, table, wine",
            pair="romantic dinner | holding hands, table", groups="banquet table"),
          Z("Chef's table", "chef's table, kitchen | kitchen counter, fine dining | open kitchen", "plating tweezers | sauces | flames | chef", solo="chef plating | tasting sauce",
            pair="chef, guest | watching chef", groups="chef's table, guests"),
          Z("Wine cellar", "wine cellar | cellar, barrels | wine vault", "wine racks | barrels | candles", solo="choosing wine | tasting, cellar", pair="wine tasting, together",
            groups="wine tasting, group"),
      ]),
    P("Street food", f="t-shirt, shorts | tank top | hoodie | sundress", m="t-shirt | tank top | hoodie | shirt, shorts",
      light="neon lights | night, lanterns | sunny day | grill fire", mood="happy playful", surf="table:plastic table|chair:stool",
      detail="grill smoke | skewers | sauce | paper plates | crowd | food truck",
      acts=dict(solo="eating skewer | holding taco | licking fingers", pair="sharing food | feeding another | food tasting", groups="food crawl | eating together"),
      zones=[
          Z("Food truck", "food truck | food truck, line | truck window", "menu board | napkins | line", solo="ordering, truck window | waiting, line", pair="sharing fries",
            groups="line, food truck"),
          Z("Grill stall", "grill stall | street grill, smoke | bbq stall", "flames | skewers | smoke", solo="grilling | fanning smoke", pair="grilling together",
            groups="crowd, grill"),
          Z("Picnic tables", "picnic tables, food court | outdoor food court | beer garden", "beer | lights | paper plates", solo="eating, table | drinking beer",
            pair="cheers | sitting across", groups="beer garden, group"),
      ]),
    P("Farmers market", f="sundress, basket | denim overalls | linen shirt | cardigan", m="flannel shirt | apron | denim jacket | t-shirt",
      light="morning sun | overcast | soft light | golden hour", mood="happy calm", surf="table:stall table",
      detail="fruit crates | vegetables | flowers | honey jars | wicker baskets | chalk prices",
      acts=dict(solo="holding basket | choosing fruit | smelling flowers", pair="shopping together | tasting samples | carrying basket, together", groups="crowd, market"),
      zones=[
          Z("Fruit stall", "fruit stall | market, fruit crates | produce stand", "apples | berries | scale | crates", solo="picking apple | tasting berry", pair="sharing fruit",
            groups="crowd, fruit"),
          Z("Flower stall", "flower stall | flower market | bouquets, market", "bouquets | buckets | tulips", solo="holding bouquet | arranging flowers", pair="buying flowers, another",
            groups="flower stall, crowd"),
          Z("Cheese stall", "cheese stall | deli stand | market, cheese", "cheese wheels | bread | olives", solo="tasting cheese | slicing cheese", pair="tasting together",
            groups="tasting, group"),
      ]),
    P("Home kitchen", f="apron | oversized shirt | casual clothes | pajamas", m="apron | t-shirt | casual clothes | henley",
      light="morning light | warm kitchen light | evening lamp | window light", mood="happy calm", surf="table:kitchen counter|chair:stool|wall:fridge|floor:kitchen floor",
      detail="pots | herbs | cutting board | spices | fruit bowl | steam",
      acts=dict(solo="cooking | chopping vegetables | tasting, spoon", pair="cooking together | feeding, spoon | hug from behind, cooking", groups="cooking party | dinner prep"),
      zones=[
          Z("Stove", "kitchen stove | stovetop, pans | home kitchen, stove", "frying pan | flames | wooden spoon", solo="stirring pot | flipping pancake", pair="tasting sauce, together",
            groups="crowded stove"),
          Z("Island", "kitchen island | counter, stools | open kitchen", "fruit bowl | wine glasses | laptop", solo="sitting on counter | leaning, island", pair="breakfast, island",
            groups="snacks, island"),
          Z("Dining nook", "breakfast nook | kitchen table | dining corner", "coffee | newspaper | toast", solo="breakfast | reading newspaper", pair="breakfast together",
            groups="shared meal"),
      ]),
    P("Tea house", f="kimono | hanfu | qipao | cardigan, skirt", m="hakama | changshan | linen shirt | cardigan",
      light="soft light | paper lantern | rainy window | morning light", mood="calm", surf="table:low table|floor:tatami",
      detail="teapot | tea cups | incense | bonsai | calligraphy | rain sound",
      acts=dict(solo="pouring tea | holding tea cup | tea ceremony", pair="tea ceremony, together | conversation, tea | bowing", groups="tea gathering | tea tasting"),
      zones=[
          Z("Tatami room", "tatami room, tea | japanese tea room | washitsu", "tatami | tokonoma | scroll | kettle", solo="kneeling, tea | whisking matcha", pair="tea ceremony, guest",
            groups="tea ceremony, guests"),
          Z("Garden pavilion", "tea pavilion, garden | gazebo, pond | garden teahouse", "pond | koi | willow", solo="sitting, pavilion | feeding koi", pair="tea, pond view",
            groups="pavilion, guests"),
          Z("Shop counter", "tea shop | tea shop, jars | tea counter", "tea jars | scales | packets", solo="smelling tea leaves | weighing tea", pair="tasting tea, shop",
            groups="tea tasting, shop"),
      ]),
    P("Diner", f="waitress uniform | t-shirt, jeans | leather jacket | sundress", m="t-shirt, jeans | leather jacket | cook uniform | flannel",
      light="neon, night | fluorescent light | morning sun | dusk, window", mood="happy calm", surf="table:booth table|chair:booth|wall:counter",
      detail="milkshake | jukebox | checkered floor | pie | coffee pot | ketchup bottle",
      acts=dict(solo="drinking milkshake | eating burger | reading menu", pair="sharing milkshake | sitting in booth, together | arguing, booth", groups="crowded booth | late night, diner"),
      zones=[
          Z("Booth", "diner booth | red booth, window | 50s diner, booth", "jukebox | ketchup | fries", solo="sitting, booth | eating fries", pair="booth, across table",
            groups="booth, crowd"),
          Z("Counter", "diner counter | counter stools | lunch counter", "coffee pot | pies | stools", solo="sitting, counter stool | coffee refill", pair="counter, side by side",
            groups="row, counter"),
          Z("Parking lot", "diner parking lot, neon | diner exterior, night | roadside diner", "neon sign | cars | sign", solo="leaning on car, neon | eating, car hood",
            pair="sitting on car hood", groups="parking lot, group"),
      ]),
], "food photography | cozy illustration | anime illustration, food | watercolor, warm", NSFW, "upper body | cowboy shot | from above | close-up")

theme("home", "Home", [
    P("Living room", f="oversized sweater | pajamas | t-shirt, shorts | cardigan, leggings", m="hoodie | t-shirt, sweatpants | pajamas | flannel shirt",
      light="lamp light | afternoon sun | tv glow | fireplace glow", mood="calm happy", surf="chair:sofa|floor:rug|table:coffee table|wall:wall",
      detail="throw pillows | blanket | houseplants | coffee mug | remote | bookshelf",
      acts=dict(solo="lying on sofa | reading, sofa | hugging pillow", pair="cuddling, sofa | watching tv together | pillow fight", groups="movie night | board game"),
      zones=[
          Z("Sofa", "living room, sofa | couch, living room | cozy living room", "blanket | pillows | popcorn | cat", solo="curled up, sofa | napping, sofa", pair="head on lap, sofa",
            groups="crowded sofa"),
          Z("Fireplace", "fireplace, living room | hearth, rug | fireplace, armchair", "fire | stockings | logs | candles", solo="warming hands, fire | sitting, rug, fire",
            pair="blanket, fire | hot cocoa, together", groups="gathered, fireplace"),
          Z("Bookshelf", "bookshelf, reading corner | living room, bookshelf | reading corner", "books | lamp | armchair", solo="reading, armchair | choosing book",
            pair="reading together", groups="book club"),
      ]),
    P("Bedroom", f="pajamas | oversized shirt | nightgown | t-shirt, shorts", m="pajamas | t-shirt, boxers | sweatpants | tank top",
      light="morning light | lamp light | night, moonlight | fairy lights", mood="calm happy", surf="bed:bed|floor:rug|wall:wall|chair:chair",
      detail="messy sheets | pillows | alarm clock | fairy lights | plush toy | phone, charger",
      acts=dict(solo="waking up, stretching | lying on bed, phone | sleeping", pair="cuddling, bed | pillow fight | breakfast in bed", groups="sleepover | pillow fight"),
      zones=[
          Z("Bed", "bedroom, bed | cozy bedroom | bed, white sheets", "sheets | duvet | pillows", solo="lying on bed | sitting on bed, phone", pair="lying on bed, together",
            groups="pile on bed"),
          Z("Vanity", "vanity table, mirror | bedroom vanity | dressing table", "makeup | perfume | mirror | jewelry", solo="brushing hair | makeup, mirror", pair="doing hair, another",
            groups="getting ready, together"),
          Z("Window", "bedroom window, morning | bay window, bedroom | window, curtains", "curtains | sunlight | plants", solo="opening curtains | sitting, windowsill",
            pair="looking outside together", groups="window, group"),
      ]),
    P("Bathroom", f="bathrobe | towel | pajamas | t-shirt", m="bathrobe | towel | t-shirt | pajamas",
      light="soft light | morning light | candles | steam, light", mood="calm", surf="water:bathtub|wall:tiled wall|floor:bath mat",
      detail="steam | towels | bath bubbles | rubber duck | toothbrush | mirror, fog",
      acts=dict(solo="brushing teeth | washing face | wrapping towel", pair="brushing teeth, together | drying hair, another | morning routine", groups="crowded bathroom"),
      zones=[
          Z("Sink", "bathroom sink, mirror | vanity, bathroom | sink, morning", "toothpaste | foggy mirror | soap", solo="brushing teeth | skincare", pair="side by side, mirror",
            groups="queue, bathroom"),
          Z("Bathtub", "bathtub, bubbles | clawfoot tub | bath, candles", "bubbles | candles | bath salts", solo="relaxing, bath | bubbles, bath", pair="bath together",
            groups="hot tub"),
          Z("Shower", "shower, glass | walk-in shower | rain shower", "water droplets | steam | shampoo", solo="showering | washing hair", pair="shower together",
            groups="showers"),
      ]),
    P("Balcony", f="sundress | t-shirt, shorts | cardigan | silk robe", m="t-shirt | linen shirt | hoodie | robe",
      light="sunset | morning sun | city lights | rain", mood="calm happy", surf="chair:deck chair|wall:railing|floor:balcony floor",
      detail="potted plants | laundry | city view | coffee | wind chime | string lights",
      acts=dict(solo="watering plants | drinking coffee | leaning on railing", pair="coffee together | sunset, together | hanging laundry", groups="balcony party | barbecue"),
      zones=[
          Z("Plants", "balcony garden | plants, balcony | balcony, herbs", "herbs | flowers | watering can", solo="watering plants | repotting", pair="gardening together",
            groups="gardening, group"),
          Z("Railing", "balcony railing, city | balcony, view | apartment balcony", "city view | wind | birds", solo="leaning on railing | looking at city", pair="leaning on railing, together",
            groups="railing, group"),
          Z("Laundry", "balcony, laundry line | hanging laundry | clothesline, balcony", "clothespins | sheets | wind", solo="hanging laundry | folding clothes",
            pair="hanging sheets together", groups="laundry, group"),
      ]),
    P("Attic", f="overalls | sweater | flannel | cardigan, skirt", m="flannel shirt | overalls | sweater | t-shirt",
      light="dusty sunbeam | lamp light | skylight | candlelight", mood="calm melancholy", surf="floor:wooden floor|chair:old chair|bed:mattress",
      detail="dust | boxes | old trunk | rocking horse | photo albums | cobwebs",
      acts=dict(solo="opening trunk | looking at photos | sitting, dust", pair="looking at old photos | exploring attic | trying old clothes", groups="cleaning attic"),
      zones=[
          Z("Trunk", "attic, old trunk | attic storage | attic, boxes", "trunk | letters | old dresses", solo="reading letters | trying on hat", pair="opening trunk, together",
            groups="treasure hunt, attic"),
          Z("Skylight", "attic skylight | attic window, round | slanted roof, window", "skylight | stars | dust", solo="looking at stars | lying under skylight",
            pair="stargazing, skylight", groups="stargazing, attic"),
          Z("Hideout", "attic hideout | attic bedroom | cozy attic", "fairy lights | mattress | pillows", solo="reading, fairy lights | lying, mattress", pair="secret hideout",
            groups="hideout, group"),
      ]),
    P("Garden", f="sundress | gardening overalls | t-shirt, shorts | straw hat, dress", m="t-shirt | overalls | linen shirt | shorts",
      light="sunny day | golden hour | morning light | overcast", mood="happy calm", surf="floor:lawn|chair:garden chair|table:garden table",
      detail="flower beds | watering can | garden gnome | vegetable patch | bees | hose",
      acts=dict(solo="gardening | watering plants | picking flowers", pair="gardening together | picnic, lawn | hose, splashing", groups="garden party | barbecue"),
      zones=[
          Z("Vegetable patch", "vegetable garden | garden beds | allotment", "tomatoes | dirt | trowel", solo="picking tomatoes | digging", pair="harvest together",
            groups="harvest, group"),
          Z("Lawn", "garden lawn | backyard, lawn | grass, garden", "sprinkler | lawn chairs | ball", solo="lying on grass | sprinkler", pair="sprinkler, playing",
            groups="lawn games"),
          Z("Patio", "patio, garden | backyard patio | patio, grill", "grill | lanterns | table", solo="grilling | sitting, patio", pair="dinner, patio",
            groups="barbecue, patio"),
      ]),
    P("Home office", f="cardigan | blouse, pajama pants | sweater | t-shirt", m="hoodie | shirt, pajama pants | t-shirt | sweater",
      light="monitor glow | window light | desk lamp | night", mood="calm serious", surf="chair:office chair|table:desk|bed:sofa bed",
      detail="laptop | coffee mug | sticky notes | plants | headphones | stacks of paper",
      acts=dict(solo="typing, laptop | video call | stretching, chair", pair="working together | distracting another | coffee break", groups="study group"),
      zones=[
          Z("Desk", "home office desk | desk, monitor | workspace", "monitor | keyboard | mug", solo="typing | headphones, typing", pair="looking at screen, together",
            groups="crowded desk"),
          Z("Reading chair", "reading chair, office | armchair, lamp | office corner", "lamp | books | blanket", solo="reading, chair | napping, chair", pair="reading together",
            groups="discussion, chairs"),
          Z("Window desk", "desk by window | window, workspace | sunny desk", "window | plants | coffee", solo="looking out window | writing", pair="working, window",
            groups="workshop, home"),
      ]),
    P("Laundry room", f="t-shirt, shorts | tank top, leggings | oversized shirt | sweater", m="t-shirt | tank top | sweatpants | hoodie",
      light="fluorescent light | window light | warm light | morning sun", mood="calm happy", surf="table:dryer|wall:washing machine|floor:floor",
      detail="laundry basket | detergent | socks | dryer sheets | ironing board | hangers",
      acts=dict(solo="folding clothes | loading washer | ironing", pair="folding sheets together | sitting on washer | sock pairing", groups="laundry day"),
      zones=[
          Z("Machines", "laundry room, washer | utility room | washer, dryer", "washer | dryer | detergent", solo="loading washer | sitting on washer", pair="sitting on dryer, together",
            groups="laundry, group"),
          Z("Ironing", "ironing board, laundry room | ironing corner | laundry, iron", "iron | steam | shirts", solo="ironing shirt", pair="ironing, chatting", groups="ironing line"),
          Z("Drying rack", "drying rack | clothesline, indoor | laundry, rack", "drying rack | towels | socks", solo="hanging clothes", pair="hanging clothes together",
            groups="drying, group"),
      ]),
    P("Kitchen night", f="pajamas | oversized shirt | camisole, shorts | robe", m="pajamas | t-shirt | boxers, t-shirt | robe",
      light="fridge light | moonlight | dim lamp | microwave light", mood="calm playful", surf="table:counter|wall:fridge|floor:kitchen floor",
      detail="open fridge | midnight snack | ice cream tub | moonlight | cereal bowl | glass of milk",
      acts=dict(solo="midnight snack | eating ice cream | drinking milk", pair="sneaking snacks | sharing ice cream | whispering, kitchen", groups="midnight snack, group"),
      zones=[
          Z("Fridge", "open fridge, night | kitchen, fridge light | fridge, dark kitchen", "fridge light | leftovers | milk", solo="looking in fridge | drinking from carton",
            pair="caught, fridge", groups="crowded fridge"),
          Z("Counter", "kitchen counter, night | counter, moonlight | kitchen island, night", "snacks | cereal | spoon", solo="sitting on counter | eating cereal",
            pair="sitting on counter, together", groups="snacks, counter"),
          Z("Window", "kitchen window, night | window, moon | sink, window", "moon | rain | plants", solo="looking at moon | washing dishes", pair="dishes together",
            groups="window, group"),
      ]),
], "cozy illustration | photorealistic, warm tones | anime illustration, slice of life | film photography, home", NSFW, "upper body | cowboy shot | full body | from side")

theme("sports", "Sports", [
    P("Tennis court", f="tennis dress | tank top, tennis skirt | polo shirt, shorts | visor, sportswear", m="polo shirt, shorts | tennis outfit | headband, t-shirt | tracksuit",
      light="sunny day | stadium lights | golden hour | overcast", mood="serious happy", surf="floor:court|wall:net|chair:bench",
      detail="tennis balls | racket | net | sweatband | water bottle | towel",
      acts=dict(solo="serving | backhand | wiping sweat", pair="handshake, net | doubles | rally", groups="doubles team | tournament"),
      zones=[
          Z("Baseline", "tennis court, baseline | clay court | hard court", "lines | clay dust | ball", solo="serving, toss | running, ball", pair="rally", groups="practice drill"),
          Z("Net", "tennis net | court, net | net, close-up", "net | ball | racket", solo="volley, net | jumping, net", pair="handshake, net", groups="team, net"),
          Z("Bench", "courtside bench | bench, towels | sideline", "towels | bottles | bags", solo="resting, bench | drinking water", pair="sitting, bench, together",
            groups="team bench"),
      ]),
    P("Basketball", f="basketball uniform | tank top, shorts | hoodie, shorts | sports bra, shorts", m="basketball uniform | tank top, shorts | hoodie | jersey",
      light="gym lights | sunset, outdoor court | night, floodlights | overcast", mood="serious happy", surf="floor:court|wall:wall|chair:bench",
      detail="basketball | hoop | chain net | scoreboard | sneakers | sweat",
      acts=dict(solo="dribbling | shooting | slam dunk", pair="one-on-one | high five | defending", groups="team huddle | pickup game"),
      zones=[
          Z("Street court", "outdoor basketball court | street court, fence | playground court", "chain net | fence | graffiti", solo="dribbling, street court | layup",
            pair="one-on-one, street", groups="pickup game"),
          Z("Arena", "basketball arena | indoor court, crowd | stadium, court", "crowd | scoreboard | lights", solo="free throw | celebrating", pair="chest bump",
            groups="team celebration"),
          Z("Locker room", "locker room | gym lockers | changing room", "lockers | towels | benches", solo="sitting, bench | taping hands", pair="pep talk", groups="team huddle, locker room"),
      ]),
    P("Pool", f="competition swimsuit | swim cap, goggles | swimsuit | towel, swimsuit", m="swim briefs | swim cap, goggles | jammers | towel",
      light="indoor pool light | sunlight, water | underwater light | overcast", mood="serious calm", surf="water:pool|floor:pool deck|chair:bench",
      detail="lane ropes | water splash | starting block | chlorine | goggles | caustics",
      acts=dict(solo="diving | swimming | adjusting goggles", pair="racing | high five, pool | sitting on edge, together", groups="relay team | swim practice"),
      zones=[
          Z("Lanes", "swimming pool, lanes | olympic pool | lap pool", "lane ropes | splash | clock", solo="freestyle | butterfly stroke", pair="racing, lanes",
            groups="swim practice, lanes"),
          Z("Diving board", "diving board | diving platform | high dive", "board | splash | height", solo="diving, mid-air | standing, board", pair="cheering, diver",
            groups="diving team"),
          Z("Pool deck", "pool deck | poolside | edge of pool", "towels | puddles | starting blocks", solo="sitting, pool edge | drying off", pair="sitting, edge, together",
            groups="team, poolside"),
      ]),
    P("Boxing gym", f="sports bra, boxing shorts | tank top, hand wraps | hoodie, shorts | boxing gloves", m="boxing shorts | tank top, hand wraps | hoodie | shirtless, gloves",
      light="harsh overhead light | dim gym light | spotlight, ring | window light", mood="serious tense", surf="floor:ring|wall:ropes|chair:corner stool",
      detail="punching bags | sweat | ropes | boxing gloves | tape | water bottle",
      acts=dict(solo="punching bag | shadow boxing | taping hands", pair="sparring | holding pads | corner talk", groups="training session | crowd, ringside"),
      zones=[
          Z("Ring", "boxing ring | ring, ropes | boxing match", "ropes | canvas | corner | referee", solo="fighting stance | uppercut", pair="sparring, ring",
            groups="match, crowd"),
          Z("Heavy bags", "heavy bags, gym | boxing gym, bags | training area", "heavy bags | chains | mirrors", solo="hitting bag | jab", pair="holding bag, another",
            groups="bag drills"),
          Z("Locker room", "boxing locker room | changing room | gym lockers", "towels | ice pack | bench", solo="sitting, bench, exhausted | wrapping hands",
            pair="tending wounds", groups="team, locker room"),
      ]),
    P("Running track", f="running outfit | sports bra, shorts | tank top, leggings | track jacket", m="running outfit | tank top, shorts | track jacket | compression shirt",
      light="sunrise | sunny day | stadium lights | golden hour", mood="serious happy", surf="floor:track|chair:bleachers",
      detail="starting blocks | lane lines | stopwatch | sweat | finish line | hurdles",
      acts=dict(solo="sprinting | stretching | starting position", pair="racing | high five, finish | stretching together", groups="relay | team warmup"),
      zones=[
          Z("Start line", "starting line, track | starting blocks | track, start", "blocks | lane numbers | starter", solo="crouch start | set position", pair="side by side, start",
            groups="lined up, start"),
          Z("Finish line", "finish line | track, finish | stadium, finish line", "tape | crowd | clock", solo="crossing finish | arms raised", pair="photo finish",
            groups="celebration, finish"),
          Z("Bleachers", "stadium bleachers | bleachers, track | stands", "bleachers | water bottles | bags", solo="sitting, bleachers | drinking water", pair="sitting together, bleachers",
            groups="team, bleachers"),
      ]),
    P("Ski slope", f="ski suit, goggles | puffer jacket | snowboard outfit | knit hat", m="ski suit | snowboard outfit | puffer jacket | beanie, goggles",
      light="bright snow | sunny day | overcast | sunset, snow", mood="happy playful", surf="floor:snow|chair:ski lift",
      detail="skis | snowboard | ski poles | powder | goggles | pine trees",
      acts=dict(solo="skiing | snowboarding | falling in snow", pair="ski lift, together | racing downhill | helping up", groups="ski group | apres ski"),
      zones=[
          Z("Slope", "ski slope | piste | mountain slope", "powder | tracks | flags", solo="carving | jumping, snowboard", pair="skiing together", groups="skiing group"),
          Z("Ski lift", "ski lift | chairlift, mountains | gondola", "chairlift | cables | view", solo="riding chairlift", pair="chairlift, together", groups="gondola, group"),
          Z("Lodge", "ski lodge | chalet, fireplace | mountain lodge", "fireplace | hot cocoa | boots", solo="hot cocoa | warming up", pair="cocoa, together", groups="apres ski, group"),
      ]),
    P("Climbing gym", f="climbing outfit | tank top, leggings | sports bra, harness | t-shirt, pants", m="climbing outfit | tank top | harness | t-shirt",
      light="gym lights | skylight | warm light | bright light", mood="serious happy", surf="wall:climbing wall|floor:crash pad",
      detail="climbing holds | chalk | ropes | carabiners | crash pads | climbing shoes",
      acts=dict(solo="climbing | chalking hands | hanging, hold", pair="belaying | spotting | high five, top", groups="climbing session"),
      zones=[
          Z("Bouldering", "bouldering wall | bouldering gym | boulder, crash pads", "holds | chalk | mats", solo="bouldering | reaching", pair="spotting, boulder",
            groups="watching climber"),
          Z("Top rope", "top rope wall | tall climbing wall | lead wall", "rope | anchors | height", solo="climbing high | rappelling", pair="belaying another",
            groups="ropes, group"),
          Z("Outdoor crag", "rock cliff, climbing | crag, sunset | climbing, cliff", "rock face | sky | quickdraws", solo="climbing cliff", pair="belaying, cliff",
            groups="crag, group"),
      ]),
    P("Soccer field", f="soccer uniform | jersey, shorts | track suit | sports bra, shorts", m="soccer uniform | jersey | track suit | goalkeeper uniform",
      light="sunny day | floodlights | rain | sunset", mood="serious happy", surf="floor:grass",
      detail="soccer ball | goal net | cleats | mud | corner flag | crowd",
      acts=dict(solo="kicking ball | celebrating goal | juggling ball", pair="tackling | passing ball | high five", groups="team huddle | celebrating, team"),
      zones=[
          Z("Goal", "soccer goal | goal net | penalty area", "net | goalkeeper | ball", solo="shooting | diving save", pair="penalty kick", groups="goal celebration"),
          Z("Midfield", "soccer field, midfield | pitch, center circle | stadium pitch", "center circle | lines | crowd", solo="dribbling | sprinting", pair="tackle",
            groups="match, players"),
          Z("Sideline", "sideline, bench | soccer bench | dugout", "bench | water | coach", solo="waiting, bench | stretching", pair="sitting, bench, together", groups="team, dugout"),
      ]),
    P("Yoga studio", f="yoga outfit | sports bra, leggings | tank top, yoga pants | crop top, leggings", m="yoga outfit | tank top, shorts | t-shirt, joggers | shirtless, yoga pants",
      light="soft morning light | warm light | sunset, window | candles", mood="calm", surf="floor:yoga mat|wall:mirror wall",
      detail="yoga mats | blocks | plants | incense | singing bowl | wooden floor",
      acts=dict(solo="yoga pose | meditating | stretching", pair="partner yoga | assisting pose | meditating together", groups="yoga class | meditation circle"),
      zones=[
          Z("Studio floor", "yoga studio | studio floor, mats | yoga room", "mats | mirrors | plants", solo="downward dog | warrior pose", pair="partner yoga",
            groups="class, rows"),
          Z("Window", "yoga studio, window | sunrise yoga | window, studio", "sunlight | city view | plants", solo="sitting, lotus position | sun salutation",
            pair="meditating, window", groups="sunrise class"),
          Z("Rooftop", "rooftop yoga | rooftop, mats | terrace yoga", "skyline | mats | sky", solo="tree pose | stretching, rooftop", pair="partner stretch",
            groups="rooftop class"),
      ]),
], "sports photography | dynamic illustration | anime illustration, sports | comic style, action", NSFW, "full body | dynamic angle | cowboy shot | from below")
