from lib import P, Z, theme

NSFW = "photorealistic, detailed skin | hentai, anime coloring | painterly, erotic illustration | boudoir photography"

theme("bedroom", "Bedroom", [
    P("Morning bed", f="oversized shirt | camisole, panties | pajamas | t-shirt, shorts", m="t-shirt, boxers | pajamas | shirtless, sweatpants | tank top",
      light="morning sunlight | soft window light | sunbeam, sheets | overcast morning", mood="calm happy", surf="bed:bed|floor:rug|wall:headboard",
      detail="white sheets | messy hair | coffee mugs | alarm clock | sunlight stripes | pillows",
      acts=dict(solo="waking up | stretching, bed | lying on stomach, phone", pair="cuddling, bed | breakfast in bed | lazy morning, together", groups="pile on bed | breakfast, bed"),
      nsfw={"suggestive": {"pair": "morning kiss | spooning, sheets"}, "nude": {"people": "tangled sheets | sheets, nude"}},
      zones=[
          Z("Sheets", "bed, white sheets | bedroom, morning | rumpled bed", "rumpled sheets | pillows | duvet", solo="hugging pillow | lying, sheets", pair="under sheets, together",
            groups="under sheets, group"),
          Z("Window side", "bedroom window, morning | bed, window | sunlit bedroom", "curtains | sunbeam | dust", solo="opening curtains | sitting, bed edge", pair="sunlight, cuddling",
            groups="sunlight, group"),
          Z("Breakfast tray", "breakfast in bed | tray, bed | bed, coffee", "tray | croissant | orange juice", solo="eating, bed | coffee, bed", pair="feeding another, bed",
            groups="breakfast, bed, group"),
      ]),
    P("Boudoir", f="lace lingerie | silk robe | corset | sheer nightgown", m="silk robe | open shirt | suit, loose necktie | boxer briefs",
      light="candlelight | dim warm light | red light | lamp light", mood="sultry calm", surf="bed:canopy bed|chair:chaise|wall:velvet wall|floor:fur rug",
      detail="velvet | candles | perfume | silk sheets | mirror | roses",
      acts=dict(solo="lounging, chaise | looking at viewer | applying perfume", pair="slow dance | whispering, close | pouring wine", groups="lounging, velvet"),
      zones=[
          Z("Canopy bed", "canopy bed | four-poster bed, silk | boudoir bed", "silk sheets | curtains | pillows", solo="lying, silk sheets | sitting, bed", pair="lying together, silk",
            groups="lounging, bed"),
          Z("Chaise", "chaise lounge | velvet chaise, boudoir | fainting couch", "velvet | fur throw | candles", solo="reclining, chaise | legs crossed, chaise", pair="sitting close, chaise",
            groups="lounging, chaise"),
          Z("Vanity", "boudoir vanity | vanity mirror, bulbs | dressing table", "perfume | jewelry | lipstick", solo="lipstick, mirror | earrings", pair="fastening necklace, another",
            groups="getting ready"),
      ]),
    P("Dorm room", f="hoodie, shorts | t-shirt, sweatpants | pajamas | crop top, leggings", m="hoodie | t-shirt, sweatpants | pajamas | tank top",
      light="desk lamp | fairy lights | monitor glow | morning light", mood="playful happy", surf="bed:bunk bed|chair:desk chair|floor:floor|table:desk",
      detail="posters | instant noodles | laptop | fairy lights | textbooks | game controller",
      acts=dict(solo="gaming | studying, bed | lying, phone", pair="gaming together | movie, laptop | studying together", groups="game night | pizza night"),
      zones=[
          Z("Bunk", "dorm bunk bed | dorm room, bunk | small dorm room", "bunk ladder | blankets | posters", solo="lying, bunk | reading, bunk", pair="bunk, together", groups="crowded bunk"),
          Z("Desk", "dorm desk | desk, laptop | study desk", "laptop | energy drinks | notes", solo="typing, laptop | studying", pair="laptop, together", groups="crowd, laptop"),
          Z("Floor", "dorm floor, beanbags | floor, pillows | dorm, rug", "beanbags | snacks | controller", solo="gaming, floor | sitting, beanbag", pair="gaming, floor", groups="party, floor"),
      ]),
    P("Loft", f="slip dress | oversized shirt | lingerie, robe | tank top, panties", m="shirtless, jeans | open shirt | robe | boxer briefs",
      light="city lights, window | sunset, loft | moonlight | neon outside", mood="calm sultry", surf="bed:bed|wall:brick wall|floor:wooden floor|chair:armchair",
      detail="exposed brick | big windows | city view | record player | plants | wine",
      acts=dict(solo="looking at city | record player | lying on bed", pair="slow dance, loft | wine, window | cuddling, bed", groups="loft party"),
      zones=[
          Z("Bed", "loft bed, window | loft bedroom | platform bed", "sheets | city lights | pillows", solo="lying, city view | sitting, bed", pair="bed, together", groups="bed, group"),
          Z("Window", "loft window, city | big window, night | window, skyline", "skyline | rain | reflection", solo="leaning, window | silhouette, window", pair="window, together",
            groups="window, group"),
          Z("Armchair", "armchair, loft | reading chair, brick | loft corner", "lamp | books | blanket", solo="reading, armchair | curled up, armchair", pair="sitting on lap, armchair",
            groups="lounging, loft"),
      ]),
    P("Cabin bedroom", f="flannel shirt | knit sweater | thermal shirt, panties | flannel pajamas", m="flannel shirt | thermal shirt | knit sweater | flannel pajamas",
      light="fireplace glow | snow light | candlelight | lamp light", mood="calm", surf="bed:log bed|floor:fur rug|chair:rocking chair",
      detail="snow outside | fireplace | quilts | log walls | hot cocoa | antlers",
      acts=dict(solo="under quilt | watching snow | warming, fire", pair="cuddling, quilt | hot cocoa, together | fireside", groups="fireside, group"),
      zones=[
          Z("Quilt bed", "cabin bed, quilts | log bed | cozy cabin bed", "quilts | pillows | snow window", solo="under quilt, reading | sleeping, quilt", pair="quilt, together",
            groups="quilts, group"),
          Z("Fur rug", "fur rug, fireplace | rug, fire, cabin | hearth, rug", "fire | fur | cocoa", solo="lying, fur rug | sitting, fire", pair="lying, rug, together", groups="rug, group"),
          Z("Window seat", "cabin window seat | window, snow | nook, snow", "snow | pines | blanket", solo="watching snow | hot cocoa, window", pair="window seat, together",
            groups="window, group"),
      ]),
    P("Hotel suite", f="silk robe | cocktail dress | lingerie | bathrobe", m="suit, loose necktie | bathrobe | open shirt | tuxedo, open collar",
      light="city lights | dim lamp | sunset | candlelight", mood="sultry calm", surf="bed:king bed|wall:window|chair:armchair|table:desk",
      detail="champagne | rose petals | city view | room service | robes | do not disturb sign",
      acts=dict(solo="champagne, window | lying on bed | robe, looking outside", pair="champagne, toast | slow dance | falling onto bed", groups="suite party"),
      zones=[
          Z("King bed", "hotel king bed | luxury bed, suite | hotel bedroom", "rose petals | pillows | sheets", solo="lying, bed | sitting, bed edge", pair="bed, together", groups="bed, group"),
          Z("Window", "floor-to-ceiling window | suite window, skyline | penthouse window", "skyline | reflection | curtains", solo="looking out | silhouette", pair="window, embrace",
            groups="window, group"),
          Z("Sitting area", "suite sitting area | sofa, suite | lounge, hotel", "sofa | champagne bucket | flowers", solo="lounging, sofa | champagne", pair="sofa, together",
            groups="lounging, suite"),
      ]),
    P("Attic bedroom", f="slip dress | oversized sweater | camisole, shorts | nightgown", m="t-shirt | sweater | pajamas | tank top",
      light="skylight | fairy lights | rain light | candlelight", mood="calm", surf="bed:mattress|floor:wooden floor|wall:slanted ceiling",
      detail="slanted ceiling | skylight, rain | fairy lights | books | plants | blankets",
      acts=dict(solo="lying, skylight | reading, fairy lights | listening, rain", pair="stargazing, skylight | cuddling, rain | reading together", groups="sleepover"),
      zones=[
          Z("Mattress", "attic mattress | floor bed, attic | cozy attic bed", "blankets | pillows | lights", solo="lying, mattress | curled up", pair="mattress, together", groups="mattress, group"),
          Z("Skylight", "attic skylight | skylight, stars | roof window", "stars | rain | moon", solo="looking up, skylight | stargazing", pair="stargazing, together",
            groups="stargazing, group"),
          Z("Reading nook", "attic nook | reading corner, attic | nook, cushions", "cushions | books | candle", solo="reading, nook | writing, diary", pair="reading, nook, together",
            groups="nook, group"),
      ]),
    P("Moroccan room", f="kaftan | silk robe | belly dancer outfit | harem pants, crop top", m="kaftan | linen robe | harem pants | open shirt",
      light="lantern light | candlelight | warm light | sunset", mood="calm sultry", surf="bed:daybed|floor:cushions|wall:tiled wall",
      detail="lanterns | cushions | mint tea | mosaic tiles | incense | silk curtains",
      acts=dict(solo="lounging, cushions | pouring tea | dancing", pair="mint tea, together | lounging together | feeding dates", groups="lounging, cushions, group"),
      zones=[
          Z("Daybed", "moroccan daybed | canopy daybed | riad bedroom", "silk curtains | cushions | lanterns", solo="reclining, daybed | lying, cushions", pair="daybed, together",
            groups="daybed, group"),
          Z("Courtyard", "riad courtyard | fountain, mosaic | courtyard, plants", "fountain | orange trees | tiles", solo="sitting, fountain | trailing hand, water", pair="fountain, together",
            groups="courtyard, group"),
          Z("Lantern room", "lantern room | cushions, lanterns | tea room", "lanterns | incense | rugs", solo="dancing, lanterns | sitting, cushions", pair="tea, lanterns",
            groups="tea, group"),
      ]),
    P("Rainy night bedroom", f="oversized hoodie | camisole, shorts | sweater, panties | slip dress", m="hoodie | t-shirt, boxers | sweatpants | open shirt",
      light="rain, window | lamp light | lightning | neon outside", mood="calm melancholy", surf="bed:bed|wall:window|floor:rug",
      detail="rain on window | lamp | blankets | tea | headphones | city lights",
      acts=dict(solo="listening to rain | lying, headphones | writing, bed", pair="cuddling, rain | sharing headphones | whispering, dark", groups="sleepover, rain"),
      zones=[
          Z("Bed", "bed, rain window | bedroom, rain | bed, night", "rain | blanket | pillows", solo="under blanket | lying, rain", pair="under blanket, together", groups="blanket fort"),
          Z("Window", "window, rain, night | window, city rain | rainy window", "raindrops | reflection | neon", solo="drawing, fogged glass | looking outside", pair="window, together",
            groups="window, group"),
          Z("Rug", "bedroom floor, rug | rug, candles | floor, pillows", "candles | tea | records", solo="lying, rug | records", pair="rug, together", groups="rug, group"),
      ]),
], "photorealistic, intimate | anime illustration, soft | film photography, bedroom | painterly, warm", NSFW, "cowboy shot | full body | from above | upper body")

theme("gym", "Gym", [
    P("Weight room", f="sports bra, leggings | tank top, shorts | crop top, gym shorts | bodysuit", m="tank top, shorts | stringer tank | shirtless, gym shorts | t-shirt, joggers",
      light="gym lights | morning light, windows | harsh light | evening light", mood="serious playful", surf="floor:gym floor|wall:mirror|chair:bench",
      detail="dumbbells | barbell | chalk | sweat | mirrors | water bottle",
      acts=dict(solo="lifting dumbbells | squatting, barbell | flexing, mirror", pair="spotting | flexing together | high five", groups="workout, group | competition"),
      nsfw={"suggestive": {"pair": "spotting, close | sweaty, close"}},
      zones=[
          Z("Free weights", "free weights area | dumbbell rack | gym, mirrors", "dumbbells | rack | mirror", solo="curling dumbbell | lunging", pair="spotting, dumbbells", groups="crowd, weights"),
          Z("Bench press", "bench press | weight bench | barbell bench", "barbell | plates | bench", solo="bench press | resting, bench", pair="spotting, bench", groups="bench, crowd"),
          Z("Squat rack", "squat rack | power rack | lifting platform", "rack | chalk | plates", solo="squatting | deadlift", pair="spotting, squat", groups="lifting, group"),
      ]),
    P("Yoga loft", f="yoga outfit | sports bra, leggings | crop top, yoga pants | bodysuit", m="yoga pants, shirtless | tank top, shorts | t-shirt, joggers | yoga outfit",
      light="soft morning light | sunset | warm light | candles", mood="calm", surf="floor:yoga mat|wall:wall",
      detail="mats | plants | candles | blocks | straps | incense",
      acts=dict(solo="stretching | yoga pose | meditating", pair="partner stretch | assisting pose | partner yoga", groups="yoga class | stretching, group"),
      zones=[
          Z("Mats", "yoga loft, mats | studio floor | yoga room", "mats | blocks | towels", solo="downward dog | splits", pair="partner yoga", groups="class"),
          Z("Window", "yoga loft window | window, city | window, sunrise", "sunlight | plants | city", solo="sun salutation | warrior pose", pair="stretching, window", groups="window class"),
          Z("Aerial", "aerial yoga | silk hammocks | aerial studio", "silks | hammocks | rigging", solo="hanging, silks | inverted, silks", pair="aerial, together", groups="aerial class"),
      ]),
    P("Boxing club", f="sports bra, boxing shorts | tank top, hand wraps | crop top, gloves | hoodie, shorts", m="boxing shorts | shirtless, gloves | tank top, hand wraps | hoodie",
      light="harsh light | dim light | spotlight | window light", mood="serious tense", surf="floor:ring|wall:ropes|chair:stool",
      detail="punching bags | gloves | sweat | ropes | tape | bucket",
      acts=dict(solo="punching bag | jump rope | shadow boxing", pair="sparring | pad work | wrapping hands, another", groups="training | crowd, ring"),
      zones=[
          Z("Ring", "boxing ring | ring, ropes | sparring ring", "ropes | canvas | corner", solo="fighting stance | ducking", pair="sparring", groups="ringside"),
          Z("Bags", "punching bags | bag area | heavy bags", "bags | chains | gloves", solo="hitting bag | uppercut", pair="holding bag", groups="bag drills"),
          Z("Corner", "ring corner | corner stool | corner, towel", "stool | towel | water", solo="resting, corner | towel, sweat", pair="corner talk", groups="corner team"),
      ]),
    P("Locker room", f="towel | sports bra | sportswear | robe", m="towel | shorts | sportswear | robe",
      light="fluorescent light | steam | dim light | bright light", mood="calm playful", surf="chair:bench|wall:lockers|floor:tiled floor",
      detail="lockers | gym bags | towels | steam | deodorant | sneakers",
      acts=dict(solo="changing | towel, hair | tying shoes", pair="changing together | towel snap | talking, bench", groups="team, lockers"),
      zones=[
          Z("Lockers", "locker room | lockers, bench | gym lockers", "lockers | bags | benches", solo="opening locker | sitting, bench", pair="changing, side by side", groups="locker room, team"),
          Z("Showers", "gym showers | shower room | communal showers", "steam | tiles | soap", solo="showering | rinsing", pair="showering, side by side", groups="team showers"),
          Z("Sauna", "gym sauna | sauna, wood | steam sauna", "steam | stones | towels", solo="sauna, sweating | resting, sauna", pair="sauna, together", groups="sauna, group"),
      ]),
    P("Pool gym", f="swimsuit | bikini | swim cap | towel", m="swim briefs | swim trunks | swim cap | towel",
      light="pool lights | sunlight | underwater light | night", mood="calm playful", surf="water:pool|floor:pool deck|chair:lounger",
      detail="lane ropes | splash | goggles | kickboard | towels | caustics",
      acts=dict(solo="swimming laps | floating | climbing out", pair="racing | splashing | floating together", groups="aqua aerobics | swim practice"),
      zones=[
          Z("Lanes", "lap pool | lanes, pool | swimming lanes", "ropes | splash | clock", solo="freestyle | backstroke", pair="racing", groups="swim practice"),
          Z("Jacuzzi", "gym jacuzzi | hot tub | whirlpool", "bubbles | steam | jets", solo="relaxing, jacuzzi | jets", pair="jacuzzi, together", groups="jacuzzi, group"),
          Z("Deck", "pool deck | poolside, towels | edge of pool", "towels | puddles | loungers", solo="drying off | sitting, edge", pair="sitting, edge, together", groups="deck, group"),
      ]),
    P("Crossfit box", f="sports bra, shorts | crop top, leggings | tank top, shorts | knee sleeves", m="shirtless, shorts | tank top | t-shirt, shorts | knee sleeves",
      light="industrial lights | daylight, garage door | harsh light | evening", mood="serious playful", surf="floor:rubber floor|wall:rig",
      detail="kettlebells | rings | ropes | tires | chalk | whiteboard",
      acts=dict(solo="kettlebell swing | rope climb | burpees", pair="tire flip, together | high five | partner workout", groups="wod | cheering"),
      zones=[
          Z("Rig", "crossfit rig | pull-up bars | rings, rig", "pull-up bar | rings | chalk", solo="pull-ups | muscle-up", pair="spotting, rig", groups="rig, group"),
          Z("Ropes", "battle ropes | climbing rope | rope station", "ropes | mats | sweat", solo="battle ropes | rope climb", pair="ropes, together", groups="ropes, group"),
          Z("Tires", "tire flip area | tires, turf | turf, sled", "tires | sled | turf", solo="tire flip | sled push", pair="tire flip, together", groups="relay"),
      ]),
    P("Dance studio", f="leotard, tights | crop top, leggings | dance skirt | sports bra, shorts", m="tank top, sweatpants | t-shirt, joggers | shirtless, dance pants | tights",
      light="studio lights | window light | sunset | dim light", mood="playful calm", surf="floor:wooden floor|wall:mirror|chair:barre",
      detail="mirrors | barre | speaker | water bottles | wooden floor | leg warmers",
      acts=dict(solo="dancing, mirror | stretching, barre | spinning", pair="partner dance | lift | stretching together", groups="dance class | rehearsal"),
      zones=[
          Z("Mirror wall", "dance studio, mirrors | mirror wall | studio floor", "mirrors | reflection | floor", solo="dancing, reflection | posing, mirror", pair="dancing, mirror",
            groups="class, mirror"),
          Z("Barre", "ballet barre | barre, window | studio barre", "barre | pointe shoes | window", solo="leg on barre | plie", pair="stretching, barre", groups="barre, row"),
          Z("Pole", "pole dance studio | dance poles | pole studio", "poles | heels | mirrors", solo="pole dancing | spinning, pole", pair="pole, together", groups="pole class"),
      ]),
    P("Home gym", f="sports bra, leggings | tank top, shorts | crop top | t-shirt", m="tank top | shirtless | t-shirt, shorts | hoodie",
      light="garage light | morning light | evening lamp | window light", mood="serious playful", surf="floor:mat|chair:bench|wall:mirror",
      detail="dumbbells | yoga mat | towel | bike | music | protein shaker",
      acts=dict(solo="push-ups | sit-ups | stationary bike", pair="workout together | holding feet, sit-ups | high five", groups="workout, group"),
      zones=[
          Z("Garage", "garage gym | garage, weights | home gym, garage", "weights | rack | tools", solo="lifting, garage | push-ups", pair="spotting, garage", groups="garage, group"),
          Z("Living room", "living room workout | home workout, rug | yoga, living room", "mat | tv | sofa", solo="yoga, mat | stretching", pair="workout, together", groups="living room, group"),
          Z("Balcony", "balcony workout | balcony, mat | terrace workout", "plants | sun | mat", solo="stretching, sun | jump rope", pair="stretching together", groups="balcony, group"),
      ]),
    P("Track and field", f="track uniform | sports bra, shorts | crop top, shorts | tracksuit", m="track uniform | tank top, shorts | tracksuit | shirtless, shorts",
      light="sunny day | stadium lights | sunset | morning", mood="serious happy", surf="floor:track|chair:bleachers",
      detail="track lanes | hurdles | stopwatch | starting blocks | javelin | stadium",
      acts=dict(solo="sprinting | hurdling | stretching, track", pair="racing | stretching together | relay baton", groups="relay | team"),
      zones=[
          Z("Track", "running track | stadium track | lanes", "lanes | blocks | hurdles", solo="sprinting, lane | starting blocks", pair="racing, lanes", groups="race"),
          Z("Field", "field events | javelin field | long jump pit", "sand pit | javelin | mats", solo="long jump | javelin throw", pair="watching jump", groups="field team"),
          Z("Bleachers", "stadium bleachers | stands | grandstand", "seats | towels | bags", solo="sitting, bleachers | drinking water", pair="bleachers, together", groups="team, stands"),
      ]),
], "fitness photography | anime illustration, sporty | photorealistic, sweat | comic style", NSFW, "full body | cowboy shot | from below | from side")

theme("hotel", "Hotel", [
    P("Grand lobby", f="evening gown | cocktail dress | business suit | trench coat", m="tuxedo | suit | overcoat | bellhop uniform",
      light="chandelier | warm light | marble reflections | evening lamps", mood="calm cool", surf="chair:velvet sofa|wall:marble column|floor:marble floor",
      detail="chandeliers | luggage cart | front desk | flowers | brass | revolving door",
      acts=dict(solo="checking in | waiting, luggage | sitting, lobby", pair="meeting, lobby | secret glance | arm in arm", groups="tour group | crowd, lobby"),
      zones=[
          Z("Front desk", "hotel front desk | reception, marble | lobby desk", "bell | keys | concierge", solo="ringing bell | holding key", pair="checking in together", groups="queue, desk"),
          Z("Lounge", "hotel lounge | lobby lounge, sofas | piano lounge", "piano | sofas | cocktails", solo="sitting, sofa | listening, piano", pair="drinks, lounge", groups="lounge, group"),
          Z("Elevator", "hotel elevator | brass elevator | elevator hall", "brass doors | floor dial | mirror", solo="waiting, elevator | leaning, elevator", pair="elevator, close",
            groups="crowded elevator"),
      ]),
    P("Hotel room", f="robe | lingerie | slip dress | business suit", m="robe | suit, loose necktie | boxer briefs | open shirt",
      light="lamp light | city lights | morning light | tv glow", mood="calm sultry", surf="bed:hotel bed|wall:window|chair:armchair|table:desk",
      detail="room key | suitcase | room service | city view | minibar | do not disturb sign",
      acts=dict(solo="unpacking | lying on bed | looking out window", pair="room service | collapsing on bed | drinks, minibar", groups="hotel party"),
      zones=[
          Z("Bed", "hotel bed | hotel room, bed | double bed, hotel", "sheets | pillows | remote", solo="lying, bed | bouncing, bed", pair="bed, together", groups="bed, group"),
          Z("Desk", "hotel desk | desk, window | writing desk, hotel", "laptop | stationery | lamp", solo="working, desk | writing letter", pair="desk, together", groups="meeting, room"),
          Z("Window", "hotel window | window, city | curtains, skyline", "skyline | curtains | rain", solo="looking out | silhouette", pair="window, together", groups="window, group"),
      ]),
    P("Pool terrace", f="bikini | swimsuit | sundress | sarong", m="swim trunks | linen shirt | shorts | robe",
      light="sunny day | sunset | pool lights | golden hour", mood="calm happy", surf="water:pool|chair:lounger|floor:pool deck",
      detail="loungers | cocktails | towels | palms | umbrellas | sunglasses",
      acts=dict(solo="sunbathing | swimming | cocktail, lounger", pair="sunbathing together | drinks, pool | swimming together", groups="pool party"),
      zones=[
          Z("Pool", "hotel pool | infinity pool | rooftop pool, hotel", "water | floats | edge", solo="floating | swimming", pair="swimming, together", groups="pool, group"),
          Z("Loungers", "pool loungers | sun deck | cabanas", "loungers | umbrellas | towels", solo="sunbathing | reading", pair="loungers, together", groups="loungers, group"),
          Z("Bar", "pool bar | swim-up bar | tiki bar, hotel", "cocktails | bartender | stools", solo="drinking cocktail", pair="cocktails, together", groups="bar, group"),
      ]),
    P("Penthouse", f="evening gown | silk robe | cocktail dress | lingerie", m="tuxedo | silk robe | suit | open shirt",
      light="city lights | sunset | candlelight | moonlight", mood="cool sultry", surf="bed:king bed|wall:window|chair:sofa|water:hot tub",
      detail="skyline | champagne | grand piano | art | marble | private pool",
      acts=dict(solo="champagne, skyline | piano | lounging, sofa", pair="champagne toast | dancing, penthouse | hot tub, together", groups="penthouse party"),
      zones=[
          Z("Living room", "penthouse living room | penthouse, piano | luxury lounge", "piano | art | sofas", solo="playing piano | lounging", pair="piano, together", groups="party"),
          Z("Terrace", "penthouse terrace | terrace, hot tub | rooftop, penthouse", "hot tub | skyline | wind", solo="hot tub | leaning, railing", pair="hot tub, together", groups="terrace party"),
          Z("Bedroom", "penthouse bedroom | master bedroom | bedroom, skyline", "king bed | skyline | silk", solo="lying, silk | robe, window", pair="bed, skyline", groups="bed, group"),
      ]),
    P("Motel", f="denim shorts, tank top | slip dress | leather jacket | oversized shirt", m="leather jacket | t-shirt, jeans | flannel shirt | tank top",
      light="neon sign | flickering lamp | headlights | dusk", mood="tense playful", surf="bed:motel bed|wall:motel door|chair:chair|water:pool",
      detail="neon sign | ice bucket | vending machine | tv static | room key | empty pool",
      acts=dict(solo="sitting on bed, smoking | ice bucket | lying, motel bed", pair="arguing | counting cash | collapsing on bed", groups="road trip crew"),
      zones=[
          Z("Room", "motel room | cheap motel | motel bed, neon", "tv | lamp | carpet", solo="lying, bed | watching tv", pair="bed, together", groups="crowded room"),
          Z("Pool", "motel pool | empty pool, motel | pool, neon", "neon | lounge chairs | ice machine", solo="sitting, pool edge | dipping feet", pair="pool, night", groups="pool, group"),
          Z("Parking lot", "motel parking lot | lot, neon | car, motel", "car | neon | vending machine", solo="leaning, car", pair="car, together", groups="lot, group"),
      ]),
    P("Ryokan", f="yukata | kimono | haori | towel", m="yukata | kimono | haori | towel",
      light="lantern light | morning light | paper screen light | snow light", mood="calm", surf="bed:futon|floor:tatami|water:hot spring|wall:shoji",
      detail="tatami | futon | tea set | garden view | paper lanterns | yukata belts",
      acts=dict(solo="tea | sitting, tatami | looking at garden", pair="tea, together | dinner, kaiseki | soaking together", groups="dinner, group"),
      zones=[
          Z("Futon room", "ryokan room, futon | tatami room, futon | inn room", "futon | pillows | lamp", solo="lying, futon | sitting, futon", pair="futon, together", groups="futons, row"),
          Z("Engawa", "engawa | veranda, garden | wooden porch, ryokan", "garden | rain | wind chime", solo="sitting, veranda | tea, veranda", pair="veranda, together", groups="veranda, group"),
          Z("Private bath", "ryokan private bath | wooden bath | rotenburo, private", "wooden tub | steam | stones", solo="soaking | towel, head", pair="soaking together", groups="soaking, group"),
      ]),
    P("Overwater villa", f="bikini | sarong | sundress | robe", m="swim trunks | linen shirt | shorts | robe",
      light="tropical sun | sunset | moonlight, water | golden hour", mood="calm happy", surf="bed:bed|water:lagoon|floor:deck|chair:hammock",
      detail="turquoise water | glass floor | hammock | fish | palm | wooden deck",
      acts=dict(solo="lying, hammock | jumping into lagoon | looking through glass floor", pair="breakfast, deck | swimming together | sunset, deck", groups="snorkeling"),
      zones=[
          Z("Deck", "overwater deck | villa deck, lagoon | wooden deck, sea", "ladder | water | towels", solo="sitting, deck | diving", pair="deck, together", groups="deck, group"),
          Z("Bedroom", "villa bedroom, ocean view | bed, glass floor | bungalow bed", "glass floor | net curtains | breeze", solo="lying, bed | waking, ocean", pair="bed, ocean, together",
            groups="bungalow, group"),
          Z("Lagoon", "lagoon | turquoise water | shallow sea", "fish | coral | rays", solo="swimming | floating", pair="snorkeling together", groups="lagoon, group"),
      ]),
    P("Hotel bar", f="cocktail dress | little black dress | blazer, silk top | sequin dress", m="suit | tuxedo | blazer | vest, rolled sleeves",
      light="dim warm light | candlelight | neon bar light | city lights", mood="cool sultry", surf="table:bar counter|chair:bar stool|wall:wall",
      detail="cocktails | whiskey | bartender | jazz trio | candles | velvet booths",
      acts=dict(solo="drinking martini | sitting, bar stool | looking over shoulder", pair="flirting, bar | toast | sharing booth", groups="drinks, booth"),
      zones=[
          Z("Bar counter", "hotel bar | bar counter, bottles | cocktail bar", "bottles | stools | bartender", solo="ordering, bar | leaning, counter", pair="bar, together", groups="bar, crowd"),
          Z("Booth", "velvet booth | bar booth | corner booth, hotel", "velvet | candles | drinks", solo="sitting, booth", pair="booth, close", groups="booth, group"),
          Z("Jazz corner", "jazz corner | bar, piano | lounge stage", "piano | saxophone | singer", solo="singing, microphone | listening, jazz", pair="slow dance, jazz", groups="audience, jazz"),
      ]),
    P("Honeymoon suite", f="wedding lingerie | silk robe | white dress | negligee", m="open shirt | robe | tuxedo, open collar | boxer briefs",
      light="candlelight | rose light | soft light | sunset", mood="sultry happy", surf="bed:heart bed|water:jacuzzi|wall:wall|floor:floor",
      detail="rose petals | champagne | candles | heart pillows | strawberries | just married sign",
      acts=dict(solo="lying, petals | champagne | robe, smiling", pair="carrying, princess carry | champagne toast | feeding strawberries", groups="toast"),
      zones=[
          Z("Bed", "honeymoon bed, petals | suite bed | heart-shaped bed", "petals | pillows | towel swans", solo="lying, petals | sitting, bed", pair="bed, petals, together", groups="bed, group"),
          Z("Jacuzzi", "suite jacuzzi | jacuzzi, candles | spa tub", "bubbles | candles | champagne", solo="jacuzzi | bubbles", pair="jacuzzi, together", groups="jacuzzi, group"),
          Z("Balcony", "suite balcony | balcony, sea | balcony, sunset", "sea | sunset | railing", solo="leaning, balcony", pair="embrace, balcony", groups="balcony, group"),
      ]),
], "photorealistic, luxury | cinematic, hotel | anime illustration, elegant | film photography", NSFW, "cowboy shot | full body | wide shot | from side")
