from lib import P, Z, theme

NSFW = "photorealistic, detailed skin | hentai, anime coloring | painterly, erotic illustration | glamour photography"
NSFW_ONLY = ("suggestive", "nude", "explicit")

theme("office", "Office", [
    P("Open office", f="blouse, pencil skirt | business suit | cardigan, slacks | blazer, turtleneck", m="shirt, necktie | business suit | sweater, chinos | rolled sleeves, vest",
      light="fluorescent light | window light | monitor glow | late night, desk lamp", mood="serious calm", surf="table:desk|chair:office chair|wall:glass wall",
      detail="monitors | coffee cups | sticky notes | keyboards | plants | printer",
      acts=dict(solo="typing | phone call | stretching, chair", pair="discussing, monitor | coffee break | high five", groups="team meeting | celebrating"),
      nsfw={"suggestive": {"pair": "loosened necktie | sitting on desk, close"}, "explicit": {"pair": "office sex, desk"}},
      zones=[
          Z("Desks", "open office, desks | cubicles | office floor", "desks | monitors | chairs", solo="typing, desk | leaning back, chair", pair="desk, together", groups="desks, team"),
          Z("Break room", "office break room | kitchenette, office | coffee corner", "coffee machine | fridge | microwave", solo="making coffee | eating lunch", pair="coffee, together",
            groups="lunch, team"),
          Z("Copy room", "copy room | printer room | supply closet", "copier | paper stacks | boxes", solo="copying | carrying paper", pair="copy room, close", groups="copy room, crowd"),
      ]),
    P("Executive office", f="power suit | pencil dress | silk blouse, skirt | blazer dress", m="three-piece suit | suit | shirt, suspenders | turtleneck, blazer",
      light="window light, skyline | desk lamp | sunset | night, city lights", mood="serious cool", surf="table:executive desk|chair:leather chair|wall:window|floor:carpet",
      detail="skyline | leather chair | whiskey decanter | awards | bookshelf | mahogany desk",
      acts=dict(solo="sitting, leather chair | looking at skyline | signing documents", pair="negotiation | whiskey, toast | standing, window", groups="board meeting"),
      nsfw={"suggestive": {"pair": "sitting on desk | necktie pull"}},
      zones=[
          Z("Desk", "executive desk | ceo office | corner office, desk", "mahogany desk | nameplate | papers", solo="feet on desk | phone, desk", pair="across desk", groups="desk, meeting"),
          Z("Window", "office window, skyline | glass wall, city | floor-to-ceiling window", "skyline | reflection | rain", solo="hands behind back, window", pair="window, together",
            groups="window, team"),
          Z("Bar cart", "office bar cart | whiskey cart | office lounge", "decanter | glasses | ice", solo="pouring whiskey", pair="whiskey, together", groups="toast, office"),
      ]),
    P("Meeting room", f="blazer, blouse | business suit | dress, cardigan | shirt, slacks", m="business suit | shirt, necktie | blazer, jeans | sweater",
      light="fluorescent light | projector light | window light | dim light", mood="serious tense", surf="table:conference table|chair:chair|wall:whiteboard",
      detail="whiteboard | projector | laptops | coffee | charts | water glasses",
      acts=dict(solo="presenting | taking notes | thinking, pen", pair="arguing | shaking hands | whispering, meeting", groups="meeting | brainstorming"),
      zones=[
          Z("Table", "conference table | boardroom | meeting table", "table | chairs | laptops", solo="sitting, head of table", pair="across table", groups="meeting"),
          Z("Whiteboard", "whiteboard, meeting room | presentation wall | screen, meeting", "whiteboard | markers | charts", solo="writing, whiteboard | pointing, chart", pair="whiteboard, together",
            groups="brainstorm"),
          Z("Glass wall", "glass meeting room | fishbowl room | glass walls, office", "glass | blinds | office", solo="leaning, glass | closing blinds", pair="glass, close", groups="glass room, team"),
      ]),
    P("Late night office", f="blouse, loosened | business suit | cardigan | shirt, skirt", m="shirt, loosened necktie | suit, no jacket | rolled sleeves | sweater",
      light="desk lamp | monitor glow | city lights | night", mood="calm melancholy", surf="table:desk|chair:office chair|floor:carpet|wall:window",
      detail="takeout boxes | city lights | empty office | coffee cups | desk lamp | screensaver",
      acts=dict(solo="working late | sleeping, desk | stretching", pair="working late together | takeout, desk | talking, dark office", groups="overtime, team"),
      nsfw={"suggestive": {"pair": "loosened necktie | close, desk"}},
      zones=[
          Z("Desk", "desk, night | office, desk lamp | empty office, desk", "lamp | monitor | papers", solo="typing, night", pair="desk, together", groups="team, night"),
          Z("Window", "office window, night | city lights, office | window, rain", "city | rain | reflection", solo="looking at city", pair="window, night", groups="window, team"),
          Z("Lounge", "office lounge, night | sofa, office | break area, night", "sofa | vending machine | tv", solo="napping, sofa", pair="sofa, together", groups="lounge, team"),
      ]),
    P("Library office", f="cardigan, glasses | blouse, long skirt | sweater, slacks | blazer", m="cardigan, glasses | tweed jacket | shirt, vest | sweater",
      light="lamp light | window light | dusty light | afternoon sun", mood="calm", surf="table:desk|chair:chair|wall:bookshelf",
      detail="books | archives | filing cabinets | lamps | ledgers | ladder",
      acts=dict(solo="reading files | stamping | sorting books", pair="research together | whispering, shelves | reaching, shelf", groups="study group"),
      zones=[
          Z("Archive", "archive room | records room | filing room", "files | boxes | cabinets", solo="searching files", pair="searching together", groups="archive, team"),
          Z("Reading room", "reading room | library desk | study hall", "lamps | tables | books", solo="reading, lamp", pair="reading together", groups="reading room, group"),
          Z("Stacks", "library stacks | shelves, aisle | book aisle", "shelves | ladder | carts", solo="climbing ladder", pair="aisle, close", groups="aisle, group"),
      ]),
    P("Startup loft", f="hoodie, jeans | t-shirt, skirt | flannel | cardigan, leggings", m="hoodie | t-shirt, jeans | flannel | quarter zip",
      light="industrial light | window light | neon sign | evening", mood="happy playful", surf="chair:beanbag|table:standing desk|wall:brick wall",
      detail="beanbags | ping pong table | laptops | whiteboard | neon sign | snacks",
      acts=dict(solo="coding | ping pong | lying, beanbag", pair="pair programming | ping pong match | brainstorm", groups="standup meeting | launch party"),
      zones=[
          Z("Desks", "startup desks | open loft | hot desks", "laptops | monitors | stickers", solo="coding, laptop", pair="pair programming", groups="team, desks"),
          Z("Game area", "ping pong, loft | game room, office | arcade, office", "ping pong | arcade | beanbags", solo="arcade", pair="ping pong", groups="tournament"),
          Z("Rooftop", "office rooftop | loft rooftop | roof deck, office", "deck | city | beer", solo="laptop, rooftop", pair="beer, rooftop", groups="rooftop party"),
      ]),
    P("Reception", f="receptionist uniform | blouse, skirt | business suit | dress", m="suit | security uniform | shirt, necktie | blazer",
      light="bright lobby light | daylight | evening light | cold light", mood="calm serious", surf="table:reception desk|chair:chair|wall:wall",
      detail="logo wall | reception desk | waiting chairs | magazines | orchids | phone",
      acts=dict(solo="answering phone | greeting | waiting, chair", pair="checking in | handshake | small talk", groups="visitors"),
      zones=[
          Z("Desk", "reception desk | front desk, office | lobby desk", "phone | logo | flowers", solo="behind desk", pair="desk, visitor", groups="queue"),
          Z("Waiting area", "waiting area | lobby chairs | waiting room", "chairs | magazines | water", solo="waiting, magazine", pair="waiting, together", groups="waiting, crowd"),
          Z("Elevator lobby", "elevator lobby | office elevator | lift lobby", "elevators | buttons | mirror", solo="waiting, elevator", pair="elevator, close", groups="elevator, crowd"),
      ]),
    P("Server room", f="technician uniform | hoodie | blouse, lanyard | t-shirt, jeans", m="technician uniform | hoodie | shirt, lanyard | t-shirt",
      light="blue led light | cold light | dim light | warning light", mood="tense calm", surf="floor:raised floor|wall:server rack",
      detail="server racks | cables | blinking lights | cold air | laptop | cable ties",
      acts=dict(solo="plugging cable | typing, laptop | checking rack", pair="troubleshooting | flashlight, cables | arguing", groups="tech team"),
      zones=[
          Z("Rack aisle", "server room aisle | data center | rows of servers", "racks | lights | cables", solo="walking, aisle", pair="aisle, together", groups="team, aisle"),
          Z("Console", "server console | monitoring station | control room", "screens | keyboard | alerts", solo="typing, console", pair="console, together", groups="control room"),
          Z("Cable floor", "raised floor | cables, floor | under floor", "cables | tiles | flashlight", solo="crawling, cables", pair="pulling cable", groups="floor, team"),
      ]),
    P("Home office call", f="blouse, pajama pants | cardigan | sweater | shirt", m="shirt, pajama pants | hoodie | sweater | polo",
      light="ring light | window light | monitor glow | lamp", mood="playful calm", surf="table:desk|chair:chair|bed:bed",
      detail="webcam | ring light | headset | coffee | pet | notes",
      acts=dict(solo="video call | muted, laughing | headset, typing", pair="interrupting call | coffee, desk | working together", groups="video call grid"),
      zones=[
          Z("Desk", "home desk, webcam | video call desk | desk setup", "webcam | mic | monitor", solo="video call, smiling", pair="behind screen, another", groups="call, group"),
          Z("Bed", "working from bed | bed, laptop | laptop, pillows", "laptop | pillows | coffee", solo="laptop, bed", pair="bed, laptop, together", groups="bed, laptops"),
          Z("Kitchen table", "kitchen table, laptop | dining table, work | table, notes", "laptop | fruit | coffee", solo="laptop, table", pair="table, together", groups="table, group"),
      ]),
], "corporate photography | anime illustration, office | cinematic still | comic style", NSFW, "cowboy shot | upper body | full body | from side")

theme("outdoors", "Outdoors", [
    P("Campsite", f="flannel shirt, shorts | hiking outfit | hoodie, leggings | tank top, cargo shorts", m="flannel shirt | hiking outfit | hoodie | tank top",
      light="campfire | golden hour | starry night | morning mist", mood="happy calm", surf="floor:grass|bed:tent|water:lake",
      detail="tent | campfire | marshmallows | lantern | backpacks | stars",
      acts=dict(solo="roasting marshmallow | setting up tent | sitting, log", pair="campfire, blanket | stargazing | cooking, fire", groups="campfire songs | stories"),
      zones=[
          Z("Fire", "campfire | fire pit, camp | bonfire, woods", "fire | sparks | logs", solo="poking fire", pair="fire, together", groups="circle"),
          Z("Tent", "camping tent | tent, night | tent, sleeping bags", "sleeping bags | lantern | tent", solo="inside tent | sleeping bag", pair="tent, together", groups="tent, crowded"),
          Z("Lakeside", "lakeside camp | camp, lake | shore, camp", "lake | canoe | moon", solo="sitting, shore", pair="shore, together", groups="swimming, night"),
      ]),
    P("Hot spring wild", f="towel | swimsuit | yukata | bikini", m="towel | swim trunks | yukata | shorts",
      light="steam | snow light | moonlight | dawn", mood="calm", surf="water:hot spring|floor:rocks",
      detail="steam | snow | rocks | pines | monkeys | stars",
      acts=dict(solo="soaking | sitting, rock | watching snow", pair="soaking together | sake, spring | stargazing, spring", groups="soaking, group"),
      zones=[
          Z("Pool", "wild hot spring | natural spring, rocks | thermal pool", "steam | rocks | snow", solo="steam, eyes closed | arms on rocks", pair="soaking, together", groups="soaking, group"),
          Z("River", "hot river | thermal river | steaming stream", "steam | stones | trees", solo="wading", pair="wading, together", groups="river, group"),
          Z("Cliff", "cliff spring | hot spring, view | spring, valley view", "valley | clouds | steam", solo="looking at view", pair="view, together", groups="view, group"),
      ]),
    P("Meadow picnic", f="sundress | floral dress | t-shirt, shorts | blouse, skirt", m="linen shirt | t-shirt | polo | henley",
      light="sunny day | golden hour | dappled light | afternoon", mood="happy calm", surf="floor:picnic blanket",
      detail="picnic basket | wine | sandwiches | flowers | blanket | butterflies",
      acts=dict(solo="lying, blanket | reading, grass | picking flowers", pair="picnic | feeding another | lying together, grass", groups="picnic, group"),
      zones=[
          Z("Blanket", "picnic blanket, meadow | picnic, field | blanket, flowers", "basket | wine | fruit", solo="eating grapes | sitting, blanket", pair="picnic, together", groups="picnic, group"),
          Z("Tree shade", "under tree, meadow | oak tree, shade | tree, picnic", "shade | roots | swing", solo="sitting, tree", pair="tree, together", groups="tree, group"),
          Z("Stream", "meadow stream | creek, field | brook, flowers", "stones | water | flowers", solo="feet in water", pair="stream, together", groups="stream, group"),
      ]),
    P("Secluded beach", f="bikini | sarong | swimsuit | sundress", m="swim trunks | shirtless | linen shirt | shorts",
      light="tropical sun | sunset | moonlight | golden hour", mood="calm playful", surf="floor:sand|water:sea|wall:rocks",
      detail="palm trees | turquoise water | footprints | shells | rocks | hammock",
      acts=dict(solo="sunbathing | swimming | walking, shore", pair="swimming together | sunbathing together | chasing, waves", groups="beach, group"),
      zones=[
          Z("Cove", "secluded cove | hidden beach | cove, rocks", "rocks | water | sand", solo="lying, sand", pair="cove, together", groups="cove, group"),
          Z("Palms", "palm trees, beach | hammock, palms | beach shade", "hammock | palms | coconut", solo="hammock", pair="hammock, together", groups="shade, group"),
          Z("Water", "shallow water | lagoon, beach | sea, waves", "waves | fish | foam", solo="floating", pair="floating together", groups="swimming, group"),
      ]),
    P("Forest trail", f="hiking outfit | tank top, shorts | flannel | sports bra, leggings", m="hiking outfit | tank top | flannel | shirtless, shorts",
      light="dappled light | god rays | mist | golden hour", mood="calm happy", surf="floor:moss|wall:tree trunk|water:stream",
      detail="ferns | moss | trail | birds | mushrooms | backpacks",
      acts=dict(solo="hiking | resting, rock | drinking water", pair="hiking together | resting, tree | helping, climb", groups="hiking group"),
      zones=[
          Z("Trail", "forest trail | path, ferns | hiking trail", "trail | roots | ferns", solo="walking, trail", pair="trail, together", groups="trail, group"),
          Z("Clearing", "forest clearing | glade | sunny clearing", "flowers | grass | sun", solo="lying, clearing", pair="clearing, together", groups="clearing, group"),
          Z("Creek", "forest creek | stream, rocks | creek, moss", "water | stones | moss", solo="crossing creek", pair="creek, together", groups="creek, group"),
      ]),
    P("Rooftop garden", f="sundress | crop top, shorts | robe | tank top", m="t-shirt | linen shirt | robe | shorts",
      light="sunset | sunny day | city lights | string lights", mood="calm happy", surf="floor:wooden deck|chair:lounger|water:plunge pool",
      detail="plants | skyline | string lights | loungers | herbs | city noise",
      acts=dict(solo="sunbathing | watering plants | reading, lounger", pair="sunset, together | drinks, deck | lounging together", groups="rooftop gathering"),
      zones=[
          Z("Deck", "rooftop deck | wooden deck, city | roof terrace", "deck | plants | city", solo="lying, deck", pair="deck, together", groups="deck, group"),
          Z("Plunge pool", "rooftop plunge pool | small pool, roof | pool, skyline", "pool | skyline | towels", solo="pool, skyline", pair="pool, together", groups="pool, group"),
          Z("Greenhouse", "rooftop greenhouse | glass house, roof | garden shed, roof", "plants | glass | pots", solo="gardening", pair="greenhouse, together", groups="greenhouse, group"),
      ]),
    P("Vineyard", f="sundress | linen dress | blouse, skirt | straw hat, dress", m="linen shirt | rolled sleeves | vest | polo",
      light="golden hour | sunset | sunny day | warm light", mood="happy calm", surf="floor:grass|table:barrel|chair:bench",
      detail="grape vines | wine barrels | wine glasses | rolling hills | baskets | cypress trees",
      acts=dict(solo="picking grapes | tasting wine | walking, vines", pair="wine tasting | picking grapes together | walking, vines, together", groups="harvest | wine tasting"),
      zones=[
          Z("Rows", "vineyard rows | grape vines, hills | vineyard, sunset", "vines | grapes | baskets", solo="holding basket | tasting grape", pair="rows, together", groups="harvest"),
          Z("Cellar", "wine cellar | barrel room | cave, wine", "barrels | candles | bottles", solo="tasting, barrel", pair="cellar, together", groups="tasting"),
          Z("Terrace", "vineyard terrace | terrace, view | patio, vineyard", "view | table | wine", solo="wine, view", pair="dinner, terrace", groups="dinner, group"),
      ]),
    P("Lakeside dock", f="swimsuit | sundress | t-shirt, shorts | flannel", m="swim trunks | t-shirt | flannel | shirtless",
      light="sunset | morning mist | moonlight | golden hour", mood="calm", surf="floor:dock|water:lake",
      detail="dock | canoe | lake | pines | reflections | fishing rods",
      acts=dict(solo="sitting, dock | diving | fishing", pair="sitting together, dock | swimming together | canoeing", groups="dock, group"),
      zones=[
          Z("Dock end", "end of dock | dock, lake | pier, lake", "planks | water | ladder", solo="sitting, dock end", pair="dock, together", groups="dock, group"),
          Z("Boathouse", "boathouse | boat shed, lake | boathouse, dock", "boats | ropes | lanterns", solo="leaning, boathouse", pair="boathouse, together", groups="boathouse, group"),
          Z("Swim spot", "swimming spot, lake | lake, rope swing | cove, lake", "rope swing | rocks | water", solo="rope swing", pair="swimming, lake", groups="swimming, group"),
      ]),
    P("Desert oasis", f="silk wrap | bikini | linen dress | scarf, sarong", m="linen shirt | shirtless | robe | turban, linen",
      light="desert sun | sunset | starry night | golden hour", mood="calm", surf="water:spring|floor:sand|bed:tent",
      detail="palm trees | spring | dunes | camels | tent | stars",
      acts=dict(solo="bathing, spring | resting, palm | drinking water", pair="bathing together | resting, tent | stargazing", groups="caravan camp"),
      zones=[
          Z("Spring", "oasis spring | pool, palms | desert spring", "water | palms | reeds", solo="bathing", pair="bathing, together", groups="spring, group"),
          Z("Tent", "desert tent | bedouin tent | tent, cushions", "cushions | lanterns | rugs", solo="lying, cushions", pair="tent, together", groups="tent, group"),
          Z("Dunes", "dunes, oasis | sand dunes, night | desert, stars", "stars | sand | moon", solo="lying, dune", pair="dune, together", groups="dune, group"),
      ]),
], "landscape photography | anime illustration, outdoors | painterly, nature | film photography", NSFW, "full body | wide shot | from behind | cowboy shot")

theme("studio", "Studio", [
    P("Photo studio", f="black dress | white shirt, jeans | bodysuit | blazer", m="black t-shirt | white shirt | suit | turtleneck",
      light="softbox | beauty dish | rim light | hard light", mood="cool serious", surf="floor:backdrop paper|chair:stool|wall:backdrop",
      detail="softboxes | light stands | backdrop paper | camera | reflector | fan",
      acts=dict(solo="posing | looking at viewer | hand on hip", pair="posing together | back-to-back | close pose", groups="group shot"),
      zones=[
          Z("White sweep", "white backdrop | white seamless | studio, white", "white | shadow | fan", solo="posing, white", pair="posing, white, together", groups="group, white"),
          Z("Black backdrop", "black backdrop | studio, black | low key studio", "black | rim light | smoke", solo="posing, black", pair="posing, black, together", groups="group, black"),
          Z("Prop set", "studio set, props | set, sofa | studio, furniture", "sofa | lamp | plant", solo="sitting, prop sofa", pair="sofa, together", groups="set, group"),
      ]),
    P("Art studio", f="paint-splattered apron | oversized shirt | overalls | smock", m="paint-splattered apron | t-shirt | overalls | smock",
      light="north light | skylight | lamp | afternoon", mood="calm", surf="chair:stool|floor:drop cloth|bed:daybed|wall:canvas",
      detail="easels | paint tubes | brushes | canvases | turpentine | sketches",
      acts=dict(solo="painting | sketching | mixing paint", pair="painting, model | sketching another | paint fight", groups="life drawing class"),
      zones=[
          Z("Easel", "easel, studio | painting studio | atelier, canvas", "canvas | brushes | palette", solo="painting, easel", pair="painting, together", groups="class"),
          Z("Model stand", "model stand | posing platform | daybed, studio", "drapery | daybed | lamp", solo="posing, model stand", pair="posing, artist", groups="life drawing"),
          Z("Sculpture", "sculpture studio | clay, studio | marble studio", "clay | tools | marble", solo="sculpting", pair="sculpting together", groups="sculpture class"),
      ]),
    P("Recording studio", f="hoodie | t-shirt, jeans | crop top | jacket", m="hoodie | t-shirt | jacket | flannel",
      light="dim warm light | led strip | monitor glow | lamp", mood="calm cool", surf="chair:chair|wall:foam wall|floor:rug",
      detail="microphone | mixing desk | headphones | guitars | foam panels | lyric sheets",
      acts=dict(solo="singing, microphone | playing guitar | headphones, eyes closed", pair="duet | listening together | jam session", groups="band | recording session"),
      zones=[
          Z("Vocal booth", "vocal booth | booth, microphone | recording booth", "microphone | pop filter | headphones", solo="singing", pair="duet", groups="booth, crowded"),
          Z("Control room", "control room | mixing desk | studio console", "faders | monitors | speakers", solo="mixing", pair="mixing together", groups="producers"),
          Z("Live room", "live room | studio, instruments | band room", "drums | guitars | amps", solo="drumming", pair="jamming", groups="band"),
      ]),
    P("Dance rehearsal", f="leotard | crop top, leggings | dance skirt | sports bra, shorts", m="tank top, joggers | t-shirt | shirtless, dance pants | tights",
      light="studio lights | window light | dim light | spotlight", mood="playful serious", surf="floor:wooden floor|wall:mirror",
      detail="mirrors | barre | speakers | water bottles | sweat | leg warmers",
      acts=dict(solo="dancing | stretching | spinning", pair="partner dance | lift | stretching together", groups="rehearsal | choreography"),
      zones=[
          Z("Mirror", "mirror wall | dance studio | rehearsal mirror", "mirrors | reflection | barre", solo="dancing, mirror", pair="dancing, mirror, together", groups="rehearsal"),
          Z("Center", "studio center | dance floor, studio | rehearsal floor", "floor | light | speakers", solo="leaping", pair="lift", groups="formation"),
          Z("Corner", "studio corner | bench, studio | corner, bags", "bags | water | towels", solo="resting, towel", pair="resting together", groups="break, group"),
      ]),
    P("Tattoo studio", f="tank top | crop top, jeans | slip dress | leather jacket", m="tank top | t-shirt | shirtless | leather jacket",
      light="work lamp | neon sign | dim light | bright light", mood="cool calm", surf="chair:tattoo chair|bed:tattoo bed|wall:flash wall",
      detail="tattoo machine | ink caps | flash art | gloves | stencils | neon",
      acts=dict(solo="getting tattoo | showing tattoo | drawing stencil", pair="tattooing another | showing tattoos | comparing tattoos", groups="waiting, shop"),
      zones=[
          Z("Chair", "tattoo chair | tattoo station | chair, lamp", "machine | ink | lamp", solo="getting tattoo, chair", pair="tattooing", groups="crowd, chair"),
          Z("Flash wall", "flash wall | tattoo designs, wall | shop wall", "flash | frames | neon", solo="choosing design", pair="choosing together", groups="browsing, wall"),
          Z("Bed", "tattoo bed | back piece, bed | lying, tattoo bed", "bed | towel | ink", solo="lying, tattoo bed", pair="back tattoo", groups="bed, crowd"),
      ]),
    P("Film soundstage", f="costume dress | wardrobe robe | stunt outfit | crew t-shirt", m="costume | robe | stunt outfit | crew t-shirt",
      light="film lights | spotlight | backlight | practical lights", mood="serious playful", surf="bed:set bed|wall:set wall|chair:director chair",
      detail="film camera | boom mic | crew | clapperboard | cables | monitors",
      acts=dict(solo="acting | reading script | makeup touch-up", pair="scene, acting | rehearsing lines | kiss scene", groups="crew, set"),
      zones=[
          Z("Set bedroom", "film set, bedroom | movie set, bed | soundstage bed", "set bed | lights | crew", solo="acting, bed", pair="scene, bed", groups="crew, set"),
          Z("Green screen", "green screen | chroma key | green stage", "green screen | markers | lights", solo="acting, green screen", pair="acting together", groups="crew"),
          Z("Video village", "video village | monitors, set | director area", "monitors | chairs | headphones", solo="watching playback", pair="reviewing", groups="crew"),
      ]),
    P("Pottery studio", f="apron | overalls | tank top | oversized shirt", m="apron | t-shirt | overalls | tank top",
      light="window light | warm light | afternoon | lamp", mood="calm playful", surf="chair:stool|table:wheel|floor:floor",
      detail="clay | pottery wheel | kiln | glazes | shelves of pots | water bucket",
      acts=dict(solo="throwing pot | glazing | trimming clay", pair="pottery together | hands on hands, wheel | clay fight", groups="pottery class"),
      zones=[
          Z("Wheel", "pottery wheel | wheel, clay | studio wheel", "clay | water | sponge", solo="centering clay | clay hands", pair="hands on hands, clay", groups="class, wheels"),
          Z("Kiln", "kiln room | kiln, shelves | firing room", "kiln | shelves | pots", solo="loading kiln", pair="kiln, together", groups="kiln, group"),
          Z("Glazing", "glazing table | glaze station | studio table", "glazes | brushes | pots", solo="dipping pot | painting pot", pair="glazing together", groups="glazing, group"),
      ]),
    P("Boudoir studio", f="lingerie | silk robe | sheer bodysuit | corset", m="open shirt | silk robe | boxer briefs | suit, no shirt",
      light="soft window light | candlelight | softbox | dim warm light", mood="sultry calm", surf="bed:bed|chair:velvet chair|wall:window|floor:fur rug",
      detail="silk sheets | flowers | candles | mirror | pearls | velvet",
      acts=dict(solo="posing, bed | looking over shoulder | lying, sheets", pair="posing together, bed | embrace | close pose", groups="group boudoir"),
      zones=[
          Z("Bed", "boudoir bed | studio bed, sheets | bed, window light", "sheets | pillows | flowers", solo="sitting, sheets | stretching, bed", pair="bed, together", groups="bed, group"),
          Z("Window", "boudoir window | window, sheer curtain | bay window, studio", "sheer curtains | light | plants", solo="window, silhouette", pair="window, together", groups="window, group"),
          Z("Velvet chair", "velvet chair, studio | armchair, boudoir | chair, backdrop", "velvet | fur | candles", solo="sitting, velvet chair", pair="sitting on lap, chair", groups="chair, group"),
      ]),
    P("Music video set", f="sequin outfit | latex | streetwear | crop top, cargo pants", m="streetwear | leather jacket | suit | open shirt",
      light="neon | colored lights | strobe | smoke, backlight", mood="cool playful", surf="floor:stage|wall:led wall",
      detail="led wall | smoke | lasers | confetti cannons | camera crane | dancers",
      acts=dict(solo="dancing | lip syncing | posing, neon", pair="dancing together | face to face | lip sync, together", groups="dancers | choreography"),
      zones=[
          Z("LED stage", "led stage | screen wall, stage | stage, lights", "led wall | smoke | lasers", solo="dancing, stage", pair="dancing, stage, together", groups="dancers, stage"),
          Z("Neon room", "neon room | neon set | room, colored lights", "neon | mirrors | smoke", solo="hands up, neon | leaning, mirror", pair="neon, together", groups="neon, group"),
          Z("Car set", "car, music video | vintage car, set | car, neon", "car | rain machine | lights", solo="leaning, car", pair="car, together", groups="car, group"),
      ]),
], "studio photography | fashion photography | anime illustration | fine art photography", NSFW, "full body | cowboy shot | upper body | from side")

theme("redlight", "Red light", [
    P("Brothel parlor", f="lace lingerie | corset, stockings | silk robe | sheer dress", m="open shirt | suit, no necktie | robe | boxer briefs",
      light="red light | lamp light | candlelight | dim warm light", mood="sultry", surf="bed:bed|chair:velvet sofa|wall:wallpaper|floor:carpet",
      detail="red lamps | velvet | perfume | mirrors | champagne | beaded curtain", levels=NSFW_ONLY,
      nsfw={"suggestive": {"people": "lounging, velvet | beckoning"}, "nude": {"people": "lounging, velvet sofa"}},
      zones=[
          Z("Parlor", "brothel parlor | velvet parlor, red light | bordello lounge", "velvet sofas | champagne | lamps"),
          Z("Private room", "brothel room | red room, bed | private room, curtains", "bed | mirror | curtains"),
          Z("Hallway", "red hallway | corridor, doors | hallway, beaded curtain", "doors | lamps | carpet"),
      ]),
    P("Strip club", f="stripper outfit | g-string, heels | latex | sequin bikini", m="stripper outfit | suit | open shirt | briefs",
      light="neon | stage lights | red and blue light | strobe", mood="sultry playful", surf="wall:pole|chair:vip couch|floor:stage", levels=NSFW_ONLY,
      detail="pole | cash | neon | stage | bar | private booth",
      nsfw={"suggestive": {"solo": "pole dance | lap dance pose | money, garter", "pair": "lap dance"}, "nude": {"solo": "pole dance, nude"}},
      zones=[
          Z("Main stage", "strip club stage | stage, pole | club stage, neon", "pole | cash | lights"),
          Z("VIP room", "vip room | private dance room | champagne room", "couch | champagne | curtain"),
          Z("Dressing room", "dressing room, club | backstage, club | mirror, bulbs", "mirror | makeup | heels"),
      ]),
    P("Love hotel", f="lingerie | bathrobe | cosplay | slip dress", m="bathrobe | open shirt | boxer briefs | t-shirt",
      light="pink light | neon | dim light | colored lights", mood="playful sultry", surf="bed:round bed|water:bathtub|wall:mirror wall|floor:floor", levels=NSFW_ONLY,
      detail="round bed | mirror ceiling | pink lights | vending machine | jacuzzi | themed room",
      zones=[
          Z("Round bed", "love hotel room | round bed | rotating bed, pink", "mirror ceiling | pink sheets | lights"),
          Z("Bathroom", "love hotel bathroom | glass bathroom | jacuzzi, love hotel", "jacuzzi | glass | bubbles"),
          Z("Themed room", "themed room, love hotel | train-car themed room | mirror room, love hotel", "costumes | props | lights"),
      ]),
    P("BDSM dungeon", f="latex | leather harness | corset, boots | nude, collar", m="leather harness | latex | leather pants | nude, collar",
      light="red light | dim light | candlelight | spotlight", mood="sultry tense", surf="bed:bondage bed|wall:cross|floor:stone floor|chair:throne", levels=NSFW_ONLY,
      detail="chains | whips | st andrew's cross | cage | candles | leather",
      nsfw={"suggestive": {"people": "holding whip | collar, leash"}, "nude": {"people": "chained, wall | kneeling, collar"},
            "explicit": {"people": "bound, cross | cage | spanking bench"}},
      zones=[
          Z("Cross", "dungeon, cross | st andrew's cross | play room, cross", "cross | cuffs | whip"),
          Z("Cage", "dungeon cage | cage, chains | cell, dungeon", "cage | chains | collar"),
          Z("Throne", "dungeon throne | throne, chains | play room, throne", "throne | candles | leash"),
      ]),
    P("Window district", f="lingerie | bodysuit | corset | latex", m="open shirt | briefs | latex | harness",
      light="red neon | red light | canal reflections | night", mood="sultry", surf="wall:window|bed:bed|chair:stool", levels=NSFW_ONLY,
      detail="red window | canal | neon | curtain | heels | stool",
      nsfw={"suggestive": {"solo": "posing, window | knocking on glass"}},
      zones=[
          Z("Window", "red light window | display window, red | window booth", "glass | curtain | red light"),
          Z("Booth", "window booth room | small room, red | booth, bed", "bed | mirror | lamp"),
          Z("Canal street", "canal street, red light | red light district | alley, neon", "canal | neon | bridges"),
      ]),
    P("Massage parlor", f="massage uniform | towel | silk robe | lingerie", m="towel | robe | boxer briefs | massage uniform",
      light="dim warm light | candlelight | red lamp | soft light", mood="sultry calm", surf="bed:massage table|water:bath|floor:mat", levels=NSFW_ONLY,
      detail="massage oil | towels | candles | incense | stones | curtain",
      nsfw={"suggestive": {"pair": "oil massage | massage, towel"}, "nude": {"pair": "oil massage, nude | body slide"}, "explicit": {"pair": "happy ending | body slide"}},
      zones=[
          Z("Table", "massage table | massage room, oil | treatment room", "oil | towels | candles"),
          Z("Mat room", "mat room | floor mat, massage | soapland mat", "mat | foam | bucket"),
          Z("Bath", "soapland bath | bath, massage parlor | tub, steam", "bath | steam | stools"),
      ]),
    P("Private club", f="evening gown, mask | lingerie, mask | latex dress | nude, mask", m="tuxedo, mask | open shirt, mask | robe, mask | nude, mask",
      light="candlelight | dim red light | low light | chandelier", mood="sultry", surf="bed:daybed|chair:chaise|wall:wall|water:pool", levels=NSFW_ONLY,
      detail="masks | velvet | champagne | candles | curtains | couples",
      zones=[
          Z("Lounge", "secret club lounge | private club | velvet lounge", "velvet | champagne | masks"),
          Z("Play room", "club play room | daybeds, curtains | playroom, candles", "daybeds | curtains | candles"),
          Z("Pool", "club pool, night | indoor pool, candles | private pool", "pool | candles | towels"),
      ]),
    P("Peep show", f="lingerie | bodysuit | stockings | latex", m="briefs | harness | open shirt | robe",
      light="neon | spotlight | red light | rotating light", mood="sultry playful", surf="floor:rotating stage|wall:glass", levels=NSFW_ONLY,
      detail="booth windows | coins | neon | rotating stage | curtains | tokens",
      nsfw={"suggestive": {"solo": "posing, booth glass"}},
      zones=[
          Z("Stage", "peep show stage | rotating stage | booth ring", "booth windows | spotlight"),
          Z("Booth", "peep booth | viewing booth | booth, glass", "glass | coins | curtain"),
          Z("Lobby", "sex shop lobby | adult store | shop, neon", "shelves | toys | neon"),
      ]),
    P("Adult film set", f="lingerie | cosplay | robe | nude", m="nude | robe | open shirt | briefs",
      light="film lights | softbox | ring light | practical lights", mood="sultry playful", surf="bed:set bed|chair:couch|table:kitchen counter|water:pool", levels=NSFW_ONLY,
      detail="camera crew | boom mic | lights | monitors | clapperboard | cables",
      nsfw={"explicit": {"people": "camera, recording | pov"}},
      zones=[
          Z("Bedroom set", "adult film set, bedroom | set bed, lights | studio bedroom", "lights | camera | crew"),
          Z("Couch set", "casting couch | set couch | studio couch", "couch | camera | lights"),
          Z("Pool set", "pool set | villa pool, shoot | pool, film crew", "pool | crew | reflector"),
      ]),
], NSFW, NSFW, "full body | cowboy shot")
