from lib import P, Z, theme

NSFW = "photorealistic, detailed skin | hentai, anime coloring | painterly, erotic illustration | glamour photography"

theme("seafaring", "Seafaring", [
    P("Pirate ship", f="pirate coat, tricorne | corset, puffy shirt | bandana, sash | captain coat", m="pirate coat, tricorne | puffy shirt, sash | bandana, vest | captain coat",
      light="sunset, sea | storm light | lantern light | bright sun", mood="playful tense", surf="wall:mast|floor:deck|table:map table|bed:hammock",
      detail="jolly roger | cannons | rigging | treasure map | rum bottle | parrot",
      acts=dict(solo="climbing rigging | holding cutlass | spyglass, horizon", pair="sword fight | map, together | drinking rum", groups="boarding party | crew, deck"),
      zones=[
          Z("Main deck", "pirate ship deck | ship deck, cannons | galleon deck", "cannons | ropes | barrels", solo="swinging, rope | standing, rail", pair="dueling, deck", groups="crew, deck"),
          Z("Crow's nest", "crow's nest | mast top, sea view | lookout, mast", "spyglass | sails | horizon", solo="looking out, spyglass | climbing mast", pair="crow's nest, together", groups="crew, rigging"),
          Z("Captain's cabin", "captain's cabin | ship cabin, windows | stern cabin", "map table | candles | treasure chest", solo="reading map | counting gold", pair="cabin, together",
            groups="crew, cabin", sky="view", surf="table:map table|bed:hammock|wall:cabin wall"),
      ]),
    P("Sailing yacht", f="striped top, white pants | bikini | sundress | windbreaker", m="polo shirt | linen shirt | swim trunks | windbreaker",
      light="bright sun, sea | golden hour | sunset | overcast", mood="happy calm", surf="floor:deck|wall:railing|water:sea|bed:sun pad",
      detail="sails | sea spray | turquoise water | champagne | ropes | coastline", weather="clear cloudy overcast",
      acts=dict(solo="sunbathing, bow | steering wheel | diving off yacht", pair="champagne, deck | sailing together | swimming, yacht", groups="yacht party"),
      zones=[
          Z("Bow", "yacht bow | sun pad, yacht | front deck, sea", "sun pad | spray | sea", solo="lying, sun pad | sitting, bow", pair="bow, together", groups="bow, group"),
          Z("Helm", "yacht helm | cockpit, sailboat | steering wheel, yacht", "wheel | instruments | sails", solo="steering", pair="steering together", groups="crew, helm"),
          Z("Swim platform", "swim platform | yacht stern, sea | ladder, sea", "ladder | sea | towels", solo="diving | climbing ladder", pair="swimming together", groups="swimming, group"),
      ]),
    P("Ocean liner", f="1920s gown | cloche hat, coat | evening dress | sailor dress", m="tuxedo | suit, hat | sailor uniform | steward uniform",
      light="chandelier | golden hour, sea | moonlight, sea | warm lamps", mood="calm happy", surf="floor:deck|chair:deck chair|bed:berth|wall:railing",
      detail="funnels | lifeboats | grand staircase | ballroom | portholes | steamer trunks",
      acts=dict(solo="leaning, railing | deck chair, blanket | descending staircase", pair="dancing, ballroom | promenade, deck | dinner, liner", groups="ballroom | dinner"),
      zones=[
          Z("Promenade", "liner promenade deck | ship deck, railings | promenade, sea", "deck chairs | lifeboats | sea", solo="strolling", pair="strolling, together", groups="passengers"),
          Z("Grand staircase", "liner grand staircase | ship staircase, dome | ornate staircase", "glass dome | clock | carpet", solo="descending", pair="staircase, together", groups="crowd", sky="view"),
          Z("Stateroom", "stateroom | first class cabin | ship suite", "porthole | trunk | bed", solo="unpacking trunk", pair="stateroom, together", groups="cabin, crowd", sky="view"),
      ]),
    P("Harbor town", f="sundress | striped shirt | linen dress | cardigan", m="linen shirt | striped shirt | jacket | fisherman sweater",
      light="morning sun | golden hour | overcast | lantern light", mood="calm happy", surf="floor:quay|chair:bench|wall:stone wall",
      detail="boats | colorful houses | bollards | gulls | fish market | lighthouse",
      acts=dict(solo="walking, quay | sitting, bollard | eating ice cream", pair="walking, harbor | dinner, waterfront | watching boats", groups="crowd, harbor"),
      zones=[
          Z("Quay", "harbor quay | waterfront, boats | marina", "boats | ropes | bollards", solo="sitting, quay", pair="quay, together", groups="quay, crowd"),
          Z("Waterfront cafe", "waterfront cafe | harbor restaurant | terrace, harbor", "seafood | wine | boats", solo="eating seafood", pair="dinner, harbor", groups="dinner, group"),
          Z("Lighthouse pier", "pier, lighthouse | breakwater | harbor lighthouse", "lighthouse | waves | fishermen", solo="walking, pier", pair="pier, together", groups="fishermen"),
      ]),
    P("Fishing boat", f="raincoat | rubber boots, overalls | sweater | waterproof jacket", m="raincoat | rubber boots | fisherman sweater | waterproof jacket",
      light="dawn, sea | overcast | storm light | sunset", mood="serious calm", surf="floor:deck|wall:rail",
      detail="nets | fish | waves | gulls | buoys | wheelhouse",
      acts=dict(solo="hauling net | gutting fish | steering", pair="hauling together | sharing coffee | storm, holding on", groups="crew"),
      zones=[
          Z("Deck", "fishing boat deck | trawler deck | boat deck, nets", "nets | fish | ice", solo="sorting fish | coiling rope", pair="nets, together", groups="crew"),
          Z("Wheelhouse", "wheelhouse | boat cabin | bridge, fishing boat", "wheel | radar | coffee", solo="radio call | coffee, wheelhouse", pair="wheelhouse, together", groups="crew", sky="view"),
          Z("Bow", "boat bow, waves | prow, sea | front deck, spray", "spray | waves | gulls", solo="standing, bow", pair="bow, together", groups="bow, crew"),
      ]),
    P("Desert island", f="torn clothes | bikini | sarong | palm leaf skirt", m="torn shirt | shorts | shirtless | palm leaf clothes",
      light="tropical sun | sunset | moonlight | golden hour", mood="calm happy", surf="floor:sand|water:lagoon|bed:hammock",
      detail="palm trees | coconuts | shipwreck | message in bottle | crabs | driftwood", weather="clear cloudy rain",
      acts=dict(solo="opening coconut | building shelter | fishing, spear", pair="building fire | sharing coconut | signal fire", groups="castaways"),
      zones=[
          Z("Beach", "desert island beach | white sand, palms | island shore", "sand | palms | waves", solo="walking, beach", pair="beach, together", groups="castaways, beach"),
          Z("Shelter", "palm shelter | island hut | lean-to, beach", "palm leaves | fire | hammock", solo="resting, hammock", pair="shelter, together", groups="camp"),
          Z("Lagoon", "island lagoon | clear lagoon | reef, shallow", "fish | coral | water", solo="swimming", pair="swimming together", groups="lagoon, group"),
      ]),
    P("Smuggler cove", f="pirate outfit | cloak | corset, boots | sailor outfit", m="pirate outfit | cloak | smuggler coat | sailor outfit",
      light="lantern light | moonlight | torchlight | fog", mood="tense", surf="floor:sand|wall:cave wall",
      detail="crates | rowboat | lanterns | barrels | cave | rope",
      acts=dict(solo="hiding crate | holding lantern | lookout", pair="secret deal | rowing | hiding together", groups="smugglers"),
      zones=[
          Z("Cave", "smuggler cave | sea cave, crates | cove cave", "crates | lanterns | water", solo="counting crates", pair="deal, cave", groups="smugglers"),
          Z("Beach", "hidden cove | rocky cove, night | cove beach", "rowboat | rocks | waves", solo="dragging boat", pair="rowing", groups="landing party"),
          Z("Cliff path", "cliff path, sea | coastal path | clifftop, lighthouse", "lantern | wind | sea", solo="signal lantern", pair="lookout, together", groups="lookouts"),
      ]),
    P("Riverboat", f="southern belle dress | parasol, gown | linen dress | gambler outfit", m="riverboat gambler suit | vest, hat | linen suit | captain uniform",
      light="golden hour | lanterns | sunset, river | morning mist", mood="calm playful", surf="table:card table|chair:deck chair|wall:railing",
      detail="paddle wheel | river | card tables | brass band | magnolias | smokestacks",
      acts=dict(solo="playing cards | leaning, railing | parasol", pair="card game | dancing, deck | strolling, deck", groups="poker table | brass band"),
      zones=[
          Z("Deck", "riverboat deck | paddle steamer deck | river, railing", "paddle wheel | river | trees", solo="railing, river", pair="deck, together", groups="passengers"),
          Z("Card room", "riverboat salon | card room | gambling saloon", "cards | chips | whiskey", solo="dealing cards", pair="poker", groups="poker game", sky="view"),
          Z("Landing", "river landing | riverboat dock | dock, river town", "dock | crates | crowd", solo="boarding", pair="goodbye, dock", groups="crowd, landing"),
      ]),
    P("Naval ship", f="naval uniform | officer uniform | sailor uniform | dress whites", m="naval uniform | officer uniform | sailor uniform | dress whites",
      light="bright sun, sea | overcast | sunset | night, deck lights", mood="serious calm", surf="floor:deck|wall:railing",
      detail="gun turrets | flags | radar | sea | anchor chain | helicopter",
      acts=dict(solo="saluting | binoculars | standing watch", pair="salute | briefing | leaning, railing", groups="formation | crew"),
      zones=[
          Z("Flight deck", "carrier flight deck | ship deck, jets | flight deck, sea", "jets | markings | sea", solo="signaling", pair="deck, together", groups="deck crew"),
          Z("Bridge", "navy ship bridge | command bridge, sea | ship bridge", "consoles | charts | windows", solo="captain, bridge", pair="bridge, together", groups="officers", sky="view"),
          Z("Bunks", "ship berthing | sailor bunks | crew quarters", "bunks | lockers | lamps", solo="lying, bunk", pair="bunks, talking", groups="crew"),
      ]),
], "maritime painting | cinematic still, sea | anime illustration, ocean | oil painting, seascape", NSFW, "full body | wide shot | cowboy shot | from below")

theme("music", "Music & stage", [
    P("Rock concert", f="leather jacket, ripped jeans | band t-shirt | corset, fishnets | crop top, plaid skirt", m="leather jacket | band t-shirt | tank top, chains | ripped jeans",
      light="stage lights | strobe | spotlight | pyrotechnics", mood="playful cool", surf="floor:stage|wall:amp stack",
      detail="amplifiers | crowd | microphone stand | drum kit | smoke | confetti",
      acts=dict(solo="playing guitar | singing, microphone | headbanging", pair="guitar duel | back-to-back, guitars | duet", groups="band | moshpit"),
      zones=[
          Z("Stage", "concert stage | rock stage, lights | arena stage", "drum kit | amps | crowd", solo="guitar solo", pair="sharing microphone", groups="band"),
          Z("Crowd", "concert crowd | moshpit | front row", "hands up | phones | barricade", solo="crowd surfing", pair="on shoulders", groups="moshpit"),
          Z("Backstage", "concert backstage | green room | backstage, cables", "cables | road cases | drinks", solo="tuning guitar", pair="backstage, together", groups="band, backstage"),
      ]),
    P("Jazz club", f="cocktail dress | velvet gown | sequin dress | silk blouse", m="suit, fedora | vest, rolled sleeves | tuxedo | turtleneck",
      light="dim warm light | spotlight | candlelight | blue light", mood="calm cool", surf="table:small table|chair:booth|wall:brick wall",
      detail="saxophone | double bass | piano | smoke | candles | martinis",
      acts=dict(solo="playing saxophone | singing, microphone | listening, martini", pair="slow dance | duet, piano | listening together", groups="jazz trio | audience"),
      zones=[
          Z("Stage", "jazz club stage | small stage, spotlight | bandstand", "piano | bass | spotlight", solo="singing", pair="duet", groups="trio"),
          Z("Tables", "jazz club tables | candlelit tables | club floor", "candles | drinks | smoke", solo="listening", pair="table, together", groups="audience"),
          Z("Bar", "jazz club bar | bar, bottles | speakeasy bar", "bottles | bartender | stools", solo="drink, bar", pair="bar, together", groups="crowd, bar"),
      ]),
    P("Concert hall", f="black gown | evening dress | velvet dress | formal dress", m="tailcoat | tuxedo | black suit | formal suit",
      light="stage lights | warm hall light | spotlight | chandelier", mood="serious calm", surf="chair:seat|floor:stage",
      detail="orchestra | music stands | violins | grand piano | balconies | conductor",
      acts=dict(solo="playing violin | playing piano | conducting", pair="duet, piano | violin duet | bowing", groups="orchestra | audience"),
      zones=[
          Z("Stage", "concert hall stage | orchestra stage | symphony stage", "music stands | instruments | conductor", solo="violin solo", pair="duet", groups="orchestra"),
          Z("Balcony box", "theater box | balcony seats | opera box", "velvet | binoculars | gilding", solo="watching, box", pair="box, together", groups="box, guests"),
          Z("Rehearsal", "rehearsal room, orchestra | practice room | music room", "stands | sheet music | piano", solo="practicing", pair="practicing together", groups="rehearsal"),
      ]),
    P("Opera house", f="opera gown | costume, opera | ball gown | velvet cape", m="opera costume | tuxedo | cape | tailcoat",
      light="chandelier | stage lights | footlights | candlelight", mood="serious playful", surf="floor:stage|chair:velvet seat|wall:curtain",
      detail="red curtains | gilded boxes | chandelier | sets | costumes | masks",
      acts=dict(solo="singing aria | bowing | applying makeup", pair="duet, stage | dramatic embrace | dressing room, together", groups="chorus | curtain call"),
      zones=[
          Z("Stage", "opera stage | stage, sets | opera performance", "sets | spotlight | curtains", solo="aria", pair="duet", groups="chorus"),
          Z("Dressing room", "opera dressing room | dressing room, mirrors | costume room", "mirrors | wigs | flowers", solo="makeup", pair="costume, help", groups="cast"),
          Z("Foyer", "opera foyer | grand foyer | opera staircase", "chandelier | marble | crowd", solo="descending stairs", pair="foyer, together", groups="crowd", sky="view"),
      ]),
    P("Street busking", f="hoodie | denim jacket | sundress | beanie, cardigan", m="hoodie | denim jacket | flannel | beanie",
      light="golden hour | streetlights | overcast | neon", mood="happy calm", surf="floor:sidewalk|wall:wall",
      detail="guitar case | coins | crowd | amplifier | street lights | pigeons",
      acts=dict(solo="busking, guitar | singing, street | playing violin, street", pair="duet, street | dancing to music | dropping coins", groups="crowd, busker"),
      zones=[
          Z("Plaza", "city plaza, busker | square, crowd | plaza, fountain", "crowd | fountain | guitar case", solo="playing guitar", pair="duet", groups="crowd"),
          Z("Subway entrance", "subway entrance, busker | underpass | station tunnel", "echo | tiles | commuters", solo="playing violin", pair="duet, tunnel", groups="commuters", sky="in"),
          Z("Bridge", "bridge, busker | river bridge | footbridge, music", "river | lamps | crowd", solo="singing, bridge", pair="bridge, music", groups="crowd, bridge"),
      ]),
    P("Piano bar", f="cocktail dress | slip dress | blazer, silk top | velvet dress", m="suit | blazer | vest | open collar shirt",
      light="dim warm light | piano lamp | candlelight | city lights", mood="calm sultry", surf="wall:piano|chair:bar stool|table:bar",
      detail="grand piano | whiskey | candles | sheet music | city view | roses",
      acts=dict(solo="playing piano | leaning, piano | singing, piano", pair="sitting on piano, singing | duet, bench | slow dance", groups="singalong"),
      zones=[
          Z("Piano", "grand piano, bar | piano lounge | piano, spotlight", "piano | lamp | glasses", solo="playing", pair="piano bench, together", groups="around piano"),
          Z("Window bar", "piano bar, window | skyline bar | lounge, city view", "skyline | glasses | candles", solo="drink, window", pair="window, together", groups="lounge", sky="view"),
          Z("Booth", "velvet booth | bar booth | corner booth", "velvet | candle | drinks", solo="booth, drink", pair="booth, close", groups="booth, group"),
      ]),
    P("Garage band", f="band t-shirt | flannel, jeans | crop top, shorts | hoodie", m="band t-shirt | flannel | tank top | hoodie",
      light="garage light | string lights | lamp | sunset, garage door", mood="playful happy", surf="floor:concrete|chair:amp|wall:wall",
      detail="amps | drum kit | posters | cables | soda cans | old couch",
      acts=dict(solo="drumming | playing bass | writing lyrics", pair="jamming | sharing headphones | singing together", groups="band practice"),
      zones=[
          Z("Garage", "garage, band | garage rehearsal | open garage door", "drums | amps | posters", solo="guitar, amp | singing, garage", pair="jamming", groups="band", sky="view"),
          Z("Couch", "old couch, garage | band couch | sofa, posters", "couch | guitars | snacks", solo="lying, couch, guitar | notebook, lyrics", pair="couch, together", groups="hanging out"),
          Z("Driveway", "driveway, band | front yard gig | street, garage", "neighbors | lights | amps", solo="playing, driveway", pair="driveway, together", groups="neighborhood gig"),
      ]),
    P("Idol stage", f="idol outfit | frilled dress | sequin outfit | sparkly costume", m="idol outfit | sequin jacket | stage costume | sparkly suit",
      light="stage lights | colorful lights | spotlight | glowsticks", mood="happy playful", surf="floor:stage",
      detail="glowsticks | fans | screens | confetti | microphones | stage lights",
      acts=dict(solo="singing, idol | dancing, idol | waving to fans", pair="duet, idol | dancing together", groups="idol group | choreography"),
      zones=[
          Z("Main stage", "idol concert stage | arena, glowsticks | dome stage", "glowsticks | screens | confetti", solo="center stage", pair="duet", groups="idol group"),
          Z("Handshake event", "fan meeting | handshake event | autograph table", "fans | posters | markers", solo="signing autograph", pair="meeting, fan", groups="fan meeting"),
          Z("Dressing room", "idol dressing room | backstage, mirrors | green room", "mirrors | costumes | snacks", solo="makeup", pair="fixing hair", groups="members, backstage"),
      ]),
    P("Ballet theater", f="tutu | leotard, tights | ballet costume | rehearsal skirt", m="ballet tights | leotard | ballet costume | rehearsal clothes",
      light="stage lights | spotlight | window light | warm light", mood="serious calm", surf="floor:stage|wall:barre",
      detail="pointe shoes | tutus | barre | mirrors | curtain | roses",
      acts=dict(solo="pirouette | arabesque | tying pointe shoes", pair="pas de deux | lift | stretching together", groups="corps de ballet | rehearsal"),
      zones=[
          Z("Stage", "ballet stage | theater stage, ballet | performance stage", "spotlight | set | curtain", solo="pirouette, stage", pair="pas de deux", groups="corps de ballet"),
          Z("Studio", "ballet studio | rehearsal studio, barre | dance studio, mirrors", "barre | mirrors | piano", solo="barre exercise", pair="lift", groups="class", sky="view"),
          Z("Wings", "stage wings | backstage, curtain | wings, dancers", "ropes | curtain | lights", solo="waiting, wings", pair="whispering, wings", groups="dancers, wings"),
      ]),
], "concert photography | anime illustration, music | cinematic still | poster art", NSFW, "full body | cowboy shot | from below | wide shot")

theme("cities", "World cities", [
    P("Paris", f="trench coat, beret | striped shirt, skirt | little black dress | silk scarf, coat", m="trench coat | turtleneck | blazer | striped shirt",
      light="golden hour | overcast | blue hour | morning light", mood="calm happy", surf="table:cafe table|chair:bistro chair|wall:balcony railing",
      detail="eiffel tower | croissant | cafe chairs | seine | bookstalls | haussmann buildings",
      acts=dict(solo="eating croissant | walking, seine | reading, cafe", pair="kiss, eiffel tower | cafe, together | walking, seine", groups="picnic, champ de mars"),
      zones=[
          Z("Cafe", "parisian cafe terrace | sidewalk cafe, paris | bistro, paris", "espresso | croissant | chairs", solo="coffee, terrace", pair="cafe, together", groups="cafe, group"),
          Z("Seine", "seine riverbank | paris quay | bridge, seine", "bookstalls | bridges | boats", solo="sitting, quay", pair="walking, quay", groups="picnic, quay"),
          Z("Balcony", "paris balcony, rooftops | wrought iron balcony | apartment balcony, paris", "rooftops | chimneys | eiffel tower", solo="coffee, balcony", pair="balcony, together",
            groups="balcony, group"),
      ]),
    P("Venice", f="summer dress | carnival mask, gown | linen dress | blouse, skirt", m="linen shirt | gondolier shirt, hat | carnival mask, cape | blazer",
      light="golden hour | morning haze | lantern light | overcast", mood="calm happy", surf="chair:gondola seat|wall:bridge",
      detail="gondolas | canals | bridges | carnival masks | pigeons | laundry lines",
      acts=dict(solo="gondola ride | feeding pigeons | wearing mask", pair="gondola, together | kiss, bridge | dinner, canal", groups="carnival crowd"),
      zones=[
          Z("Canal", "venice canal, gondola | grand canal | narrow canal, venice", "gondolas | water | bridges", solo="gondola", pair="gondola, together", groups="boats"),
          Z("Piazza", "piazza san marco | venice square | piazza, pigeons", "pigeons | campanile | cafe", solo="walking, piazza", pair="piazza, together", groups="crowd"),
          Z("Bridge", "rialto bridge | venice bridge, canal | stone bridge, venice", "canal | gondolas | crowd", solo="leaning, bridge", pair="bridge, together", groups="crowd, bridge"),
      ]),
    P("Tokyo", f="streetwear | oversized hoodie | trench coat | kimono", m="streetwear | hoodie | suit | jacket",
      light="neon lights | rain, neon | overcast | morning light", mood="cool happy", surf="wall:vending machine|chair:train seat",
      detail="vending machines | neon signs | crosswalk | trains | konbini | cherry trees",
      acts=dict(solo="crossing street | buying drink, vending machine | holding umbrella", pair="photo booth | crossing, hand in hand | ramen, together", groups="crowd, crossing"),
      zones=[
          Z("Shibuya", "shibuya crossing | tokyo intersection | crowded crosswalk", "screens | crowd | traffic", solo="crossing", pair="crossing, together", groups="crowd"),
          Z("Back street", "tokyo alley, lanterns | yokocho | izakaya alley", "lanterns | izakaya | signs", solo="walking, alley", pair="izakaya, together", groups="izakaya, group"),
          Z("Konbini", "convenience store | konbini, night | store front, tokyo", "shelves | onigiri | lights", solo="shopping, konbini", pair="snacks, together", groups="konbini, group", sky="view"),
      ]),
    P("New York", f="trench coat | leather jacket | business suit | puffer jacket", m="overcoat | leather jacket | suit | hoodie",
      light="golden hour | overcast | neon | streetlights", mood="cool happy", surf="wall:brownstone|chair:bench|floor:fire escape",
      detail="yellow taxis | skyscrapers | steam vents | hot dog cart | subway | fire escapes",
      acts=dict(solo="hailing taxi | coffee, walking | sitting, stoop", pair="walking, avenue | skating, rink | sitting, stoop", groups="crowd, times square"),
      zones=[
          Z("Avenue", "manhattan avenue | city street, taxis | times square", "taxis | screens | crowds", solo="walking, avenue", pair="walking together", groups="crowd"),
          Z("Brownstone stoop", "brownstone stoop | brooklyn street | stoop, brownstones", "stairs | trees | railings", solo="reading, stoop | coffee, steps", pair="stoop, together", groups="stoop, group"),
          Z("Central park", "central park | park, skyline | bow bridge", "trees | skyline | pond", solo="walking, park", pair="picnic, park", groups="picnic"),
      ]),
    P("Hanoi", f="ao dai | sundress, non la | t-shirt, shorts | blouse, jeans", m="t-shirt | linen shirt | shorts | jacket",
      light="morning haze | golden hour | lantern light | rain", mood="calm happy", surf="chair:plastic stool|table:low table",
      detail="motorbikes | street food | lanterns | tangled wires | coffee | lotus",
      acts=dict(solo="drinking coffee, stool | riding motorbike | eating pho", pair="eating, plastic stools | motorbike, together | walking, old quarter", groups="street food, group"),
      zones=[
          Z("Old quarter", "hanoi old quarter | narrow street, motorbikes | old town, lanterns", "motorbikes | shops | wires", solo="walking, old quarter", pair="motorbike, together", groups="crowd"),
          Z("Street cafe", "sidewalk cafe, plastic stools | coffee street | egg coffee cafe", "plastic stools | coffee | motorbikes", solo="coffee, stool", pair="coffee, together", groups="friends, stools"),
          Z("Hoan Kiem lake", "hoan kiem lake | lake, red bridge | lakeside, willows", "red bridge | willows | tower", solo="walking, lake", pair="lakeside, together", groups="morning exercise"),
      ]),
    P("Istanbul", f="headscarf, long dress | coat, scarf | blouse, skirt | sundress", m="linen shirt | jacket | sweater | suit",
      light="golden hour | morning light | lantern light | overcast", mood="calm happy", surf="chair:cushion|table:low table",
      detail="mosques | bosphorus | turkish tea | lanterns | spices | seagulls",
      acts=dict(solo="drinking tea | browsing bazaar | feeding seagulls", pair="tea, together | ferry, bosphorus | bazaar, bargaining", groups="crowd, bazaar"),
      zones=[
          Z("Grand bazaar", "grand bazaar | covered bazaar | lamp shop, bazaar", "lamps | carpets | spices", solo="browsing lamps", pair="bargaining", groups="crowd", sky="in"),
          Z("Bosphorus", "bosphorus waterfront | ferry, bosphorus | seaside, mosques", "ferries | mosques | gulls", solo="ferry, railing", pair="ferry, together", groups="crowd, ferry"),
          Z("Rooftop tea", "rooftop cafe, mosque view | terrace, istanbul | roof, domes", "tea | domes | cushions", solo="tea, rooftop", pair="tea, together", groups="rooftop, group"),
      ]),
    P("Marrakech", f="kaftan | linen dress | headscarf | sundress", m="djellaba | linen shirt | kaftan | jacket",
      light="desert sun | golden hour | lantern light | dusk", mood="happy calm", surf="chair:cushions|table:low table|water:fountain",
      detail="spice piles | lanterns | rugs | mint tea | snake charmer | orange trees", weather="clear cloudy",
      acts=dict(solo="browsing souk | pouring mint tea | holding lantern", pair="bargaining | mint tea, together | walking, souk", groups="crowd, square"),
      zones=[
          Z("Souk", "marrakech souk | market alley | spice market", "spices | lanterns | rugs", solo="browsing", pair="bargaining", groups="crowd"),
          Z("Riad", "riad courtyard | courtyard, fountain | moroccan courtyard", "fountain | tiles | orange tree", solo="sitting, fountain", pair="tea, courtyard", groups="dinner, riad"),
          Z("Square", "jemaa el-fnaa | night market square | square, food stalls", "food stalls | smoke | crowds", solo="eating, stall", pair="square, together", groups="crowd"),
      ]),
    P("Havana", f="sundress | ruffled dress | white blouse | headwrap, skirt", m="guayabera | panama hat | linen suit | white shirt",
      light="golden hour | tropical sun | warm evening light | streetlights", mood="happy playful", surf="chair:car seat|wall:wall",
      detail="vintage cars | pastel buildings | cigars | salsa music | balconies | malecon", weather="clear cloudy rain",
      acts=dict(solo="smoking cigar | dancing salsa | leaning, vintage car", pair="salsa dancing | convertible ride | walking, malecon", groups="street party"),
      zones=[
          Z("Old street", "havana street, vintage cars | colorful street | old havana", "vintage cars | pastel walls | balconies", solo="leaning, car", pair="convertible", groups="crowd"),
          Z("Malecon", "malecon | seawall, havana | sea wall, sunset", "waves | seawall | cars", solo="sitting, seawall", pair="seawall, together", groups="crowd, seawall"),
          Z("Salsa bar", "salsa bar | dance hall, havana | bar, band", "band | rum | dancers", solo="dancing", pair="salsa", groups="dancers", sky="view"),
      ]),
    P("Seoul", f="oversized coat | hanbok | trendy streetwear | knit sweater, skirt", m="long coat | hanbok | streetwear | knit sweater",
      light="neon lights | autumn light | night, city lights | overcast", mood="calm happy", surf="chair:bench|table:bbq table",
      detail="neon signs | palaces | cafes | bbq grill | n seoul tower | hanok roofs",
      acts=dict(solo="taking selfie | eating street food | walking, palace", pair="korean bbq | couple photo | walking, palace", groups="bbq, friends"),
      zones=[
          Z("Palace", "gyeongbokgung palace | korean palace | palace courtyard", "pavilions | hanbok | gates", solo="hanbok, posing | holding fan, palace", pair="palace, together", groups="tourists"),
          Z("BBQ restaurant", "korean bbq restaurant | bbq table, grill | soju restaurant", "grill | soju | side dishes", solo="grilling meat", pair="bbq, together", groups="friends, bbq", sky="view"),
          Z("Night street", "seoul night street | myeongdong | neon street", "neon | food stalls | crowd", solo="street food", pair="walking together", groups="crowd"),
      ]),
], "travel photography | cinematic still, city | anime illustration, city | watercolor, travel sketch", NSFW, "cowboy shot | full body | wide shot | from behind")

theme("retro", "Retro 80s-90s", [
    P("Arcade", f="neon windbreaker | crop top, high-waist jeans | denim jacket | leg warmers, leotard", m="windbreaker | denim jacket | t-shirt, jeans | varsity jacket",
      light="neon lights | screen glow | dim light | colored lights", mood="playful happy", surf="wall:arcade cabinet|floor:carpet",
      detail="arcade cabinets | tokens | high score | neon | joystick | pinball",
      acts=dict(solo="playing arcade | leaning, cabinet | holding tokens", pair="playing together | competing, high score | sharing tokens", groups="crowd, arcade"),
      zones=[
          Z("Cabinets", "arcade, cabinets | game room, neon | video arcade", "cabinets | screens | carpet", solo="playing", pair="playing together", groups="crowd"),
          Z("Pinball", "pinball corner | pinball machines | arcade, pinball", "pinball | lights | flippers", solo="pinball", pair="pinball, together", groups="watching"),
          Z("Prize counter", "prize counter | arcade counter | ticket counter", "prizes | tickets | toys", solo="choosing prize", pair="prize, together", groups="queue"),
      ]),
    P("Shopping mall", f="shoulder pads, blazer | neon top, skirt | denim jacket | scrunchie, sweater", m="windbreaker | polo shirt | denim jacket | t-shirt",
      light="skylight | fluorescent light | neon | warm light", mood="happy playful", surf="chair:bench|water:fountain",
      detail="fountain | escalators | shopping bags | food court | neon signs | palm trees",
      acts=dict(solo="carrying bags | sitting, fountain | sipping soda", pair="shopping together | photo booth | food court, together", groups="mall crowd"),
      zones=[
          Z("Atrium", "80s mall atrium | mall, fountain | mall, escalators", "fountain | escalators | plants", solo="fountain, coin", pair="escalator, together", groups="crowd", sky="view"),
          Z("Food court", "mall food court | food court, neon | pizza counter", "pizza | soda | trays", solo="eating pizza", pair="sharing food", groups="friends"),
          Z("Record store", "record store | music store, posters | tape shop", "cassettes | posters | listening booth", solo="headphones, booth", pair="choosing tapes", groups="browsing"),
      ]),
    P("Video store", f="oversized sweater | denim jacket | flannel, jeans | crop top", m="flannel | denim jacket | hoodie | t-shirt",
      light="fluorescent light | neon sign | dim light | night", mood="calm playful", surf="wall:shelves|table:counter",
      detail="vhs tapes | movie posters | rewind sign | candy | popcorn | counter",
      acts=dict(solo="browsing tapes | holding vhs | reading back cover", pair="choosing movie | arguing, movie | counter, renting", groups="movie night planning"),
      zones=[
          Z("Aisles", "video store aisles | vhs shelves | rental store", "vhs | posters | signs", solo="browsing", pair="choosing", groups="browsing"),
          Z("Counter", "rental counter | video store counter | checkout", "counter | candy | tapes", solo="renting", pair="counter, together", groups="queue"),
          Z("Back room", "movie night, vhs | living room, tv | couch, tapes", "crt tv | vhs player | popcorn", solo="watching tv", pair="couch, movie", groups="movie night", sky="view"),
      ]),
    P("Drive-in", f="poodle skirt | letterman jacket | sundress | denim jacket", m="letterman jacket | leather jacket | t-shirt, jeans | flannel",
      light="projector light | night, screen glow | neon | dusk", mood="calm happy", surf="chair:car seat|wall:car",
      detail="giant screen | classic cars | popcorn | speaker box | stars | snack bar", times="evening night",
      acts=dict(solo="watching movie, car | eating popcorn | sitting, car hood", pair="cuddling, car | sharing popcorn | kiss, car", groups="truck bed, friends"),
      zones=[
          Z("Car", "drive-in, car | car, screen | convertible, drive-in", "screen | popcorn | speaker", solo="watching, car", pair="car, together", groups="car, crowded"),
          Z("Truck bed", "truck bed, drive-in | blankets, truck | pickup, screen", "blankets | pillows | screen", solo="lying, truck bed", pair="truck bed, together", groups="friends"),
          Z("Snack bar", "drive-in snack bar | concession stand | neon snack bar", "hot dogs | soda | neon", solo="buying snacks", pair="snacks, together", groups="queue"),
      ]),
    P("Roller rink", f="roller skates, shorts | neon leotard | tube socks, skirt | satin jacket", m="roller skates | satin jacket | tank top, shorts | headband",
      light="disco ball | neon | colored lights | spotlight", mood="playful happy", surf="floor:rink|wall:rail",
      detail="disco ball | roller skates | neon | music | rail | snack counter",
      acts=dict(solo="roller skating | spinning, skates | holding rail", pair="skating, hand in hand | couple skate | falling, laughing", groups="skating crowd"),
      zones=[
          Z("Rink", "roller rink | skating rink, disco ball | rink floor", "disco ball | lights | skaters", solo="skating", pair="skating together", groups="crowd"),
          Z("Rail", "rink rail | edge of rink | rail, skaters", "rail | lights | skates", solo="leaning, rail", pair="rail, together", groups="rail, group"),
          Z("Skate counter", "skate rental | rink counter | lockers, rink", "skates | lockers | benches", solo="lacing skates", pair="lacing, together", groups="benches"),
      ]),
    P("Bowling alley", f="bowling shirt | high-waist jeans, crop top | skirt, sneakers | polo shirt", m="bowling shirt | polo shirt | jeans | t-shirt",
      light="neon | fluorescent light | blacklight | warm light", mood="playful happy", surf="floor:lane|chair:bench",
      detail="bowling pins | bowling balls | scoreboard | neon | shoes | nachos",
      acts=dict(solo="bowling | cheering | holding ball", pair="high five | teaching bowling | rivalry", groups="league night"),
      zones=[
          Z("Lane", "bowling lane | bowling alley | lanes, pins", "pins | ball | lane", solo="strike, celebrating | aiming ball", pair="bowling, together", groups="team"),
          Z("Seats", "bowling seats | scoring table | lane seats", "scoreboard | snacks | shoes", solo="sitting, seats", pair="seats, together", groups="team, seats"),
          Z("Bar", "bowling alley bar | snack bar | lounge, bowling", "beer | nachos | neon", solo="drink", pair="bar, together", groups="bar, group"),
      ]),
    P("Outrun highway", f="sunglasses, jacket | neon outfit | leather jacket | crop top", m="sunglasses, jacket | leather jacket | neon outfit | t-shirt",
      light="synthwave sunset | neon grid | night | magenta glow", mood="cool", surf="chair:car seat|floor:road",
      detail="sports car | palm trees | neon grid | sunset | mountains | chrome", times="evening night", weather="clear cloudy",
      acts=dict(solo="driving | leaning, sports car | sunglasses, wind", pair="driving together | leaning on car | night drive", groups="car meet"),
      zones=[
          Z("Highway", "synthwave highway | neon road | highway, palms", "palm trees | grid | sun", solo="hand on wheel | hair blowing, car", pair="driving together", groups="cars"),
          Z("Beach road", "coastal road, neon | beach highway | sea road, sunset", "sea | palms | car", solo="car, beach", pair="beach, car", groups="car meet"),
          Z("Neon city", "neon city, synthwave | retro city | city, grid", "skyline | neon | grid", solo="walking, neon", pair="neon, together", groups="crowd, neon"),
      ]),
    P("Retro bedroom", f="oversized t-shirt | scrunchie, sweater | denim jacket | pajamas", m="t-shirt | flannel | hoodie | pajamas",
      light="lamp light | morning light | lava lamp | tv glow", mood="calm playful", surf="bed:bed|floor:carpet|chair:beanbag",
      detail="posters | cassette player | crt tv | game console | lava lamp | landline phone",
      acts=dict(solo="talking, landline phone | playing console | listening to walkman", pair="playing console together | mixtape | lying, bed, talking", groups="sleepover"),
      zones=[
          Z("Bed", "90s bedroom, bed | retro bedroom | bedroom, posters", "posters | phone | magazines", solo="lying, bed, phone", pair="bed, together",
            groups="sleepover", sky="view"),
          Z("TV corner", "crt tv corner | game console, carpet | tv, beanbags", "console | controllers | snacks", solo="gaming", pair="gaming together", groups="gaming, group", sky="view"),
          Z("Desk", "retro desk, computer | desk, cassette | study desk, 90s", "computer | cassettes | lamp", solo="typing, computer", pair="desk, together", groups="crowded desk", sky="view"),
      ]),
    P("Disco", f="sequin jumpsuit | wrap dress | halter top, flared pants | gold dress", m="leisure suit | open collar shirt | flared pants | gold chain",
      light="disco ball | colorful lights | spotlight | strobe", mood="playful happy", surf="floor:light-up floor|chair:booth",
      detail="disco ball | light-up floor | platform shoes | glitter | dj booth | afro wigs",
      acts=dict(solo="disco dancing | pointing up, dance | twirling", pair="disco dance, partner | spinning, partner", groups="dance line | crowd, dancing"),
      zones=[
          Z("Dance floor", "disco dance floor | light-up floor | 70s club", "disco ball | lights | crowd", solo="dancing", pair="dancing together", groups="crowd"),
          Z("DJ booth", "disco dj booth | turntables | booth, records", "records | turntables | lights", solo="djing", pair="booth, together", groups="crowd, booth"),
          Z("Lounge", "disco lounge | velvet booth, disco | club lounge, 70s", "velvet | cocktails | mirrors", solo="lounging", pair="booth, together", groups="lounge"),
      ]),
], "80s anime | retro photography, film grain | synthwave art | vhs aesthetic", NSFW, "cowboy shot | full body | from side | wide shot")

theme("holidays", "Holidays", [
    P("Christmas market", f="winter coat, scarf | knit sweater | santa hat, coat | wool coat, mittens", m="winter coat | knit sweater | santa hat | wool coat, scarf",
      light="string lights | warm lantern light | snow light | evening glow", mood="happy calm", surf="table:stall|floor:snow",
      detail="mulled wine | gingerbread | christmas tree | ornaments | wooden stalls | snowflakes", weather="clear cloudy overcast snow", times="afternoon evening night",
      acts=dict(solo="holding mulled wine | browsing stalls | catching snowflakes", pair="sharing mulled wine | ice skating | holding hands, market", groups="caroling | crowd, market"),
      zones=[
          Z("Stalls", "christmas market stalls | wooden huts, lights | market, christmas", "ornaments | candles | gingerbread", solo="browsing", pair="browsing together", groups="crowd"),
          Z("Big tree", "giant christmas tree | town square, tree | tree, lights", "tree | star | lights", solo="looking up, tree", pair="kiss, tree", groups="crowd, tree"),
          Z("Ice rink", "outdoor ice rink | skating rink, lights | rink, christmas", "skates | lights | snow", solo="ice skating", pair="skating together", groups="skaters"),
      ]),
    P("Christmas home", f="christmas sweater | santa dress | pajamas | red dress", m="christmas sweater | pajamas | santa costume | flannel",
      light="fireplace glow | christmas lights | candlelight | morning light", mood="happy calm", surf="floor:rug|chair:sofa|table:dining table",
      detail="christmas tree | presents | stockings | hot cocoa | cookies | snow outside", weather="clear cloudy overcast snow",
      acts=dict(solo="wrapping presents | decorating tree | hot cocoa", pair="opening presents | decorating, together | mistletoe kiss", groups="christmas dinner | gift exchange"),
      zones=[
          Z("Tree", "living room, christmas tree | decorated tree, presents | tree, lights", "ornaments | presents | lights", solo="hanging ornament", pair="tree, together", groups="presents", sky="view"),
          Z("Fireplace", "fireplace, stockings | hearth, christmas | fireside, garland", "stockings | fire | garland", solo="fire, cocoa", pair="blanket, fire", groups="fireside", sky="view"),
          Z("Dinner table", "christmas dinner table | dining room, turkey | festive table", "turkey | candles | crackers", solo="setting table", pair="dinner, together", groups="christmas dinner", sky="view"),
      ]),
    P("Halloween party", f="witch costume | vampire costume | cat costume | nurse costume, fake blood", m="vampire costume | zombie costume | pirate costume | grim reaper costume",
      light="jack-o'-lantern light | purple light | candlelight | moonlight", mood="playful tense", surf="floor:floor|chair:sofa|table:snack table",
      detail="jack-o'-lanterns | cobwebs | candy bowl | skeletons | bats | fog machine", times="evening night",
      acts=dict(solo="carving pumpkin | holding candy | posing, costume", pair="costume photo | scaring another | bobbing apples", groups="costume party | trick-or-treat"),
      zones=[
          Z("Living room", "halloween party, living room | decorated room, pumpkins | spooky party", "pumpkins | cobwebs | candy", solo="eating candy | witch hat, dancing", pair="dancing, costumes", groups="costume party", sky="view"),
          Z("Porch", "halloween porch | front porch, pumpkins | doorstep, decorations", "pumpkins | skeleton | candy bowl", solo="handing candy", pair="porch, together", groups="trick-or-treaters"),
          Z("Pumpkin patch", "pumpkin patch | field, pumpkins | farm, scarecrow", "pumpkins | scarecrow | hay", solo="picking pumpkin", pair="hayride", groups="pumpkin picking"),
      ]),
    P("Lunar new year", f="red qipao | ao dai, red | hanbok | red dress", m="red changshan | ao dai | hanbok | red shirt",
      light="red lanterns | fireworks | warm light | morning sun", mood="happy", surf="table:banquet table",
      detail="red lanterns | red envelopes | dragon dance | firecrackers | peach blossoms | dumplings",
      acts=dict(solo="holding red envelope | lighting incense | holding lantern", pair="exchanging red envelopes | making dumplings | watching fireworks", groups="dragon dance | reunion dinner"),
      zones=[
          Z("Street", "lunar new year street | lantern street | festival street, red", "lanterns | firecrackers | crowd", solo="walking, lanterns", pair="lanterns, together", groups="dragon dance"),
          Z("Temple", "temple, new year | incense, temple | pagoda, lanterns", "incense | lanterns | bells", solo="praying, incense", pair="praying together", groups="crowd, temple"),
          Z("Banquet", "new year banquet | reunion dinner | round table, feast", "dumplings | fish | tea", solo="making dumplings", pair="toast, banquet", groups="reunion dinner", sky="view"),
      ]),
    P("Cherry blossom", f="kimono | spring dress, cardigan | white blouse, skirt | trench coat", m="yukata | spring jacket | shirt, chinos | cardigan",
      light="spring sunlight | soft light | evening lanterns | golden hour", mood="happy calm", surf="floor:picnic blanket|chair:bench",
      detail="cherry blossoms | petals | picnic boxes | lanterns | river | sake", weather="clear cloudy overcast rain",
      acts=dict(solo="catching petals | looking up, blossoms | picnic", pair="hanami picnic | walking, blossoms | photo, blossoms", groups="hanami party"),
      zones=[
          Z("Park", "cherry blossom park | sakura trees | hanami park", "petals | blankets | crowds", solo="sitting, blanket", pair="hanami, together", groups="hanami party"),
          Z("River", "cherry blossom river | canal, sakura | riverside, blossoms", "petals on water | boats | bridge", solo="walking, river", pair="boat, blossoms", groups="crowd, river"),
          Z("Night lanterns", "yozakura | night blossoms, lanterns | sakura, lanterns", "lanterns | blossoms | stalls", solo="lanterns, blossoms", pair="night hanami", groups="crowd, lanterns"),
      ]),
    P("Summer festival", f="yukata, obi | yukata, hair ornament | jinbei | summer dress", m="yukata | jinbei | t-shirt | happi coat",
      light="lantern light | fireworks | evening glow | stall lights", mood="happy playful", surf="floor:shrine path",
      detail="fireworks | goldfish scooping | candy apple | paper fans | lanterns | festival stalls", times="evening night",
      acts=dict(solo="eating candy apple | goldfish scooping | holding fan", pair="watching fireworks | holding hands, festival | sharing takoyaki", groups="festival crowd"),
      zones=[
          Z("Stalls", "festival stalls | matsuri stalls | shrine festival", "stalls | lanterns | crowds", solo="buying food", pair="stalls, together", groups="crowd"),
          Z("Fireworks spot", "fireworks, riverside | hill, fireworks | fireworks viewing", "fireworks | river | crowd", solo="watching fireworks", pair="fireworks, together", groups="crowd, fireworks"),
          Z("Bon dance", "bon odori | dance, yagura | festival dance", "yagura | taiko | lanterns", solo="dancing", pair="dancing together", groups="circle dance"),
      ]),
    P("Autumn harvest", f="knit sweater, scarf | flannel shirt | corduroy skirt | cardigan, boots", m="flannel shirt | knit sweater | corduroy jacket | vest",
      light="golden autumn light | overcast | sunset | morning mist", mood="calm happy", surf="floor:leaves|chair:hay bale|table:harvest table",
      detail="falling leaves | pumpkins | apple cider | corn stalks | hay bales | scarecrow",
      acts=dict(solo="kicking leaves | drinking cider | carrying pumpkin", pair="leaf fight | hayride | cider, together", groups="harvest festival"),
      zones=[
          Z("Maple path", "autumn path, maples | red leaves, park | forest, autumn", "red leaves | path | bench", solo="walking, leaves", pair="walking together, leaves", groups="walking, leaves"),
          Z("Harvest fair", "harvest fair | autumn fair | festival, pumpkins", "pumpkins | pies | bunting", solo="eating pie", pair="fair, together", groups="crowd, fair"),
          Z("Harvest table", "harvest table, outdoors | long table, autumn | feast table", "pies | candles | leaves", solo="setting table", pair="dinner, together",
            groups="harvest feast"),
      ]),
    P("Valentine's date", f="red dress | pink dress | little black dress | lingerie, robe", m="suit | open shirt | blazer | sweater",
      light="candlelight | rose light | dim warm light | city lights", mood="calm sultry", surf="table:dinner table|bed:bed|chair:sofa",
      detail="roses | chocolates | heart balloons | wine | candles | love letter", times="evening night",
      acts=dict(solo="holding roses | reading love letter | waiting, table", pair="candlelit dinner | giving roses | slow dance", groups="double date"),
      zones=[
          Z("Restaurant", "romantic restaurant | candlelit table | dinner, roses", "roses | candles | wine", solo="checking watch | sipping wine", pair="dinner, together", groups="double date", sky="view"),
          Z("Bedroom", "valentine bedroom | rose petals, bed | bedroom, candles", "petals | chocolates | candles", solo="bed, petals", pair="bed, together", groups="bedroom, group", sky="view"),
          Z("Rooftop", "rooftop date | rooftop, candles | terrace, city lights", "candles | skyline | blanket", solo="rooftop, waiting", pair="rooftop, together", groups="rooftop, group"),
      ]),
    P("New Year's Eve", f="sequin dress | party dress, tiara | metallic dress | velvet dress", m="tuxedo | suit, bowtie | velvet blazer | party shirt",
      light="fireworks | countdown lights | sparklers | city lights", mood="happy playful", surf="floor:rooftop|wall:railing",
      detail="fireworks | champagne | confetti | party hats | sparklers | countdown clock", times="night",
      acts=dict(solo="holding sparkler | champagne | blowing noisemaker", pair="midnight kiss | toast | dancing, confetti", groups="countdown | crowd, fireworks"),
      zones=[
          Z("Rooftop", "rooftop party, fireworks | rooftop, countdown | terrace, skyline", "fireworks | skyline | champagne", solo="champagne, fireworks", pair="midnight kiss", groups="countdown"),
          Z("Ballroom", "new year ballroom | gala, balloons | party hall", "balloons | confetti | clock", solo="dancing", pair="dancing together", groups="gala crowd", sky="view"),
          Z("City square", "city square, countdown | crowd, fireworks | plaza, new year", "crowd | screens | fireworks", solo="crowd, cheering", pair="kiss, crowd", groups="crowd"),
      ]),
], "holiday illustration | film photography, festive | anime illustration, seasonal | cozy illustration", NSFW, "cowboy shot | full body | wide shot | from side")
