from lib import P, Z, theme

NSFW = "photorealistic, detailed skin | hentai, anime coloring | painterly, erotic illustration | candid photography"

theme("travel", "Travel", [
    P("Airport", f="travel outfit, sneakers | trench coat, scarf | hoodie, leggings | blazer, jeans", m="travel jacket, backpack | hoodie, joggers | suit, carry-on | denim jacket",
      light="daylight, terminal | fluorescent light | sunrise, runway | night, runway lights", mood="calm happy", surf="chair:gate seat|wall:glass wall|floor:terminal floor",
      detail="suitcases | boarding pass | departure board | planes outside | coffee cup | neck pillow",
      acts=dict(solo="pulling suitcase | checking boarding pass | sitting, gate | sleeping, neck pillow", pair="goodbye hug | waiting together, gate | running, late",
                groups="travel group | queue, check-in"),
      zones=[
          Z("Gate", "airport gate, window | departure gate, planes | gate seats, runway view", "airplane, window | gate sign | charging station | carry-on",
            solo="looking at planes | charging phone", pair="watching planes together", groups="waiting crowd", sky="view"),
          Z("Check-in", "check-in hall | airport terminal, counters | ticket counters", "luggage belt | passports | queue ropes | screens",
            solo="checking in | weighing luggage", pair="passports, together", groups="queue"),
          Z("Arrivals", "arrivals hall | airport exit, crowd | arrival gate", "welcome signs | flowers | crowd | taxi rank", solo="arriving, suitcase | looking for someone",
            pair="reunion hug | holding sign", groups="welcome crowd"),
      ]),
    P("Night train", f="sweater, long skirt | travel coat | pajamas | cardigan, jeans", m="sweater | travel coat | pajamas | flannel shirt",
      light="dim cabin light | passing station lights | moonlight, window | dawn, window", mood="calm melancholy", surf="bed:sleeper bunk|chair:seat|wall:window|table:fold-down table",
      detail="rattling rails | landscape blur | tea glass | ticket | curtains | passing lights",
      acts=dict(solo="looking out window | reading, bunk | writing postcard", pair="sharing tea | sitting across, window | talking, low voices", groups="cards game, compartment"),
      zones=[
          Z("Sleeper cabin", "sleeper compartment, bunks | train cabin, window | sleeping car", "bunk ladder | blankets | small lamp | luggage rack",
            solo="lying, bunk | sitting, bunk edge", pair="bunks, talking", groups="crowded compartment", sky="view"),
          Z("Dining car", "dining car | train restaurant car | dining carriage, window", "white tablecloth | wine glasses | menu | landscape", solo="eating, window | coffee, window",
            pair="dinner, dining car", groups="shared table", sky="view"),
          Z("Corridor", "train corridor, windows | carriage corridor | narrow corridor, train", "window rail | curtains | night landscape", solo="leaning, window rail | smoking, window",
            pair="passing close, corridor", groups="corridor, chatting", sky="view"),
      ]),
    P("Ferry crossing", f="windbreaker | sundress, cardigan | raincoat | sweater, jeans", m="windbreaker | jacket | raincoat | hoodie",
      light="sea light | sunset, sea | overcast, sea | morning sun, water", mood="calm happy", surf="wall:railing|chair:bench|floor:deck",
      detail="seagulls | wake, water | islands, distance | life rings | wind, hair | ferry horn",
      acts=dict(solo="leaning on railing | feeding seagulls | taking photo", pair="leaning on railing, together | sharing snacks | hair blowing, laughing", groups="tourists, deck"),
      zones=[
          Z("Bow", "ferry bow | ship bow, sea | front deck, ferry", "spray | horizon | ropes", solo="standing, bow, wind | arms spread", pair="bow, together", groups="crowd, bow"),
          Z("Stern", "ferry stern, wake | back deck, ferry | stern railing", "wake | seagulls | flag", solo="watching wake | sitting, bench", pair="watching wake, together", groups="stern, group"),
          Z("Cabin", "ferry cabin, windows | passenger lounge, ferry | seats, ferry", "rows of seats | snack bar | windows", solo="sleeping, seat | reading", pair="seats, together",
            groups="passengers", sky="view"),
      ]),
    P("Hostel", f="tank top, shorts | hoodie | backpacker outfit | t-shirt, jeans", m="tank top | hoodie | backpacker outfit | t-shirt",
      light="warm light | morning light | fairy lights | lamp light", mood="happy playful", surf="bed:bunk bed|chair:bean bag|table:kitchen table",
      detail="backpacks | maps | lockers | travel stickers | guitar | world map",
      acts=dict(solo="unpacking backpack | planning route, map | playing guitar", pair="sharing travel stories | cooking, hostel kitchen | swapping tips", groups="hostel party | dinner, strangers"),
      zones=[
          Z("Dorm", "hostel dorm, bunk beds | dorm room, lockers | shared room, bunks", "bunk curtains | lockers | backpacks", solo="lying, bunk | packing", pair="bunks, talking",
            groups="dorm, chatting", sky="view"),
          Z("Common room", "hostel common room | lounge, beanbags | hostel lounge", "beanbags | board games | books", solo="reading, beanbag | guitar", pair="board game",
            groups="common room, crowd", sky="view"),
          Z("Rooftop", "hostel rooftop | roof terrace, city | rooftop bar, hostel", "string lights | city | beers", solo="sitting, ledge | beer, sunset", pair="beers, rooftop",
            groups="rooftop party"),
      ]),
    P("Landmark", f="sundress, sun hat | t-shirt, shorts | trench coat | denim jacket, skirt", m="t-shirt, shorts | linen shirt | jacket | polo shirt",
      light="sunny day | golden hour | blue hour | overcast", mood="happy calm", surf="wall:stone wall|chair:steps",
      detail="tourists | cameras | souvenir stalls | maps | selfie stick | pigeons",
      acts=dict(solo="taking selfie | looking up, landmark | holding map", pair="selfie together | pointing, landmark | posing for photo", groups="tour group | group photo"),
      zones=[
          Z("Monument", "famous monument | landmark, plaza | historic monument", "statue | tourists | cobblestones", solo="posing, monument", pair="photo, monument", groups="tour, monument"),
          Z("Viewpoint", "viewpoint, city panorama | lookout, city | scenic overlook", "telescope viewer | railing | panorama", solo="looking at view", pair="view, together",
            groups="viewpoint, crowd"),
          Z("Souvenir street", "souvenir street | tourist street, shops | market lane, tourists", "postcards | magnets | hats", solo="buying souvenir", pair="trying hats",
            groups="shopping, tourists"),
      ]),
    P("Hot air balloon", f="jacket, scarf | sweater, jeans | coat | windbreaker", m="jacket | sweater | coat | windbreaker",
      light="sunrise | golden hour | morning mist | clear sky", mood="happy calm", surf="wall:basket rim",
      detail="balloons in sky | burner flame | valleys | fairy chimneys | morning haze | shadows on land", times="morning evening",
      acts=dict(solo="leaning over basket | looking at balloons | taking photo", pair="hug, basket | pointing, balloons | champagne, sky", groups="balloon basket, group"),
      zones=[
          Z("Basket", "hot air balloon basket | balloon, sky | basket, flying", "burner | ropes | sky", solo="holding rope", pair="basket, together", groups="crowded basket"),
          Z("Launch field", "balloon launch field | inflating balloons | field, balloons", "inflating balloon | crew | fans", solo="watching inflation", pair="watching, together",
            groups="crew, launch"),
          Z("Valley view", "valley, balloons | cappadocia, balloons | rock valley, sky", "rock chimneys | balloons | valley", solo="standing, cliff, balloons", pair="sunrise, balloons",
            groups="crowd, viewpoint"),
      ]),
    P("Cruise ship", f="sundress | cocktail dress | bikini, sarong | linen set", m="linen shirt | suit | swim trunks | polo shirt",
      light="ocean sunlight | sunset, sea | night, ship lights | golden hour", mood="happy calm", surf="water:ship pool|chair:deck chair|wall:railing|bed:cabin bed",
      detail="ocean | deck chairs | life boats | buffet | ship funnel | waves",
      acts=dict(solo="lounging, deck chair | leaning on railing | cocktail, sea view", pair="dancing, ship | dinner, ocean view | railing, together", groups="deck party | dinner, captain table"),
      zones=[
          Z("Pool deck", "cruise ship pool deck | ship pool, ocean | sun deck, cruise", "pool | loungers | waterslide", solo="sunbathing, deck", pair="pool, together", groups="pool party, ship"),
          Z("Balcony cabin", "cruise cabin balcony | balcony, ocean | stateroom balcony", "ocean | chairs | towels", solo="morning coffee, balcony", pair="balcony, together",
            groups="balcony, crowded"),
          Z("Grand atrium", "cruise ship atrium | grand staircase, ship | ship lobby", "chandelier | glass elevator | shops", solo="descending stairs", pair="dressed up, atrium",
            groups="crowd, atrium"),
      ]),
    P("Mountain homestay", f="wool sweater | ethnic dress | raincoat | flannel shirt", m="wool sweater | flannel shirt | raincoat | jacket",
      light="morning mist | golden hour | firelight | overcast", mood="calm happy", surf="floor:wooden floor|chair:stool|bed:floor mattress",
      detail="terraced hills | wooden house | wood stove | rice wine | water buffalo | mist, valley",
      acts=dict(solo="drinking tea, view | warming hands, fire | hiking, village", pair="dinner, host | tea, porch | walking, terraces", groups="dinner, homestay | dancing, fire"),
      zones=[
          Z("Stilt house", "stilt house interior | wooden house, fire | homestay room", "wood stove | mats | lanterns", solo="sitting, mats", pair="sharing meal", groups="dinner, mats",
            sky="view"),
          Z("Porch", "wooden porch, mountains | veranda, valley view | stilt house porch", "valley | mist | rice terraces", solo="sitting, porch", pair="porch, tea", groups="porch, group"),
          Z("Village path", "village path, mountains | mountain village | dirt road, village", "chickens | fences | fields", solo="walking, village",
            pair="walking together, village", groups="trekking group"),
      ]),
    P("Road trip", f="denim shorts, tank top | flannel, jeans | sundress | sunglasses, crop top", m="flannel shirt | t-shirt, jeans | denim jacket | tank top",
      light="golden hour | harsh sun | dusk | headlights", mood="happy calm", surf="chair:car seat|wall:car door|floor:car hood",
      detail="map | snacks | sunglasses | open road | road signs | camper van",
      acts=dict(solo="driving | feet on dashboard | hand out window", pair="singing, car | map reading | sitting on car hood", groups="road trip, van"),
      zones=[
          Z("Highway", "open highway | desert highway, car | coastal road, car", "road | horizon | car", solo="driving, sunglasses", pair="driving together", groups="van, highway"),
          Z("Rest stop", "rest stop | roadside stop | scenic pullout", "vending machine | picnic table | view", solo="stretching, rest stop", pair="snacks, rest stop",
            groups="picnic, rest stop"),
          Z("Camper van", "camper van, open doors | van life, campsite | van interior, view", "fairy lights | mattress | coffee", solo="coffee, van door", pair="lying, van, view",
            groups="campfire, van"),
      ]),
], "travel photography | film photography, travel | anime illustration, travel | watercolor, travel journal", NSFW, "cowboy shot | full body | wide shot | from behind")

theme("countryside", "Countryside", [
    P("Farmhouse", f="sundress, apron | flannel shirt, jeans | overalls | cardigan, long skirt", m="flannel shirt | overalls | work shirt, jeans | henley",
      light="morning light | golden hour | lamp light | overcast", mood="calm happy", surf="table:farm table|chair:chair|floor:wooden floor|bed:quilt bed",
      detail="fresh eggs | pie | mason jars | dried herbs | rooster | quilt",
      acts=dict(solo="baking pie | carrying basket | drinking coffee, porch", pair="breakfast together | canning jars | porch swing", groups="harvest dinner | kitchen, busy"),
      zones=[
          Z("Kitchen", "farmhouse kitchen | country kitchen, window | rustic kitchen", "wood stove | pie | jars", solo="kneading dough | cooking", pair="cooking together", groups="kitchen, group", sky="view"),
          Z("Porch", "farmhouse porch | porch swing, fields | front porch", "rocking chair | lemonade | dog", solo="sitting, porch swing", pair="porch swing, together", groups="porch, group"),
          Z("Bedroom", "farmhouse bedroom | quilt bed, window | country bedroom", "quilt | lace curtains | fields outside", solo="waking, quilt", pair="quilt, together",
            groups="bedroom, crowded", sky="view"),
      ]),
    P("Barn", f="overalls | flannel shirt | denim shorts, boots | work shirt", m="overalls | flannel shirt | work shirt, boots | tank top",
      light="light beams, barn | golden hour | lantern light | dusty light", mood="calm playful", surf="floor:hay|wall:barn wall|bed:hay bales",
      detail="hay bales | pitchfork | dust in light | horses | tractor | barn cat",
      acts=dict(solo="stacking hay | sitting, hay bale | climbing ladder", pair="hay fight | lying in hay | working together", groups="barn dance | hay rides"),
      zones=[
          Z("Hayloft", "hayloft | barn loft, hay | loft, open door", "hay | loft door | light beams", solo="lying, hay | sitting, loft door", pair="lying in hay, together",
            groups="hayloft, group", sky="view"),
          Z("Stalls", "barn stalls | horse stalls | stable, barn", "horses | saddles | buckets", solo="brushing horse", pair="feeding horses", groups="stable hands"),
          Z("Barn doors", "open barn doors, fields | barn entrance | barnyard", "tractor | chickens | fields", solo="leaning, barn door", pair="barn door, together", groups="barnyard, group"),
      ]),
    P("Orchard", f="sundress | gingham dress | overalls | cardigan, skirt", m="flannel shirt | overalls | work shirt | henley",
      light="dappled sunlight | golden hour | morning light | overcast", mood="happy calm", surf="floor:grass|chair:ladder",
      detail="apples | baskets | ladders | blossoms | bees | cider",
      acts=dict(solo="picking apples | biting apple | carrying basket", pair="picking together | apple, sharing | ladder, holding", groups="harvest, orchard"),
      zones=[
          Z("Apple rows", "apple orchard | orchard rows | fruit trees", "apples | ladders | baskets", solo="reaching, apple", pair="picking, ladder", groups="harvest"),
          Z("Blossom", "orchard blossom | cherry orchard, blossoms | blooming trees", "blossoms | petals | bees", solo="petals, wind", pair="walking, blossoms", groups="picnic, blossoms"),
          Z("Cider press", "cider press | orchard shed | press house", "press | barrels | jugs", solo="pressing apples", pair="tasting cider", groups="cider, group"),
      ]),
    P("Rice terraces", f="ao ba ba | conical hat, tunic | ethnic dress | t-shirt, rolled pants", m="conical hat | tunic | rolled pants, shirt | farmer clothes",
      light="morning mist | golden hour | overcast | sunbeam", mood="calm", surf="floor:paddy dike|water:paddy",
      detail="rice terraces | water buffalo | mist | reflections | bamboo | conical hats",
      acts=dict(solo="planting rice | walking, dike | carrying baskets, pole", pair="planting together | walking, terraces | resting, hut", groups="harvest, rice | farmers, field"),
      zones=[
          Z("Terraces", "rice terraces | terraced fields, mountains | rice paddies, slopes", "water terraces | green rice | mist", solo="standing, terraces", pair="walking, dike",
            groups="farmers"),
          Z("Paddy", "flooded paddy | rice field, water | paddy field", "seedlings | mud | reflection", solo="bending, seedlings | wiping sweat", pair="planting together", groups="planting line"),
          Z("Field hut", "bamboo hut, fields | field shelter | rest hut, paddies", "hammock | tea | bamboo", solo="resting, hammock", pair="resting together", groups="lunch, hut"),
      ]),
    P("Stable", f="riding outfit | equestrian jacket | flannel, jeans | cowgirl hat", m="riding outfit | cowboy hat | flannel, jeans | vest",
      light="morning light | golden hour | dusty light | lantern", mood="calm happy", surf="floor:hay|wall:stall door",
      detail="horses | saddles | bridles | horseshoes | hay | riding boots",
      acts=dict(solo="grooming horse | saddling horse | riding", pair="riding together | teaching riding | leading horse", groups="trail ride"),
      zones=[
          Z("Stalls", "horse stalls | stable aisle | stable interior", "horses | hay | buckets", solo="brushing horse", pair="feeding horse, together", groups="stable crew"),
          Z("Paddock", "paddock | horse paddock, fence | corral", "fence | horses | dust", solo="leaning, fence", pair="leading horse", groups="corral, group"),
          Z("Trail", "riding trail | trail, horseback | meadow trail", "horses | trees | meadow", solo="horseback riding", pair="riding, side by side", groups="trail ride"),
      ]),
    P("Country road", f="sundress | denim jacket | flannel | t-shirt, shorts", m="flannel shirt | t-shirt | denim jacket | work shirt",
      light="golden hour | sunny day | overcast | dusk", mood="calm happy", surf="floor:grass|wall:fence",
      detail="dirt road | wildflowers | fences | pickup truck | telephone poles | crows",
      acts=dict(solo="walking, road | riding bicycle | sitting, fence", pair="walking together | bicycle, together | sitting, truck bed", groups="walking, group"),
      zones=[
          Z("Dirt road", "dirt road, fields | country lane | gravel road", "dust | fields | fences", solo="kicking stones | hands in pockets, road", pair="walking, hand in hand", groups="walking, row"),
          Z("Truck bed", "pickup truck bed, fields | truck, roadside | truck bed, sunset", "blankets | cooler | radio", solo="sitting, truck bed", pair="truck bed, together", groups="truck, group"),
          Z("Bridge", "wooden bridge, creek | covered bridge | stone bridge, stream", "creek | bridge | trees", solo="leaning, bridge", pair="bridge, together", groups="bridge, group"),
      ]),
    P("Watermill", f="peasant dress | linen dress | apron, blouse | cardigan", m="linen shirt | vest | work clothes | apron",
      light="dappled light | morning light | golden hour | overcast", mood="calm", surf="floor:grass|water:millpond|wall:stone wall",
      detail="water wheel | millstone | flour sacks | ducks | willow | stream",
      acts=dict(solo="carrying flour sack | sitting, stream | feeding ducks", pair="fishing together | sitting, bank | walking, stream", groups="picnic, mill"),
      zones=[
          Z("Water wheel", "water wheel, stream | mill wheel | watermill", "wheel | splash | moss", solo="watching wheel", pair="wheel, together", groups="wheel, group"),
          Z("Mill interior", "mill interior | millstone room | flour mill", "millstones | sacks | dust", solo="grinding flour", pair="working, mill", groups="mill crew", sky="view"),
          Z("Millpond", "millpond | pond, willow | still pond", "ducks | willow | lilies", solo="fishing", pair="rowing, pond", groups="pond, group"),
      ]),
    P("Fishing village", f="striped shirt | raincoat | sundress | apron, rolled sleeves", m="fisherman sweater | raincoat | rolled sleeves | rubber boots",
      light="morning sun | sunset, harbor | overcast | fog", mood="calm happy", surf="floor:dock|wall:boat",
      detail="fishing boats | nets | crates | seagulls | lighthouse | buoys",
      acts=dict(solo="mending nets | carrying crate | sitting, dock", pair="unloading boat | fishing together | walking, harbor", groups="fish market | crew"),
      zones=[
          Z("Harbor", "fishing harbor | harbor, boats | small port", "boats | ropes | gulls", solo="tying rope", pair="boat, together", groups="crew, harbor"),
          Z("Fish market", "fish market, harbor | open-air fish market | dockside stalls", "fish crates | ice | scales", solo="selling fish", pair="bargaining", groups="crowd, market"),
          Z("Cottages", "fishermen cottages | seaside cottages | whitewashed houses", "laundry | flowers | cats", solo="hanging laundry", pair="doorstep, chatting", groups="neighbors"),
      ]),
    P("Vegetable farm", f="overalls | sun hat, dress | gardening gloves, jeans | t-shirt, shorts", m="overalls | sun hat | work clothes | tank top",
      light="sunny day | morning light | golden hour | overcast", mood="happy", surf="floor:soil",
      detail="vegetables | crates | watering cans | scarecrow | tractor | greenhouse",
      acts=dict(solo="harvesting vegetables | watering | carrying crate", pair="harvest together | washing vegetables | tractor ride", groups="harvest day"),
      zones=[
          Z("Rows", "vegetable rows | farm field | garden rows", "carrots | lettuce | soil", solo="pulling carrots", pair="harvest, rows", groups="harvest, rows"),
          Z("Greenhouse", "farm greenhouse | polytunnel | greenhouse, tomatoes", "tomatoes | humidity | vines", solo="picking tomatoes", pair="greenhouse, together", groups="greenhouse, crew",
            sky="view"),
          Z("Farm stand", "farm stand | roadside stand | produce stand, farm", "baskets | prices | pumpkins", solo="selling produce", pair="buying produce", groups="customers"),
      ]),
], "film photography, countryside | painterly, rural | studio ghibli style | watercolor, pastoral", NSFW, "full body | cowboy shot | wide shot | from behind")

theme("historical", "Historical", [
    P("Roman bath", f="stola | toga | palla, jewelry | linen tunic", m="toga | tunic | roman armor | himation",
      light="sunbeam, steam | torchlight | oil lamps | soft light", mood="calm", surf="water:bath|floor:mosaic floor|wall:column",
      detail="mosaics | steam | marble columns | oil flasks | strigil | statues",
      acts=dict(solo="bathing | oiling skin | lounging, marble", pair="massage, oil | bathing together | conversation, bath", groups="bathhouse crowd"),
      zones=[
          Z("Caldarium", "caldarium | hot bath, roman | steam bath, marble", "steam | marble | mosaic", solo="soaking", pair="soaking together", groups="bathers"),
          Z("Frigidarium", "frigidarium | cold pool, columns | roman pool", "columns | statues | cold water", solo="swimming", pair="pool, together", groups="pool, bathers", sky="view"),
          Z("Palaestra", "palaestra | bath courtyard | exercise yard, roman", "columns | sand | weights", solo="exercising", pair="wrestling", groups="athletes"),
      ]),
    P("Victorian London", f="victorian dress, bonnet | bustle dress | corset, gloves | shawl, long skirt", m="top hat, frock coat | waistcoat, pocket watch | newsboy cap | inverness coat",
      light="gaslight | fog | overcast | lamplight", mood="calm tense", surf="wall:brick wall|chair:bench",
      detail="gas lamps | carriages | fog | cobblestones | newspapers | chimneys",
      acts=dict(solo="walking, cane | reading newspaper | holding umbrella", pair="arm in arm | tipping hat | carriage ride", groups="crowd, street"),
      zones=[
          Z("Foggy street", "victorian street, fog | london street, gaslight | cobblestone street", "carriage | gas lamp | fog", solo="walking, fog", pair="walking together, fog", groups="crowd, fog"),
          Z("Tea room", "victorian tea room | parlor, tea | tea shop, lace", "tea set | cakes | lace", solo="pouring tea", pair="tea, together", groups="tea party", sky="view"),
          Z("Thames bridge", "bridge, thames | river, fog | embankment", "river | boats | fog", solo="leaning, bridge", pair="bridge, together", groups="crowd, bridge"),
      ]),
    P("Edo Japan", f="kimono | furisode | yukata | geisha outfit", m="hakama | samurai armor | yukata | kimono, haori",
      light="paper lantern light | morning mist | sunset | moonlight", mood="calm serious", surf="floor:tatami|wall:shoji|chair:engawa",
      detail="paper lanterns | wooden bridges | cherry trees | wooden signs | sake | katana",
      acts=dict(solo="holding umbrella | pouring sake | walking, geta", pair="tea ceremony | bowing | walking, bridge", groups="festival | procession"),
      zones=[
          Z("Street", "edo street | wooden shops, street | old japanese street", "shop curtains | lanterns | barrels", solo="walking, street", pair="street, together", groups="crowd, street"),
          Z("Teahouse", "edo teahouse | tatami, teahouse | tea room, shoji", "shoji | tea | screen", solo="serving tea", pair="tea, together", groups="guests, teahouse", sky="view"),
          Z("Castle", "japanese castle | castle grounds | castle gate", "stone walls | moat | gate", solo="standing, gate", pair="walking, castle", groups="samurai, castle"),
      ]),
    P("Speakeasy", f="flapper dress | sequin dress, headband | fur stole | beaded gown", m="pinstripe suit | fedora | suspenders | tuxedo",
      light="dim warm light | smoky light | spotlight | candlelight", mood="playful cool", surf="table:bar|chair:booth|wall:brick wall|floor:dance floor",
      detail="jazz band | cocktails | cigarette smoke | hidden door | poker chips | gramophone",
      acts=dict(solo="smoking, holder | drinking martini | dancing charleston", pair="dancing, charleston | whispering, booth | toast", groups="jazz crowd | card game"),
      zones=[
          Z("Bar", "speakeasy bar | hidden bar, bottles | 1920s bar", "bottles | bartender | smoke", solo="leaning, bar", pair="drinks, bar", groups="crowd, bar"),
          Z("Dance floor", "speakeasy dance floor | jazz floor | 1920s club", "band | feathers | lights", solo="dancing", pair="dancing together", groups="dancers"),
          Z("Back room", "back room, cards | gambling room | smoky room", "cards | chips | whiskey", solo="dealing cards", pair="poker", groups="poker game"),
      ]),
    P("Renaissance court", f="renaissance gown | corset, velvet | brocade dress | veil, jewels", m="doublet | renaissance clothes, cape | velvet coat | armor",
      light="candlelight | window light | sunbeam | torchlight", mood="calm serious", surf="chair:throne|floor:marble floor|bed:canopy bed",
      detail="frescoes | tapestries | lutes | goblets | portraits | chessboard",
      acts=dict(solo="playing lute | reading letter | posing, portrait", pair="dance, court | chess | secret letter", groups="court | banquet"),
      zones=[
          Z("Great hall", "renaissance hall | palazzo hall | frescoed hall", "frescoes | chandeliers | tapestries", solo="walking, hall", pair="dancing, hall", groups="court", sky="view"),
          Z("Painter's studio", "renaissance studio | painter studio, easel | artist workshop", "easel | pigments | canvas", solo="posing, painter", pair="painter, model", groups="workshop", sky="view"),
          Z("Garden", "renaissance garden | palazzo garden | villa garden, fountains", "fountains | hedges | statues", solo="walking, garden", pair="garden, together", groups="garden party"),
      ]),
    P("Wild west ranch", f="prairie dress | cowgirl hat, boots | ranch shirt, jeans | corset dress", m="cowboy hat | ranch shirt | chaps | duster",
      light="golden hour | harsh sun | sunset | campfire", mood="calm tense", surf="floor:dirt|wall:fence|chair:porch",
      detail="cattle | lasso | windmill | horse | barrel | cactus",
      acts=dict(solo="lasso throwing | riding horse | leaning, fence", pair="riding together | campfire, coffee | dancing, barn", groups="cattle drive | hoedown"),
      zones=[
          Z("Corral", "ranch corral | horse corral | cattle pen", "fence | horses | dust", solo="roping", pair="corral, together", groups="ranch hands"),
          Z("Ranch house", "ranch house porch | wooden porch, prairie | homestead", "rocking chair | lantern | prairie", solo="sitting, porch", pair="porch, together", groups="porch, group"),
          Z("Prairie", "prairie | open range | plains, cattle", "cattle | grass | horizon", solo="riding, prairie", pair="riding, side by side", groups="cattle drive"),
      ]),
    P("Belle epoque Paris", f="belle epoque gown | corset, parasol | lace dress | feathered hat", m="frock coat | top hat | waistcoat | boater hat",
      light="afternoon sun | gaslight | golden hour | rain, street", mood="happy calm", surf="table:cafe table|chair:bistro chair",
      detail="absinthe | posters | parasols | carriages | flower sellers | eiffel tower, distance",
      acts=dict(solo="holding parasol | drinking absinthe | painting", pair="cafe, together | strolling, arm in arm | dancing, cabaret", groups="cabaret | salon"),
      zones=[
          Z("Cafe", "belle epoque cafe | parisian cafe, terrace | bistro, posters", "absinthe | newspapers | chairs", solo="cafe, absinthe", pair="cafe, together", groups="crowd, cafe"),
          Z("Cabaret", "cabaret, stage | moulin rouge | music hall", "cancan dancers | stage | red curtains", solo="cancan", pair="dancing, cabaret", groups="cancan line"),
          Z("Boulevard", "paris boulevard | grand boulevard | avenue, trees", "trees | carriages | lamps", solo="strolling", pair="strolling, together", groups="crowd, boulevard"),
      ]),
    P("Chinese palace", f="hanfu | qipao | imperial robe | silk robe", m="hanfu | imperial robe | scholar robe | armor",
      light="lantern light | morning mist | sunset | moonlight", mood="calm serious", surf="floor:palace floor|chair:throne|water:lotus pond",
      detail="red lanterns | lotus | dragon carvings | silk screens | jade | incense",
      acts=dict(solo="playing guzheng | calligraphy | holding fan", pair="tea, pavilion | bowing | walking, gardens", groups="imperial court | banquet"),
      zones=[
          Z("Throne hall", "imperial throne hall | palace hall, dragons | forbidden city hall", "throne | pillars | dragons", solo="sitting, throne", pair="audience", groups="court", sky="view"),
          Z("Garden pavilion", "palace garden, pavilion | lotus pond, pavilion | chinese garden", "lotus | rocks | bridge", solo="sitting, pavilion", pair="pavilion, together", groups="garden, court"),
          Z("Courtyard", "palace courtyard | red walls, courtyard | imperial courtyard", "red walls | lanterns | stone lions", solo="walking, courtyard", pair="courtyard, together", groups="procession"),
      ]),
    P("Medieval village", f="peasant dress | kirtle, apron | cloak | linen dress", m="tunic | cloak | blacksmith apron | jerkin",
      light="morning light | overcast | torchlight | sunset", mood="calm happy", surf="floor:dirt|table:wooden table|bed:straw bed",
      detail="thatched roofs | chickens | well | market cart | smoke | church bell",
      acts=dict(solo="drawing water, well | carrying basket | milking goat", pair="market, bargaining | dancing, fair | walking, village", groups="village fair | market day"),
      zones=[
          Z("Village square", "medieval village square | well, square | market square", "well | carts | stalls", solo="drawing water", pair="market, together", groups="market day"),
          Z("Cottage", "medieval cottage | thatched cottage, hearth | peasant house", "hearth | pot | straw", solo="cooking, hearth", pair="hearth, together", groups="supper", sky="view"),
          Z("Fairground", "medieval fair | fairground, tents | festival, village", "tents | jugglers | banners", solo="juggling", pair="dancing, fair", groups="crowd, fair"),
      ]),
], "historical painting | oil painting, classical | cinematic still, period drama | engraving", NSFW, "full body | cowboy shot | wide shot | from side")

theme("apocalypse", "Post-apocalypse", [
    P("Ruined city", f="tattered jacket, cargo pants | scavenger outfit | gas mask, hoodie | leather armor", m="tattered jacket | scavenger outfit | gas mask | leather armor",
      light="dusty sunlight | overcast | sunset, haze | firelight", mood="tense melancholy", surf="floor:rubble|wall:ruined wall",
      detail="rubble | rusted cars | overgrown vines | broken windows | crows | debris",
      acts=dict(solo="scavenging | climbing rubble | aiming rifle", pair="covering another | sharing canned food | scouting together", groups="survivor group | patrol"),
      zones=[
          Z("Street", "ruined street | overgrown street, cars | collapsed city", "rusted cars | weeds | traffic lights", solo="walking, ruins", pair="walking, ruins, together", groups="patrol"),
          Z("Skyscraper", "ruined skyscraper floor | collapsed office, open wall | broken tower", "open wall | wind | city view", solo="looking out, broken wall", pair="lookout",
            groups="camp, tower", sky="out"),
          Z("Subway", "flooded subway | abandoned subway station | tunnel, ruins", "water | old train | darkness", solo="wading, tunnel", pair="flashlight, together", groups="group, tunnel"),
      ]),
    P("Wasteland road", f="dust goggles, scarf | leather jacket | cargo pants, tank top | poncho", m="dust goggles | leather jacket | poncho | armor plates",
      light="harsh sun | dust storm | sunset | heat haze", mood="tense", surf="floor:sand|wall:car",
      detail="dust | wrecked cars | skull | road signs | buzzards | heat haze", weather="clear cloudy",
      acts=dict(solo="driving | walking, wasteland | scanning horizon", pair="driving together | repairing car | sharing water", groups="convoy | raiders"),
      zones=[
          Z("Highway", "wasteland highway | broken road | desert road, wrecks", "wrecks | dust | road", solo="driving, dust", pair="car, together", groups="convoy"),
          Z("Gas station", "ruined gas station | wasteland gas station | abandoned station", "pumps | signs | barrels", solo="siphoning fuel", pair="trading", groups="raiders, station"),
          Z("Canyon", "wasteland canyon | dry canyon | rock canyon", "rocks | skulls | shade", solo="hiding, canyon", pair="camping, canyon", groups="camp, canyon"),
      ]),
    P("Survivor camp", f="patched clothes | flannel, jeans | jacket, boots | tank top, cargo pants", m="patched clothes | flannel | jacket | tank top",
      light="campfire | dusk | lantern light | morning", mood="calm tense", surf="floor:dirt|chair:crate|bed:cot",
      detail="tents | campfire | barricades | water barrels | radio | garden beds",
      acts=dict(solo="cooking, fire | keeping watch | repairing radio", pair="sharing meal | bandaging wound | guard duty", groups="camp meeting | campfire"),
      zones=[
          Z("Campfire", "survivor campfire | camp, fire | firepit, ruins", "fire | pot | crates", solo="cooking", pair="fire, together", groups="circle"),
          Z("Watchtower", "camp watchtower | lookout tower | barricade tower", "binoculars | rifle | wall", solo="binoculars, scanning | leaning, railing", pair="watch, together", groups="guards"),
          Z("Shelter", "survivor shelter | tent, cots | makeshift shelter", "cots | blankets | lanterns", solo="resting, cot", pair="cot, together", groups="shelter, crowded"),
      ]),
    P("Overgrown mall", f="scavenger outfit | hoodie | jacket, backpack | tattered dress", m="scavenger outfit | hoodie | jacket | vest",
      light="skylight, sunbeam | overgrown light | dim light | god rays", mood="melancholy calm", surf="floor:tiles|chair:fountain edge",
      detail="vines | broken escalators | mannequins | skylight | moss | dead fountain",
      acts=dict(solo="exploring | trying on clothes | sitting, fountain", pair="exploring together | shopping, ruins | dancing, empty mall", groups="scavenging party"),
      zones=[
          Z("Atrium", "overgrown mall atrium | mall, skylight | ruined atrium", "trees | skylight | vines", solo="standing, atrium", pair="atrium, together", groups="atrium, group", sky="view"),
          Z("Store", "abandoned store | ruined boutique | dusty shop", "mannequins | racks | dust", solo="trying clothes", pair="shopping, ruins", groups="looting"),
          Z("Food court", "abandoned food court | mall food court, vines | ruined food court", "tables | signs | plants", solo="sitting, table", pair="eating, ruins", groups="camp, food court", sky="view"),
      ]),
    P("Bunker", f="military fatigues | jumpsuit | tank top, cargo pants | hoodie", m="military fatigues | jumpsuit | tank top | hoodie",
      light="emergency light | fluorescent light | dim light | red light", mood="tense calm", surf="bed:bunk|table:metal table|wall:concrete wall",
      detail="canned food | radio | maps | bunk beds | air filter | blast door",
      acts=dict(solo="listening to radio | counting supplies | sleeping, bunk", pair="playing cards | planning, map | waiting, door", groups="bunker meeting"),
      zones=[
          Z("Bunks", "bunker bunks | bunk room | sleeping quarters, bunker", "bunks | lockers | lamp", solo="lying, bunk", pair="bunk, together", groups="crowded bunks"),
          Z("Control room", "bunker control room | radio room | monitors, bunker", "radio | monitors | maps", solo="radio", pair="radio, together", groups="meeting"),
          Z("Pantry", "bunker pantry | supply room | storage, cans", "cans | shelves | water", solo="counting cans", pair="supplies, together", groups="supplies, crowd"),
      ]),
    P("Flooded city", f="raincoat | waders, jacket | tank top, shorts | scavenger outfit", m="raincoat | waders | tank top | scavenger outfit",
      light="overcast | sunset, water | misty light | dawn", mood="melancholy calm", surf="water:flood water|floor:rooftop",
      detail="flooded streets | boats | submerged cars | rooftops | birds | reflections",
      acts=dict(solo="rowing boat | fishing, rooftop | wading", pair="rowing together | rooftop, together | swimming, ruins", groups="boat convoy"),
      zones=[
          Z("Canal street", "flooded street | city canals | water street", "boats | signs | buildings", solo="rowing", pair="boat, together", groups="boats"),
          Z("Rooftop", "rooftop, flood | rooftop garden, water | roof camp", "garden | tents | water", solo="fishing, roof", pair="roof, together", groups="rooftop camp"),
          Z("Drowned mall", "flooded mall | water, escalators | submerged lobby", "escalators | water | reflections", solo="wading, mall", pair="exploring, water", groups="divers", sky="view"),
      ]),
    P("Radio tower", f="climbing harness | jacket | scavenger outfit | cargo pants", m="climbing harness | jacket | scavenger outfit | cargo pants",
      light="sunset | stormy sky | night | dawn", mood="tense serious", surf="wall:tower frame|floor:platform",
      detail="antennas | wires | warning light | wind | broken dish | horizon",
      acts=dict(solo="climbing tower | repairing antenna | radio call", pair="climbing together | holding rope | watching horizon", groups="repair crew"),
      zones=[
          Z("Tower top", "radio tower top | antenna platform | tower, sky", "antennas | wind | clouds", solo="clinging to frame | wind, hair", pair="top, together", groups="crew, top"),
          Z("Radio shack", "radio shack | transmitter room | equipment room", "radios | static | headphones", solo="headphones, listening | tuning dial", pair="radio, together", groups="crew", sky="view"),
          Z("Base", "tower base, fence | perimeter, tower | compound, fence", "fence | generator | barrels", solo="guarding", pair="guard, together", groups="crew, base"),
      ]),
    P("Greenhouse colony", f="farmer clothes | overalls | linen dress | jumpsuit", m="farmer clothes | overalls | linen shirt | jumpsuit",
      light="diffused light | morning light | golden hour | grow lights", mood="calm happy", surf="floor:soil|table:potting bench",
      detail="crops | water tanks | solar panels | seedlings | patched glass | chickens",
      acts=dict(solo="planting | watering | harvesting", pair="planting together | sharing harvest | repairing glass", groups="harvest feast"),
      zones=[
          Z("Greenhouse", "colony greenhouse | patched greenhouse | glass dome farm", "seedlings | glass | vines", solo="tying vines | misting plants", pair="greenhouse, together", groups="farmers", sky="view"),
          Z("Solar field", "solar panel field | solar farm, ruins | panel rows", "panels | cables | grass", solo="cleaning panel", pair="repairing panel", groups="crew"),
          Z("Commons", "colony commons | long table, colony | shared hall", "long table | bread | lanterns", solo="setting table", pair="dinner, together", groups="feast", sky="view"),
      ]),
    P("Frozen wasteland", f="fur coat, goggles | parka | layered clothes | scarf, mittens", m="fur coat | parka | layered clothes | scarf",
      light="pale sun | blizzard light | overcast | aurora", mood="tense melancholy", surf="floor:snow|wall:ice wall",
      detail="snow drifts | frozen cars | icicles | breath vapor | sled | ruins under snow", weather="clear cloudy overcast snow",
      acts=dict(solo="trudging, snow | hunting | warming hands", pair="sharing blanket | pulling sled | huddled", groups="caravan, snow"),
      zones=[
          Z("Ice city", "frozen city | snow-buried street | ice ruins", "frozen cars | icicles | snow", solo="walking, snow", pair="walking, snow, together", groups="caravan"),
          Z("Shelter", "snow shelter | igloo | ice cave shelter", "fire | furs | ice", solo="warming, fire", pair="furs, together", groups="huddled"),
          Z("Frozen lake", "frozen lake, ruins | ice field | frozen river", "ice | cracks | fish hole", solo="ice fishing", pair="fishing together", groups="camp, ice"),
      ]),
], "post-apocalyptic, concept art | cinematic still, desaturated | anime illustration, ruins | gritty illustration", NSFW, "full body | wide shot | cowboy shot | from below", nonhuman="scifi")

theme("steampunk", "Steampunk", [
    P("Airship bridge", f="corset, goggles | aviator jacket | brass buttons, coat | steampunk dress", m="aviator jacket, goggles | captain coat | waistcoat, goggles | leather apron",
      light="sunset, clouds | brass lamps | morning light | storm light", mood="cool happy", surf="wall:helm|chair:captain chair|floor:deck",
      detail="brass instruments | propellers | clouds | maps | speaking tubes | telescope",
      acts=dict(solo="steering airship | looking through telescope | reading map", pair="navigating together | toasting, bridge | pointing, horizon", groups="crew, bridge"),
      zones=[
          Z("Helm", "airship helm | bridge, wheel | airship bridge", "wheel | gauges | windows", solo="steering", pair="helm, together", groups="crew", sky="view"),
          Z("Deck", "airship deck | gondola deck, clouds | balloon deck", "ropes | clouds | balloon", solo="standing, deck, wind", pair="deck, together", groups="crew, deck", sky="out"),
          Z("Cabin", "airship cabin | captain cabin, brass | stateroom, airship", "maps | brass lamps | porthole", solo="writing log", pair="cabin, together", groups="cabin, crowded", sky="view"),
      ]),
    P("Clockwork workshop", f="leather apron, goggles | corset, tool belt | work dress | blouse, rolled sleeves", m="leather apron | goggles, vest | work clothes | waistcoat",
      light="lamp light | sparks | window light | warm light", mood="serious happy", surf="table:workbench|chair:stool|floor:wooden floor",
      detail="gears | springs | clockwork | tools | blueprints | automaton",
      acts=dict(solo="tinkering | soldering | adjusting goggles", pair="building together | testing invention | blueprints", groups="workshop crew"),
      zones=[
          Z("Workbench", "clockwork workbench | inventor bench | gear workshop", "gears | tools | lamp", solo="magnifying glass, gears | oiling gears", pair="building", groups="crowded bench", sky="view"),
          Z("Automaton", "automaton workshop | clockwork robot | mechanical doll room", "automaton | wires | keys", solo="winding automaton", pair="testing automaton", groups="crowd, automaton"),
          Z("Forge", "steam forge | workshop forge | furnace room", "furnace | sparks | anvil", solo="hammering", pair="forging", groups="smiths"),
      ]),
    P("Steam train", f="traveling dress | corset, coat | gloves, hat | lace blouse", m="frock coat | conductor uniform | waistcoat | engineer overalls",
      light="steam, sunlight | lamp light | sunset | coal fire", mood="calm happy", surf="chair:velvet seat|wall:window|table:table",
      detail="steam | brass fittings | velvet seats | coal | tickets | landscape",
      acts=dict(solo="looking out window | reading | shoveling coal", pair="sitting across | dining, train | conductor, ticket", groups="passengers"),
      zones=[
          Z("Carriage", "steam train carriage | velvet compartment | first class carriage", "velvet | lamps | luggage", solo="sitting, window", pair="compartment, together", groups="passengers", sky="view"),
          Z("Engine", "locomotive cab | steam engine, firebox | engine cab", "firebox | gauges | coal", solo="pulling whistle | leaning out cab", pair="engine, together", groups="crew", sky="view"),
          Z("Platform", "steam station platform | station, steam | victorian platform", "steam | clock | luggage", solo="waiting, platform", pair="goodbye, platform", groups="crowd, platform"),
      ]),
    P("Brass laboratory", f="lab coat, goggles | corset, apron | blouse, gloves | scientist outfit", m="lab coat, goggles | apron, vest | scientist outfit | waistcoat",
      light="tesla coil glow | lamp light | green glow | lightning", mood="serious tense", surf="table:lab table|floor:stone floor",
      detail="tesla coil | test tubes | brass dials | sparks | bubbling liquids | electricity",
      acts=dict(solo="experimenting | pulling lever | holding test tube", pair="experiment together | sparks, startled | writing notes", groups="demonstration"),
      zones=[
          Z("Tesla coil", "tesla coil lab | lightning machine | electric lab", "arcs | coils | sparks", solo="arms raised, sparks | goggles down", pair="watching sparks", groups="audience"),
          Z("Chemistry", "alchemy bench | chemistry lab, brass | potion lab", "tubes | flasks | smoke", solo="mixing", pair="mixing together", groups="lab crew", sky="view"),
          Z("Observatory", "brass observatory | telescope dome | star room", "telescope | orrery | stars", solo="telescope", pair="stargazing", groups="lecture", sky="view"),
      ]),
    P("Sky dock", f="aviator outfit | corset, goggles | coat, scarf | trousers, boots", m="aviator jacket | dock worker | captain coat | goggles, vest",
      light="morning light | sunset | fog | lamp light", mood="happy calm", surf="floor:dock|wall:railing",
      detail="docked airships | cranes | crates | ropes | gulls | clouds below",
      acts=dict(solo="loading crates | watching airships | checking cargo", pair="farewell, dock | trading | boarding", groups="dock workers"),
      zones=[
          Z("Mooring", "airship mooring | sky dock | docking tower", "airships | ropes | clouds", solo="tying rope", pair="boarding", groups="crew"),
          Z("Cargo", "cargo dock | crates, dock | loading bay", "crates | cranes | nets", solo="loading", pair="loading together", groups="workers"),
          Z("Dock tavern", "dock tavern | sky pub | pilot bar", "mugs | maps | pilots", solo="drinking", pair="drinks, together", groups="pilots", sky="view"),
      ]),
    P("Clock tower", f="corset, coat | steampunk dress | goggles, gloves | blouse, skirt", m="frock coat | goggles | waistcoat | engineer outfit",
      light="light through clock face | sunset | moonlight | lamp light", mood="calm tense", surf="floor:gear platform|wall:clock face",
      detail="giant gears | clock face | pendulum | city below | pigeons | bell",
      acts=dict(solo="climbing gears | looking through clock face | repairing", pair="hiding, gears | looking at city | chase", groups="chase, tower"),
      zones=[
          Z("Clock face", "inside clock face | clock tower interior | behind clock", "clock hands | glass | city", solo="silhouette, clock", pair="clock, together", groups="clock, group", sky="view"),
          Z("Gear room", "gear room | clockwork interior | machinery, gears", "gears | chains | pendulum", solo="balancing, gear | dodging pendulum", pair="gears, together", groups="gears, group"),
          Z("Belfry", "clock tower belfry | bell, rooftops | tower top", "bell | rooftops | wind", solo="ringing bell", pair="belfry, together", groups="belfry, group", sky="out"),
      ]),
    P("Inventor mansion", f="steampunk gown | corset, lace | velvet dress | goggles, dress", m="velvet coat | waistcoat | smoking jacket | goggles, suit",
      light="gaslight | fireplace | window light | candlelight", mood="calm playful", surf="chair:armchair|table:desk|bed:canopy bed",
      detail="inventions | brass robot butler | bookshelves | globes | gramophone | maps",
      acts=dict(solo="reading, armchair | winding gramophone | sketching invention", pair="tea, robot butler | dancing, gramophone | showing invention", groups="soiree"),
      zones=[
          Z("Study", "inventor study | library, inventions | brass study", "books | globe | blueprints", solo="sketching", pair="study, together", groups="soiree, study", sky="view"),
          Z("Parlor", "steampunk parlor | parlor, gramophone | salon, brass", "gramophone | robot butler | tea", solo="tea", pair="dancing", groups="soiree", sky="view"),
          Z("Bedroom", "steampunk bedroom | brass bed | canopy bed, gears", "brass bed | lamps | clockwork", solo="lying, bed", pair="bed, together", groups="bedroom, group", sky="view"),
      ]),
    P("Steam factory", f="work dress, apron | overalls, goggles | corset, gloves | rolled sleeves", m="overalls | goggles | work clothes | apron",
      light="furnace glow | steam, light beams | lamp light | sparks", mood="serious tense", surf="floor:metal floor|wall:pipes",
      detail="pipes | steam | pistons | furnaces | conveyor | pressure gauges",
      acts=dict(solo="pulling lever | checking gauge | wiping sweat", pair="working together | shouting, noise | repairing pipe", groups="factory workers"),
      zones=[
          Z("Floor", "steam factory floor | pistons, factory | industrial hall", "pistons | steam | belts", solo="working machine", pair="working together", groups="workers", sky="view"),
          Z("Boiler", "boiler room | furnace room | steam boilers", "boilers | coal | fire", solo="shoveling coal", pair="boiler, together", groups="stokers"),
          Z("Catwalk", "factory catwalk | pipe catwalk | metal walkway, steam", "pipes | railing | steam", solo="walking, catwalk", pair="catwalk, together", groups="foremen", sky="view"),
      ]),
    P("Underground city", f="corset, goggles | steampunk dress | worker clothes | cloak", m="goggles, coat | worker clothes | cloak | waistcoat",
      light="gaslight | furnace glow | crystal light | lamp light", mood="calm tense", surf="floor:cobblestones|wall:stone wall",
      detail="steam vents | brass pipes | lanterns | elevators | crystals | market stalls",
      acts=dict(solo="walking, lantern | riding elevator | buying goods", pair="walking together | market, bargaining | elevator, together", groups="crowd, market"),
      zones=[
          Z("Market", "underground market | cavern market | steam market", "stalls | lanterns | crowds", solo="buying", pair="market, together", groups="crowd"),
          Z("Elevator", "brass elevator | cage elevator, cavern | lift shaft", "cage | chains | depth", solo="gripping cage | looking down, shaft", pair="elevator, together", groups="crowded elevator"),
          Z("Cavern street", "cavern street | underground street, gaslight | stone street, pipes", "pipes | lamps | steam", solo="walking", pair="walking, together", groups="crowd"),
      ]),
], "steampunk illustration | victorian sci-fi, concept art | oil painting, steampunk | sepia photography", NSFW, "full body | cowboy shot | wide shot | dutch angle", nonhuman="scifi")
