from lib import P, Z, theme

PHOTO = "photorealistic, skin texture, depth of field | cinematic still, film grain | anime illustration, clean lineart | 35mm film photography"
NSFW = "photorealistic, detailed skin | hentai, anime coloring | painterly, erotic illustration | fine art nude photography"

theme("portrait", "Portrait", [
    P("Window light", detail="dust particles | soft shadows | houseplants | linen texture | warm wood | morning haze", acts=dict(solo="looking at viewer, soft smile | tucking hair behind ear | hand on own cheek", pair="cheek to cheek | forehead to forehead | hug from behind", groups="group portrait, close | laughing together"),
      f="linen shirt | knit sweater | black turtleneck | white blouse, pearl earrings",
      m="white shirt | denim jacket | wool sweater | grey henley", light="soft window light | golden hour, sunbeam | overcast, diffused light | backlighting, rim light",
      mood="calm happy", surf="chair:armchair|wall:window|bed:daybed|floor:rug",
      zones=[
          Z("Armchair", "apartment, armchair, tall window | living room, window, sheer curtains | sunlit room, armchair, houseplants",
            "dust particles | potted plant, windowsill | coffee cup | open book | knit blanket | wooden floor | sleeping cat",
            solo="sitting in armchair, legs tucked | reading book | holding cup, looking outside | curled up, armchair | chin on hand",
            pair="sharing armchair | sitting on armrest | reading together | cheek to cheek",
            groups="group portrait, armchair | gathered around armchair | laughing together"),
          Z("Sheer curtains", "bedroom, sheer curtains, window | white curtains, breeze, window | curtain shadows, white wall",
            "curtains, wind | lace curtain shadow | fairy lights | dried flowers, vase | white sheets | morning haze",
            solo="peeking through curtains | holding curtain | standing by window, looking back | leaning on window frame",
            pair="hiding behind curtain | forehead to forehead, curtains | whispering, window",
            groups="posing by window | curtains, group portrait | sitting on windowsill"),
          Z("Windowsill", "window seat, cushions, city view | bay window, cushions | windowsill, rooftops view",
            "rain on window | steam on glass | mug, windowsill | succulents | city skyline | pigeons outside | notebook, pen",
            solo="sitting on windowsill, knees up | drawing on fogged glass | writing in notebook | looking outside, chin on knee",
            pair="sitting side by side, window | sharing headphones | pointing outside",
            groups="squeezed on window seat | looking outside together"),
      ]),
    P("Studio headshot", detail="catchlight | detailed eyes | skin texture | flyaway hair | sharp focus | bokeh", acts=dict(solo="looking at viewer | chin up, confident | hand on own neck", pair="cheek to cheek | arm around shoulder | side by side, serious", groups="group portrait, tiers | shoulder to shoulder"),
      f="black dress, pearl earrings | blazer, red lipstick | white shirt, slicked-back hair | turtleneck, gold hoops",
      m="suit, no necktie | black t-shirt | turtleneck, glasses | leather jacket", light="rembrandt lighting | softbox, fill light | split lighting | butterfly lighting",
      mood="serious cool", surf="chair:stool|wall:backdrop|floor:studio floor", camera="close-up | portrait | upper body | headshot",
      zones=[
          Z("Grey backdrop", "studio, grey backdrop | photo studio, seamless paper, grey | grey background, studio",
            "catchlight | skin texture | light stand | reflector | tethered laptop | flyaway hair",
            solo="looking at viewer | looking over shoulder | arms crossed | sitting on stool | hand on chin",
            pair="back-to-back, arms crossed | side by side, looking at viewer | shoulder to shoulder",
            groups="band portrait, standing in row | group portrait, seated and standing | v formation"),
          Z("Black backdrop", "studio, black background | dark studio, black backdrop | black background, low key",
            "rim light, hair | smoke, haze | shadow, half face | spotlight | dust in light",
            solo="face in shadow | turning head | eyes closed, chin up | hand on collar",
            pair="faces close, darkness | profile to profile | silhouette, rim light",
            groups="faces from darkness | staggered heads"),
          Z("Color gel wall", "studio, colored gel lighting | studio, pink and blue light | neon gel backdrop",
            "gel lights | teal and orange | colored shadows | glitter | lens flare",
            solo="looking at viewer, colored light | hand on face, gel light | head tilt, neon", pair="back-to-back, neon | split color, faces",
            groups="neon group shot | crowded frame, colored light", light="pink and blue lighting | red and cyan lighting | purple gel light"),
      ]),
    P("Golden field", detail="lens flare | warm haze | seeds in air | long shadows | swallows, sky | insects, sunlight", acts=dict(solo="spinning, skirt flare | looking at viewer, smile | hand shielding eyes", pair="spinning together | forehead to forehead, sunset | hug from behind", groups="holding hands, chain | walking toward viewer"),
      f="sundress, straw hat | white blouse, long skirt | linen dress | cardigan, jeans",
      m="linen shirt, rolled sleeves | denim jacket, white t-shirt | knit vest, shirt | henley, chinos",
      light="golden hour, backlighting | warm sunset glow | lens flare, sunset | blue hour", mood="happy calm", surf="floor:grass",
      zones=[
          Z("Wheat field", "wheat field, sunset | golden wheat, rolling hills | farmland, wheat, horizon",
            "lens flare | seeds in air | dragonflies | hay bales | dirt road | windmill, distance",
            solo="walking through field | hand brushing wheat | looking back | holding hat, wind | arms spread",
            pair="walking hand in hand | piggyback | running, laughing | lying in wheat",
            groups="running through field | sitting in circle | walking in line"),
          Z("Wildflower meadow", "flower field, meadow | wildflowers, poppies, meadow | meadow, daisies, hills",
            "butterflies | flower crown | picnic basket | dandelion seeds | bees | tall grass",
            solo="sitting in flowers | holding flowers | blowing dandelion | lying in grass", pair="making flower crowns | lying in grass, side by side | picnic",
            groups="picnic blanket, meadow | flower crown, group | lying in circle"),
          Z("Hilltop", "hilltop, sunset, valley view | grassy hill, lone tree | hill, sky, clouds",
            "lone tree | kite in sky | long shadows | birds, sky | valley, mist",
            solo="sitting under tree | standing on hill, wind | flying kite", pair="sitting under tree, shoulders touching | flying kite together",
            groups="watching sunset together | sitting on hill, row"),
      ]),
    P("Old library", detail="dust in light | old books | leather armchair | brass lamp | wooden shelves | parchment", acts=dict(solo="reading, glasses | holding book to chest | looking up from book", pair="reading over shoulder | whispering, library | passing note", groups="debate, books | quiet reading together"),
      f="cardigan, plaid skirt | tweed blazer, glasses | knit sweater, long skirt | wool coat, scarf",
      m="tweed jacket, glasses | cardigan, oxford shirt | waistcoat, rolled sleeves | turtleneck, blazer",
      light="lamp light | dusty sunbeam | candlelight | soft window light", mood="calm serious", surf="chair:leather chair|table:reading table|wall:bookshelf|floor:rug",
      zones=[
          Z("Reading nook", "library, reading nook, armchair | library interior, window nook | bookstore, cozy corner",
            "stacked books | reading glasses | tea cup | dust particles | old map | candle",
            solo="reading book | book on lap, looking up | turning page | sleeping on book", pair="reading together | whispering, books | sharing book",
            groups="reading circle | arguing over book"),
          Z("Rolling ladder", "library, rolling ladder, tall shelves | bookshelves, ladder, high ceiling | grand library, balcony",
            "rolling ladder | leather spines | brass rail | dust | globe",
            solo="climbing ladder | reaching for book | sitting on ladder, reading", pair="handing book up | holding ladder",
            groups="searching shelves | passing books"),
          Z("Desk lamp", "library, desk, green lamp | study table, lamp, books | archive room, desk",
            "green desk lamp | handwritten notes | fountain pen | magnifying glass | old letters | ink bottle",
            solo="writing, fountain pen | studying, desk | leaning over desk | head on arms, desk", pair="studying together | pointing at page",
            groups="study group, desk | huddled over notes"),
      ]),
    P("Rainy city", detail="rain | wet hair | neon reflections | bokeh, headlights | umbrella | puddles", acts=dict(solo="holding umbrella | looking up, rain | hood up", pair="sharing umbrella | hug, rain | holding hands, rain", groups="running, rain | umbrellas, crowd"),
      f="trench coat | raincoat, rain boots | wool coat, scarf | oversized hoodie",
      m="trench coat | rain jacket | wool coat, turtleneck | bomber jacket", light="streetlight, wet reflections | neon lights, rain | overcast, rain | night, bokeh",
      mood="melancholy calm", surf="wall:wall",
      zones=[
          Z("Bus stop", "bus stop, rain, night | bus shelter, city street | street, rain, puddles",
            "rain | puddles | bus timetable | headlights, bokeh | umbrella",
            solo="waiting, bus stop | holding umbrella | looking up, rain | hands in pockets", pair="sharing umbrella | waiting together, bus stop",
            groups="crowded bus stop | umbrellas, group"),
          Z("Cafe window", "cafe window, rain outside | cafe, rainy window | coffee shop, night, rain",
            "raindrops on glass | steam, coffee | reflection, window | neon reflection | condensation",
            solo="looking out window, rain | writing on fogged glass | holding cup", pair="sitting across table, rain | talking, cafe",
            groups="crowded table, rain"),
          Z("Crosswalk", "crosswalk, neon, rain | city intersection, rain, night | shibuya crossing, rain",
            "neon signs | wet asphalt | traffic light | crowd, umbrellas | taxi",
            solo="walking, umbrella | crossing street | looking back, crosswalk", pair="running in rain, holding hands | umbrella, close together",
            groups="crossing street together | umbrellas, crowd"),
      ]),
    P("Greenhouse", detail="humid glass | hanging ferns | terracotta pots | watering can | garden gloves | butterflies", acts=dict(solo="holding potted plant | smelling flower | looking at viewer, plants", pair="laughing, plants | handing flower, another | watering plants, together", groups="tending plants together | greenhouse tour"),
      f="floral dress | gardening apron, rolled sleeves | linen jumpsuit | white sundress",
      m="linen shirt | work apron, shirt | cardigan, linen pants | rolled sleeves, suspenders", light="diffused light, greenhouse | dappled light | morning sun, glass roof | humid haze",
      mood="calm happy", surf="table:potting bench|floor:stone floor|chair:wicker chair",
      zones=[
          Z("Fern aisle", "greenhouse, ferns, glass roof | conservatory, ferns, palms | greenhouse aisle, plants",
            "ferns | condensation, glass | hanging plants | watering can | moss", solo="watering plants | touching leaf | walking, ferns",
            pair="walking together, plants | pointing at plant", groups="tour, greenhouse | watering together"),
          Z("Orchid bench", "greenhouse, potting bench, orchids | potting shed, flowers | orchid house",
            "orchids | terracotta pots | soil, trowel | seed packets | glass jars", solo="potting plant | smelling flower | sitting on bench",
            pair="repotting together | handing flower", groups="potting together | sharing tools"),
          Z("Glass doorway", "greenhouse door, garden | conservatory doorway, sunlight | glass door, garden path",
            "climbing roses | open door | garden path | wheelbarrow | sunlight, glass", solo="leaning in doorway | stepping outside | holding basket",
            pair="standing in doorway, talking | basket, flowers", groups="arriving, garden | group portrait, doorway"),
      ]),
    P("Seaside cliffs", detail="sea spray | seagulls | wind, hair | grass, wind | waves | distant ship", acts=dict(solo="hair blowing, wind | looking at sea | arms spread, wind", pair="hug, wind | walking, hand in hand | forehead to forehead, wind", groups="group, wind | looking at sea together"),
      f="white dress, wind | knit sweater, jeans | raincoat | sundress, cardigan",
      m="fisherman sweater | linen shirt, open collar | windbreaker | peacoat", light="overcast, sea light | golden hour, coast | storm light | morning fog",
      mood="calm melancholy", surf="floor:grass|wall:stone wall",
      zones=[
          Z("Cliff edge", "cliff, ocean, wind | sea cliff, grass, horizon | cliffside, waves below",
            "waves crashing | seagulls | wind, hair | sea spray | wildflowers, cliff", solo="standing at cliff edge, wind | sitting, legs dangling | hair blowing",
            pair="holding hands, cliff | sitting together, ocean view", groups="standing in row, ocean | looking at sea together"),
          Z("Rocky shore", "rocky beach, tide pools | pebble beach, waves | shoreline, rocks, mist",
            "tide pools | seaweed | driftwood | smooth stones | foam", solo="sitting on rock | wading, barefoot | collecting shells",
            pair="skipping stones | sitting on rocks", groups="exploring tide pools | bonfire, beach"),
          Z("Lighthouse path", "lighthouse, path, coast | lighthouse, cliff, sunset | coastal trail, lighthouse",
            "lighthouse | stone wall | wooden fence | sheep, distance | beam of light", solo="walking on path | leaning on fence | looking at lighthouse",
            pair="walking together, path | arm in arm", groups="hiking, coast | walking in line"),
      ]),
    P("Vintage parlor", detail="velvet | gilded frames | antique clock | lace | tea cups | ferns in pots", acts=dict(solo="sitting upright, elegant | holding teacup | looking at viewer, gloves", pair="arm in arm | hand kiss | sitting close, sofa", groups="parlor gathering | formal group portrait"),
      f="velvet dress | lace blouse, long skirt | 1920s dress, pearls | silk blouse, high-waist skirt",
      m="three-piece suit | smoking jacket | waistcoat, pocket watch | tuxedo", light="firelight | warm lamp light | candlelight | soft window light",
      mood="calm cool", surf="chair:velvet sofa|wall:wallpaper|floor:persian rug|table:side table",
      zones=[
          Z("Velvet sofa", "parlor, velvet sofa | victorian parlor, sofa | antique living room, chaise",
            "velvet cushions | tea set | lace doilies | antique clock | potted palm", solo="lounging on sofa | sitting upright, hands on lap | reclining, chaise",
            pair="sitting on sofa, close | pouring tea | head on shoulder", groups="tea party, parlor | group portrait, sofa"),
          Z("Fireplace", "parlor, fireplace | fireplace, mantel, portraits | drawing room, fire",
            "fire | mantel clock | candelabra | oil portraits | brass poker", solo="warming hands, fire | leaning on mantel | sitting by fire",
            pair="standing by fireplace, talking | toasting, glasses", groups="gathered by fire | cards game, fireplace"),
          Z("Gilded mirror", "parlor, gilded mirror | antique mirror, vanity | dressing room, mirror",
            "gilded frame | perfume bottles | hairbrush | jewelry box | reflection", solo="looking in mirror | fixing hair | putting on earrings",
            pair="fixing necktie | reflection, both", groups="checking reflection together"),
      ]),
    P("Rooftop dusk", detail="city lights | antennas | evening sky | pigeons | wind | rooftop gravel", acts=dict(solo="looking at city | sitting, knees up | hair blowing, wind", pair="sitting close, skyline | sharing earphones | leaning on shoulder", groups="hanging out, rooftop | toasting, sunset"),
      f="slip dress, jacket | crop top, wide pants | oversized shirt | denim jacket, skirt",
      m="bomber jacket | white t-shirt, jeans | open shirt, chain | hoodie", light="dusk, city lights | blue hour | string lights | sunset glow",
      mood="calm cool", surf="wall:parapet|floor:rooftop|chair:deck chair",
      zones=[
          Z("Water tower", "rooftop, water tower | rooftop, city skyline | roof, antennas, dusk",
            "water tower | antennas | pigeons | city lights | airplane trail", solo="sitting on ledge | leaning on railing | looking at city",
            pair="sitting on ledge, together | sharing cigarette | pointing at skyline", groups="hanging out, rooftop | sitting on ledge, row"),
          Z("Parapet", "rooftop parapet, skyline | building edge, city view | rooftop, sunset, city",
            "skyline | wind | traffic below | neon signs, distance", solo="leaning on parapet | arms on railing, chin down | standing, wind",
            pair="leaning on parapet, close | shoulder to shoulder", groups="leaning on railing, row"),
          Z("String-light terrace", "rooftop terrace, string lights | rooftop garden, fairy lights | terrace, plants, lanterns",
            "string lights | potted plants | wine glasses | candles | blankets", solo="sitting under lights | holding glass", pair="toasting | slow dancing",
            groups="rooftop party | toasting together"),
      ]),
], PHOTO, NSFW, "upper body | portrait | cowboy shot | close-up")
