from lib import P, Z, theme

NSFW = "photorealistic, detailed skin | hentai, anime coloring | painterly, erotic illustration | soft focus photography"
HOME_STYLES = "cozy illustration | photorealistic, warm tones | anime illustration, slice of life | film photography, home"

theme("kitchen", "Kitchen", [
    P("Morning kitchen", f="oversized shirt | pajamas | apron, t-shirt | camisole, shorts", m="t-shirt, sweatpants | pajamas | apron, t-shirt | henley shirt",
      light="morning sunlight | sunbeam, window | soft window light | overcast morning", mood="calm happy", surf="table:kitchen counter|wall:fridge|floor:tiled floor|chair:bar stool",
      detail="coffee maker | toast | frying pan | eggs | orange juice | steam",
      acts=dict(solo="making coffee | cracking egg | flipping pancake", pair="cooking together | feeding another | hug from behind, stove", groups="family breakfast | busy kitchen"),
      zones=[
          Z("Stove", "kitchen stove, morning | gas stove, pan | cooking range", "frying pan | bacon | steam", solo="frying eggs | stirring pot", pair="hug from behind, cooking",
            groups="crowded stove"),
          Z("Counter", "kitchen counter, sunlight | marble countertop | kitchen island", "cutting board | fruit bowl | coffee mugs", solo="chopping vegetables | sitting on counter",
            pair="sitting on counter, coffee", groups="breakfast, island"),
          Z("Window sink", "kitchen sink, window | sink, morning light | window, herbs", "herbs | dish rack | soap bubbles", solo="washing dishes | watering herbs",
            pair="washing dishes together", groups="dishes, group"),
      ]),
    P("Farmhouse kitchen", f="gingham dress, apron | flannel shirt, jeans | sundress, apron | knit cardigan", m="flannel shirt | overalls | henley shirt, apron | suspenders, shirt",
      light="warm window light | afternoon sun | lantern light | golden hour", mood="happy calm", surf="table:farmhouse table|chair:wooden bench|floor:wooden floor|wall:wooden wall",
      detail="cast iron pan | mason jars | dried herbs | wood stove | pie | copper pots",
      acts=dict(solo="kneading dough | canning jars | rolling pie crust", pair="baking together | flour fight | tasting sauce", groups="harvest dinner | family table"),
      zones=[
          Z("Wood stove", "wood stove, farmhouse | cast iron stove | rustic kitchen, stove", "kettle | firewood | cast iron", solo="stoking fire | stirring stew",
            pair="warming hands, stove", groups="gathered, stove"),
          Z("Long table", "farmhouse table | rustic dining table | long wooden table", "bread | pies | jam jars", solo="setting table | slicing bread", pair="sharing pie",
            groups="family dinner"),
          Z("Pantry", "farmhouse pantry | pantry shelves | larder", "mason jars | flour sacks | onions", solo="reaching shelf | counting jars", pair="hiding, pantry",
            groups="stocking pantry"),
      ]),
    P("Modern kitchen", f="silk blouse, slacks | knit dress | apron, tank top | sweater dress", m="black t-shirt | apron, rolled sleeves | turtleneck | dress shirt, rolled sleeves",
      light="pendant lights | under-cabinet lighting | daylight, minimalist | evening light", mood="calm cool", surf="table:kitchen island|chair:bar stool|wall:glass wall|floor:concrete floor",
      detail="stainless steel | espresso machine | wine glasses | minimalist | induction stove | knife block",
      acts=dict(solo="pouring wine | plating dish | espresso machine", pair="wine, island | cooking date | plating together", groups="dinner party prep | cocktails, island"),
      zones=[
          Z("Island", "kitchen island, pendant lights | marble island | modern kitchen island", "wine glasses | cheese board | bar stools", solo="leaning on island | sitting, bar stool",
            pair="wine, island", groups="cocktails, island"),
          Z("Espresso bar", "espresso machine | coffee bar, kitchen | modern kitchen, espresso", "espresso | milk jug | cups", solo="pulling espresso | latte art", pair="espresso, together",
            groups="coffee round"),
          Z("Glass wall", "kitchen, glass wall | modern kitchen, city view | kitchen, floor-to-ceiling window", "city view | plants | reflections", solo="looking outside, coffee",
            pair="window, wine", groups="view, group"),
      ]),
    P("Tiny apartment kitchen", f="oversized hoodie | t-shirt, shorts | tank top, pajama pants | cardigan", m="hoodie | t-shirt | tank top, sweatpants | flannel shirt",
      light="fluorescent light | window light | warm bulb | night, lamp", mood="calm playful", surf="table:small counter|wall:fridge|floor:kitchen floor|chair:stool",
      detail="instant noodles | rice cooker | sticky notes | magnets | dish pile | kettle",
      acts=dict(solo="cooking noodles | eating from pot | kettle boiling", pair="cramped kitchen | bumping hips | sharing noodles", groups="crowded kitchen"),
      zones=[
          Z("Two-burner stove", "small stove | tiny kitchen | studio apartment kitchen", "pot | noodles | steam", solo="boiling noodles | stirring pot", pair="cooking, shoulder to shoulder",
            groups="crowded stove"),
          Z("Fridge", "fridge, magnets | open fridge | fridge door, notes", "magnets | photos | takeout boxes", solo="looking in fridge | drinking from bottle", pair="fridge, peeking",
            groups="fridge raid"),
          Z("Window ledge", "kitchen window ledge | small window, kitchen | window, plants", "basil | herbs | cat", solo="eating, window | watering basil", pair="window, noodles",
            groups="window, snacks"),
      ]),
    P("Baking day", f="apron, sundress | apron, sweater | apron, t-shirt | apron, blouse", m="apron, t-shirt | apron, henley shirt | apron, shirt | apron, sweater",
      light="warm kitchen light | afternoon sun | oven glow | soft window light", mood="happy playful", surf="table:floured counter|floor:kitchen floor|wall:oven|chair:stool",
      detail="flour | rolling pin | cookies | mixing bowl | cake | sprinkles",
      acts=dict(solo="whisking | frosting cake | flour on face", pair="flour fight | licking spoon | decorating cake", groups="cookie decorating | bake sale prep"),
      zones=[
          Z("Floured counter", "floured counter | baking counter | kitchen, dough", "dough | flour | rolling pin", solo="rolling dough | kneading dough", pair="flour fight",
            groups="cookie cutters, group"),
          Z("Oven", "oven, baking | open oven | kitchen, oven glow", "baking tray | oven mitts | cookies", solo="taking tray out | peeking in oven", pair="tasting cookies",
            groups="waiting, oven"),
          Z("Cooling rack", "cooling rack, cake | cake stand | kitchen table, cakes", "frosting | cupcakes | sprinkles", solo="frosting cake | piping", pair="decorating cake",
            groups="cupcake party"),
      ]),
    P("Dinner party prep", f="cocktail dress, apron | blouse, skirt | wrap dress | little black dress", m="dress shirt, apron | vest, shirt | suit, rolled sleeves | turtleneck",
      light="warm pendant lights | candlelight | evening light | dim warm light", mood="happy serious", surf="table:counter|wall:wine rack|floor:tiled floor|chair:bar stool",
      detail="roast | wine bottles | candles | serving platters | herbs | timer",
      acts=dict(solo="plating dish | tasting sauce | opening wine", pair="tasting sauce, another | toasting | rushing, kitchen", groups="cooking together, group | toast, kitchen"),
      zones=[
          Z("Plating", "plating station | kitchen counter, platters | serving counter", "platters | garnish | tweezers", solo="plating | garnishing", pair="plating together",
            groups="plating line"),
          Z("Wine rack", "wine rack, kitchen | kitchen, wine bottles | wine corner", "wine bottles | corkscrew | glasses", solo="opening wine | pouring wine", pair="toast, wine",
            groups="toast, group"),
          Z("Oven roast", "oven, roast | roasting pan | kitchen, oven", "roast chicken | rosemary | steam", solo="basting roast | checking oven", pair="carrying platter",
            groups="gathered, roast"),
      ]),
    P("Rainy kitchen", f="knit sweater | oversized cardigan | flannel pajamas | hoodie", m="knit sweater | hoodie | flannel shirt | thermal shirt",
      light="rainy window light | lamp light | candlelight | overcast", mood="calm melancholy", surf="table:kitchen table|chair:kitchen chair|wall:window|floor:floor",
      detail="rain on window | tea kettle | soup pot | candles | blanket | steam",
      acts=dict(solo="drinking tea | stirring soup | watching rain", pair="soup, together | tea, window | slow dance, kitchen", groups="soup night"),
      zones=[
          Z("Rain window", "kitchen window, rain | rain, glass | window, raindrops", "raindrops | fog | plants", solo="watching rain, tea | drawing on fog", pair="rain, together",
            groups="rain, window, group"),
          Z("Soup pot", "kitchen stove, soup | pot, steam | stove, rain", "ladle | steam | bread", solo="stirring soup | tasting soup", pair="feeding soup, another",
            groups="soup, bowls"),
          Z("Kitchen table", "kitchen table, candles | small table, kitchen | breakfast nook", "candles | tea cups | blanket", solo="reading, table | journaling", pair="tea, table",
            groups="card game, table"),
      ]),
    P("Outdoor kitchen", f="sundress | crop top, shorts | linen shirt, shorts | bikini, sarong", m="linen shirt | t-shirt, shorts | tank top | apron, shirtless",
      light="sunny day | golden hour | string lights | sunset", mood="happy playful", surf="table:outdoor counter|chair:patio chair|floor:patio|wall:stone wall",
      detail="grill | pizza oven | string lights | lemons | herbs | smoke",
      acts=dict(solo="grilling | pizza oven | squeezing lemons", pair="grilling together | cocktails, outdoor | tasting, grill", groups="backyard barbecue | pizza night"),
      zones=[
          Z("Grill", "outdoor grill | backyard grill | patio, barbecue", "skewers | smoke | tongs", solo="flipping burgers | grilling skewers", pair="grilling together",
            groups="barbecue, group"),
          Z("Pizza oven", "outdoor pizza oven | brick oven, garden | wood-fired oven, patio", "pizza peel | flames | dough", solo="sliding pizza | tossing dough", pair="pizza, together",
            groups="pizza night"),
          Z("Bar counter", "outdoor bar | patio counter | outdoor kitchen, stone", "cocktails | lemons | ice", solo="mixing drinks | cutting lemons", pair="cocktails, counter",
            groups="drinks, counter"),
      ]),
    P("Diner kitchen", f="waitress uniform, apron | t-shirt, apron | cook uniform | tank top, bandana", m="cook uniform | t-shirt, apron | tank top, bandana | paper hat, apron",
      light="fluorescent light | neon outside | heat lamp | night", mood="serious playful", surf="table:steel counter|wall:order window|floor:tiled floor",
      detail="flat-top grill | order tickets | heat lamp | fryer | ketchup bottles | grease",
      acts=dict(solo="flipping burgers | ringing bell | wiping counter", pair="short order, together | arguing, kitchen | taking break", groups="dinner rush"),
      zones=[
          Z("Flat-top", "flat-top grill | diner grill | short order kitchen", "burgers | spatula | smoke", solo="flipping burgers | scraping grill", pair="cooking side by side",
            groups="rush, grill"),
          Z("Order window", "order window, diner | pass, heat lamp | ticket rail", "order tickets | bell | plates", solo="ringing bell | reading tickets", pair="passing plates",
            groups="rush, window"),
          Z("Back door", "kitchen back door, alley | back door, diner | loading door, night", "crates | cigarette | trash cans", solo="smoking break | sitting, crate",
            pair="break, together", groups="break, group"),
      ]),
], HOME_STYLES, NSFW, "upper body | cowboy shot | full body | from side")

theme("livingroom", "Living room", [
    P("Cozy living room", f="oversized sweater | pajamas | t-shirt, shorts | cardigan, leggings", m="hoodie | t-shirt, sweatpants | pajamas | flannel shirt",
      light="lamp light | afternoon sun | tv glow | warm light", mood="calm happy", surf="chair:sofa|floor:rug|table:coffee table|wall:wall",
      detail="throw pillows | knitted blanket | houseplants | coffee mug | remote | candles",
      acts=dict(solo="lying on sofa | reading, sofa | hugging pillow", pair="cuddling, sofa | watching tv together | pillow fight", groups="movie night | board game"),
      zones=[
          Z("Sectional", "sectional sofa | l-shaped couch | cozy couch", "blanket | pillows | popcorn", solo="curled up, sofa | napping, sofa", pair="head on lap, sofa",
            groups="crowded sofa"),
          Z("Rug", "living room rug | shag rug | floor cushions", "floor cushions | board game | tea", solo="lying on rug | stretching, rug", pair="board game, rug",
            groups="sitting in circle, rug"),
          Z("Window nook", "window nook, living room | bay window | window bench", "cushions | rain | books", solo="reading, window seat | looking outside", pair="window seat, together",
            groups="window, group"),
      ]),
    P("Movie night", f="pajamas | hoodie, shorts | oversized t-shirt | onesie", m="hoodie | pajamas | t-shirt, sweatpants | onesie",
      light="tv glow | projector light | dim room | screen light", mood="happy tense", surf="chair:couch|floor:blanket fort|table:coffee table",
      detail="popcorn bowl | soda | remote | blanket | candy | projector",
      acts=dict(solo="eating popcorn | hiding behind pillow | holding remote", pair="cuddling, movie | scared, hugging | sharing popcorn", groups="movie night | blanket fort"),
      zones=[
          Z("Couch", "couch, tv glow | dark living room, couch | couch, screen light", "popcorn | blanket | remote", solo="eating popcorn | hiding behind blanket",
            pair="cuddling, blanket", groups="crowded couch"),
          Z("Blanket fort", "blanket fort | pillow fort | fort, fairy lights", "fairy lights | pillows | laptop", solo="inside fort, laptop | peeking out", pair="inside fort, together",
            groups="fort, group"),
          Z("Projector", "projector screen, living room | home cinema | projector, wall", "projector beam | dust | snacks", solo="silhouette, projector | sitting, beanbag",
            pair="beanbags, together", groups="home cinema, group"),
      ]),
    P("Fireplace lounge", f="knit sweater | turtleneck, skirt | wool dress | silk robe", m="knit sweater | cardigan, shirt | turtleneck | flannel shirt",
      light="fireplace glow | candlelight | warm lamp light | firelight", mood="calm sultry", surf="floor:fur rug|chair:armchair|wall:mantel",
      detail="fireplace | fur rug | wine glasses | stockings | logs | candles",
      acts=dict(solo="warming hands, fire | reading, armchair | wine, fire", pair="blanket, fire | wine, together | lying on rug, fire", groups="gathered, fireplace"),
      zones=[
          Z("Hearth", "fireplace, hearth | stone fireplace | fire, living room", "fire | logs | poker", solo="sitting, hearth | stoking fire", pair="fire, together", groups="gathered, hearth"),
          Z("Fur rug", "fur rug, fireplace | rug, firelight | bearskin rug", "fur | firelight | wine", solo="lying, fur rug | stretching, rug", pair="lying, rug, together",
            groups="lounging, rug"),
          Z("Wingback chair", "wingback chair, fire | leather armchair | armchair, fireplace", "book | brandy | lamp", solo="reading, armchair | brandy, armchair",
            pair="sitting on lap, armchair", groups="armchairs, talking"),
      ]),
    P("Game night", f="t-shirt, jeans | hoodie | crop top, shorts | sweater", m="t-shirt | hoodie | flannel shirt | graphic t-shirt",
      light="lamp light | rgb lighting | tv glow | warm light", mood="playful happy", surf="chair:couch|floor:floor|table:coffee table",
      detail="game controllers | board game | dice | pizza box | energy drinks | cards",
      acts=dict(solo="gaming, controller | shuffling cards | rolling dice", pair="gaming together | arguing, game | high five", groups="game night | card game | party game"),
      zones=[
          Z("Console", "tv, game console | living room, gaming | couch, controllers", "controllers | screen | snacks", solo="gaming, controller | leaning forward, gaming",
            pair="gaming, rivals", groups="gaming, group"),
          Z("Board game table", "coffee table, board game | living room, board game | tabletop game", "dice | cards | game board", solo="rolling dice | reading rules",
            pair="board game, together", groups="board game, group"),
          Z("Floor party", "living room floor, pizza | floor, cushions | party, living room", "pizza box | cards | cushions", solo="lying on floor, laughing | eating pizza",
            pair="card game, floor", groups="party game, floor"),
      ]),
    P("Mid-century lounge", f="shift dress | turtleneck, slacks | wrap dress | cigarette pants, blouse", m="turtleneck | cardigan, slacks | suit, no tie | polo shirt",
      light="warm lamp light | afternoon sun | globe lamp | evening light", mood="cool calm", surf="chair:lounge chair|floor:rug|table:coffee table|wall:wood paneling",
      detail="record player | teak furniture | bar cart | globe lamp | vinyl records | abstract art",
      acts=dict(solo="playing record | mixing cocktail | lounging, chair", pair="dancing, record player | cocktails, together | talking, lounge", groups="cocktail party"),
      zones=[
          Z("Record player", "record player, living room | turntable, vinyl | hi-fi, wood", "vinyl | speakers | album covers", solo="choosing record | dancing alone",
            pair="slow dance, record", groups="dancing, group"),
          Z("Lounge chair", "lounge chair | eames chair | leather lounge chair", "ottoman | book | lamp", solo="lounging, chair | reading, lounge chair", pair="sitting on armrest",
            groups="lounging, group"),
          Z("Bar cart", "bar cart | cocktail cart | home bar", "decanter | cocktail shaker | olives", solo="mixing cocktail | pouring drink", pair="toast, cocktails",
            groups="cocktail party"),
      ]),
    P("Loft living", f="slip dress | oversized shirt | tank top, jeans | knit dress", m="t-shirt, jeans | open shirt | henley shirt | turtleneck",
      light="big window light | city lights | sunset | night, neon", mood="calm cool", surf="chair:leather sofa|floor:wooden floor|wall:brick wall|table:coffee table",
      detail="exposed brick | steel beams | plants | city view | art canvases | bicycle",
      acts=dict(solo="looking at city | stretching, window | reading, sofa", pair="slow dance, loft | wine, window | cuddling, sofa", groups="loft party"),
      zones=[
          Z("Leather sofa", "leather sofa, loft | loft living room | sofa, brick wall", "cushions | magazines | lamp", solo="lounging, sofa | lying, sofa", pair="sofa, together",
            groups="sofa, group"),
          Z("Factory window", "factory window, city | loft window | big window, skyline", "skyline | rain | reflections", solo="silhouette, window | leaning, window",
            pair="window, together", groups="window, party"),
          Z("Art corner", "loft, easel | art corner | studio corner, loft", "canvases | paint | brushes", solo="painting, easel | sitting, floor, sketchbook", pair="painting together",
            groups="art night"),
      ]),
    P("Grandparents' parlor", f="floral dress | cardigan, long skirt | blouse, pearls | knit vest, skirt", m="cardigan, shirt | sweater vest | suit, waistcoat | tweed jacket",
      light="lace curtain light | lamp light | afternoon sun | dim warm light", mood="calm melancholy", surf="chair:floral sofa|floor:persian rug|table:tea table|wall:wallpaper",
      detail="lace doilies | grandfather clock | china cabinet | photo frames | piano | tea set",
      acts=dict(solo="playing piano | pouring tea | looking at photos", pair="tea, together | piano, together | looking at album", groups="family gathering | tea party"),
      zones=[
          Z("Piano", "upright piano, parlor | piano, lace | parlor, piano", "sheet music | candles | photos", solo="playing piano | turning pages", pair="piano duet",
            groups="singing, piano"),
          Z("China cabinet", "china cabinet | parlor, cabinet | display cabinet", "teacups | porcelain | silverware", solo="dusting cabinet | holding teacup", pair="tea, china",
            groups="tea party"),
          Z("Floral sofa", "floral sofa | parlor sofa | vintage sofa, doilies", "doilies | cushions | cat", solo="knitting, sofa | napping, sofa", pair="photo album, sofa",
            groups="family photo"),
      ]),
    P("Japanese living room", f="yukata | knit sweater, skirt | kimono | t-shirt, shorts", m="yukata | jinbei | hoodie | t-shirt",
      light="paper lantern | shoji light | afternoon sun | warm light", mood="calm happy", surf="floor:tatami|table:kotatsu|wall:shoji",
      detail="kotatsu | tatami | mandarin oranges | tea | paper lanterns | futon",
      acts=dict(solo="under kotatsu | peeling orange | sipping tea", pair="kotatsu, together | tea, tatami | napping, kotatsu", groups="kotatsu, group | new year, kotatsu"),
      zones=[
          Z("Kotatsu", "kotatsu, living room | kotatsu, tatami | under kotatsu", "mandarin oranges | blanket | tea", solo="under kotatsu, napping | peeling orange",
            pair="under kotatsu, together", groups="kotatsu, group"),
          Z("Engawa", "engawa | veranda, garden | wooden veranda", "wind chime | garden | watermelon", solo="sitting, engawa | fanning, engawa", pair="watermelon, engawa",
            groups="sitting, engawa, group"),
          Z("Tatami", "tatami room | tatami, shoji | washitsu", "shoji | cushion | ikebana", solo="lying, tatami | kneeling, tatami", pair="tea ceremony",
            groups="tatami, group"),
      ]),
    P("Sunroom", f="sundress | linen dress | camisole, linen pants | swimsuit, cover-up", m="linen shirt | t-shirt | tank top | polo shirt",
      light="bright sunlight | glass roof light | morning sun | golden hour", mood="calm happy", surf="chair:wicker chair|floor:tiled floor|table:side table|bed:daybed",
      detail="potted palms | wicker | glass roof | ferns | lemonade | cat",
      acts=dict(solo="napping, daybed | reading, wicker chair | watering plants", pair="lemonade, together | napping together | reading together", groups="brunch, sunroom"),
      zones=[
          Z("Daybed", "daybed, sunroom | sunroom, daybed | daybed, glass roof", "cushions | sunlight | book", solo="napping, daybed | reading, daybed", pair="lying, daybed, together",
            groups="lounging, sunroom"),
          Z("Plants", "sunroom, plants | conservatory, ferns | greenhouse room", "ferns | palms | watering can", solo="watering plants | misting plants", pair="repotting, together",
            groups="plant swap"),
          Z("Wicker chairs", "wicker chairs, sunroom | rattan chairs | sunroom, tea table", "lemonade | magazines | sun hat", solo="sitting, wicker chair | lemonade",
            pair="lemonade, together", groups="brunch"),
      ]),
], HOME_STYLES, NSFW, "upper body | cowboy shot | full body | from side")

theme("balcony", "Balcony", [
    P("City balcony", f="sundress | t-shirt, shorts | cardigan | silk robe", m="t-shirt | linen shirt | hoodie | robe",
      light="sunset | morning sun | city lights | night", mood="calm happy", surf="chair:folding chair|wall:railing|floor:balcony floor",
      detail="potted plants | city view | coffee | string lights | air conditioner unit | traffic below",
      acts=dict(solo="drinking coffee | leaning on railing | smoking", pair="coffee together | sunset, together | leaning on railing, together", groups="balcony party"),
      zones=[
          Z("Railing", "balcony railing, city | apartment balcony | balcony, skyline", "city view | wind | pigeons", solo="leaning on railing | looking at city", pair="leaning on railing, together",
            groups="railing, group"),
          Z("Bistro set", "balcony, bistro table | small balcony table | balcony, folding chairs", "coffee | croissant | ashtray", solo="coffee, balcony | reading, balcony",
            pair="breakfast, balcony", groups="drinks, balcony"),
          Z("Corner plants", "balcony garden | balcony, potted plants | balcony, herbs", "herbs | tomatoes | watering can", solo="watering plants | repotting", pair="gardening together",
            groups="plants, group"),
      ]),
    P("Penthouse terrace", f="evening gown | slip dress | cocktail dress | bikini, sarong", m="suit | open shirt | tuxedo | linen shirt",
      light="city lights | sunset | night, skyline | blue hour", mood="cool calm", surf="chair:lounge chair|wall:glass railing|floor:terrace|water:infinity pool",
      detail="skyline | champagne | infinity pool | lounge chairs | fire pit | helicopter lights",
      acts=dict(solo="champagne, skyline | lounging, terrace | leaning, glass railing", pair="champagne, together | slow dance, terrace | kiss, skyline", groups="rooftop party"),
      zones=[
          Z("Glass railing", "penthouse terrace, glass railing | terrace, skyline | rooftop terrace", "skyline | wind | champagne", solo="leaning, glass railing | looking at skyline",
            pair="skyline, together", groups="toast, skyline"),
          Z("Infinity pool", "rooftop pool, penthouse | infinity pool, city | terrace pool", "water | city lights | towels", solo="leaning, pool edge | swimming", pair="pool, together",
            groups="pool party"),
          Z("Fire pit", "fire pit, terrace | rooftop fire pit | terrace, lounge", "flames | blankets | wine", solo="warming, fire pit | wine, fire", pair="blanket, fire pit",
            groups="gathered, fire pit"),
      ]),
    P("Laundry balcony", f="t-shirt, shorts | tank top, skirt | house dress | oversized shirt", m="t-shirt | tank top | shorts, t-shirt | sweatpants",
      light="morning sun | bright daylight | windy day | overcast", mood="calm happy", surf="wall:railing|floor:balcony floor|chair:stool",
      detail="laundry line | clothespins | sheets | wind | neighbors' balconies | laundry basket",
      acts=dict(solo="hanging laundry | folding clothes | chasing sheet", pair="hanging sheets together | folding sheets | chatting, laundry", groups="laundry, neighbors"),
      zones=[
          Z("Clothesline", "balcony, laundry line | clothesline, balcony | hanging laundry", "clothespins | shirts | wind", solo="hanging laundry | pinning shirt",
            pair="hanging sheets together", groups="laundry, group"),
          Z("Billowing sheets", "white sheets, wind | sheets, balcony | laundry, wind", "sheets | sunlight | wind", solo="behind sheet | holding sheet, wind", pair="hide and seek, sheets",
            groups="sheets, group"),
          Z("Neighbors", "apartment balconies | balconies, neighbors | apartment block", "balconies | plants | bicycles", solo="waving, neighbor | leaning, railing",
            pair="talking, across balconies", groups="balconies, chatting"),
      ]),
    P("Mediterranean balcony", f="white sundress | linen dress | off-shoulder blouse, skirt | bikini, sarong", m="linen shirt | white t-shirt | open shirt | linen pants, shirtless",
      light="bright sunlight | golden hour | sunset | moonlight", mood="happy calm", surf="chair:iron chair|wall:stone balustrade|floor:terracotta tiles",
      detail="bougainvillea | sea view | lemons | whitewashed walls | blue shutters | wine",
      acts=dict(solo="looking at sea | sipping wine | leaning, balustrade", pair="wine, sea view | breakfast, balcony | kiss, sunset", groups="dinner, balcony"),
      zones=[
          Z("Bougainvillea", "balcony, bougainvillea | flower balcony | balcony, pink flowers", "bougainvillea | petals | shutters", solo="smelling flowers | leaning, flowers",
            pair="flowers, together", groups="flowers, group"),
          Z("Sea view", "balcony, sea view | balcony, coast | balcony, ocean", "sea | sailboats | sun", solo="looking at sea | sunbathing, balcony", pair="sea view, together",
            groups="sea view, group"),
          Z("Breakfast table", "balcony breakfast | balcony table, lemons | breakfast, sea", "lemons | espresso | pastries", solo="breakfast, balcony | espresso", pair="breakfast together",
            groups="long breakfast"),
      ]),
    P("Juliet balcony", f="nightgown | corset dress | ball gown | silk robe", m="poet shirt | doublet | cloak | open shirt",
      light="moonlight | candlelight | night | lantern light", mood="calm sultry", surf="wall:stone balcony|floor:balcony",
      detail="ivy | moon | stone balustrade | candles | roses | lanterns",
      acts=dict(solo="looking at moon | leaning, balustrade | holding rose", pair="serenade | reaching up | kiss, balcony", groups="serenade, group"),
      zones=[
          Z("Ivy wall", "ivy wall, balcony | ivy, stone balcony | climbing ivy", "ivy | trellis | moon", solo="climbing ivy | reaching down", pair="climbing up, balcony",
            groups="ivy, group"),
          Z("Balustrade", "stone balustrade | stone balcony, moon | castle balcony", "moon | stars | roses", solo="leaning, balustrade | looking at moon", pair="leaning, together",
            groups="balcony, group"),
          Z("Open doors", "balcony doors, curtains | french doors, balcony | balcony, curtains", "curtains | candles | wind", solo="stepping out, curtains | silhouette, doorway",
            pair="embrace, doorway", groups="doorway, group"),
      ]),
    P("Rainy balcony", f="hoodie | oversized cardigan | raincoat | t-shirt, shorts", m="hoodie | flannel shirt | t-shirt | raincoat",
      light="rain, overcast | grey light | streetlight, rain | lamp light", mood="melancholy calm", surf="chair:plastic chair|wall:railing|floor:wet floor",
      detail="rain | wet railing | umbrella | puddles | steam from cup | city lights",
      acts=dict(solo="watching rain | smoking, rain | hand out, rain", pair="umbrella, together | watching rain, together | hug, rain", groups="rain, balcony, group"),
      zones=[
          Z("Under awning", "balcony awning, rain | covered balcony | balcony, rain", "dripping water | tea | umbrella", solo="tea, rain | sitting, rain", pair="under awning, together",
            groups="awning, group"),
          Z("Wet railing", "wet railing | balcony railing, rain | rain, city balcony", "raindrops | city | fog", solo="hand out, rain | leaning, wet railing", pair="rain, leaning together",
            groups="railing, rain"),
          Z("Window glow", "balcony, window glow | balcony door, light | balcony, warm window", "warm light | plants | reflection", solo="looking inside | sitting by door",
            pair="doorway, rain", groups="window, group"),
      ]),
    P("Hotel balcony", f="bathrobe | bikini, sarong | sundress | silk robe", m="bathrobe | swim trunks, open shirt | linen shirt | robe",
      light="morning sun | sunset | bright daylight | night, pool lights", mood="happy calm", surf="chair:sun lounger|wall:railing|floor:balcony floor|table:balcony table",
      detail="ocean view | palm trees | room service | towels | sunscreen | cocktails",
      acts=dict(solo="room service | sunbathing, balcony | looking at ocean", pair="breakfast, robes | cocktails, balcony | kiss, sunset", groups="balcony, friends"),
      zones=[
          Z("Ocean view", "hotel balcony, ocean | resort balcony | balcony, palm trees", "ocean | palms | sun", solo="leaning, railing | stretching, sun", pair="ocean view, together",
            groups="view, group"),
          Z("Lounger", "sun lounger, balcony | balcony, deck chair | lounger, resort", "towels | sunscreen | magazine", solo="sunbathing | lying, lounger", pair="loungers, together",
            groups="loungers, group"),
          Z("Room service", "room service, balcony | balcony breakfast | balcony table, tray", "tray | fruit | coffee", solo="breakfast, robe | coffee, balcony", pair="feeding fruit",
            groups="brunch, balcony"),
      ]),
    P("Winter balcony", f="puffer jacket | knit sweater, scarf | coat, beanie | fur coat", m="puffer jacket | wool coat, scarf | knit sweater | parka",
      light="snow light | overcast | night, snow | morning, frost", mood="calm happy", surf="wall:snowy railing|floor:snowy floor|chair:chair",
      detail="snow | frost | hot cocoa | breath vapor | icicles | fairy lights", weather="snow overcast clear",
      acts=dict(solo="hot cocoa | catching snowflakes | brushing off snow", pair="hot cocoa, together | snowball, balcony | sharing scarf", groups="snow, balcony, group"),
      zones=[
          Z("Snowy railing", "snowy balcony | balcony, snow | railing, snow", "snow | icicles | breath vapor", solo="catching snowflakes | leaning, snowy railing",
            pair="snow, together", groups="snow, group"),
          Z("Fairy lights", "balcony, fairy lights, snow | winter balcony, lights | balcony, christmas lights", "fairy lights | wreath | snow", solo="hanging lights | looking at lights",
            pair="lights, together", groups="lights, group"),
          Z("Doorway", "balcony door, snow | doorway, winter | balcony door, warm light", "warm light | blanket | cocoa", solo="stepping out, blanket | cocoa, doorway",
            pair="blanket, doorway", groups="doorway, group"),
      ]),
    P("Rooftop garden", f="sundress | overalls | tank top, shorts | linen dress", m="t-shirt | overalls | linen shirt | tank top",
      light="golden hour | sunny day | sunset | string lights", mood="happy calm", surf="chair:garden bench|floor:wooden deck|wall:railing|table:planter",
      detail="raised beds | beehive | string lights | water tank | skyline | sunflowers",
      acts=dict(solo="harvesting tomatoes | watering plants | beekeeping", pair="gardening together | picnic, rooftop | sunset, rooftop", groups="rooftop dinner | community garden"),
      zones=[
          Z("Raised beds", "rooftop garden, raised beds | urban garden | rooftop, vegetables", "tomatoes | lettuce | trowel", solo="harvesting | weeding", pair="harvest together",
            groups="community garden"),
          Z("Beehive", "rooftop beehive | beehives, roof | apiary, rooftop", "bees | honeycomb | smoker", solo="beekeeping | holding honeycomb", pair="beekeeping, together",
            groups="honey harvest"),
          Z("Deck", "rooftop deck | roof deck, string lights | rooftop, skyline", "string lights | skyline | cushions", solo="lying, deck | sunset, rooftop", pair="picnic, rooftop",
            groups="rooftop dinner"),
      ]),
], HOME_STYLES, NSFW, "upper body | cowboy shot | full body | from side")

theme("garden", "Garden", [
    P("Backyard", f="sundress | t-shirt, shorts | tank top, denim shorts | swimsuit", m="t-shirt | tank top | shorts, t-shirt | swim trunks",
      light="sunny day | golden hour | afternoon sun | sunset", mood="happy playful", surf="floor:lawn|chair:lawn chair|table:picnic table|water:kiddie pool",
      detail="sprinkler | lawn chairs | hammock | garden hose | ball | picnic blanket",
      acts=dict(solo="lying on grass | sprinkler | hammock nap", pair="sprinkler, playing | hose, splashing | picnic, lawn", groups="lawn games | backyard party"),
      zones=[
          Z("Lawn", "backyard lawn | grass, backyard | lawn, sunny", "sprinkler | ball | dandelions", solo="lying on grass | running, sprinkler", pair="water fight, hose",
            groups="lawn games"),
          Z("Hammock", "hammock, trees | backyard hammock | hammock, shade", "hammock | book | lemonade", solo="napping, hammock | reading, hammock", pair="hammock, together",
            groups="hammock, group"),
          Z("Picnic table", "picnic table, backyard | backyard, picnic table | wooden table, garden", "watermelon | lemonade | burgers", solo="eating watermelon | sitting, picnic table",
            pair="lunch, picnic table", groups="cookout"),
      ]),
    P("English garden", f="floral dress | linen dress, straw hat | blouse, long skirt | cardigan, dress", m="linen shirt | waistcoat, shirt | cardigan | straw hat, shirt",
      light="soft sunlight | dappled light | overcast | golden hour", mood="calm happy", surf="chair:garden bench|floor:grass path|table:tea table",
      detail="roses | hedges | stone path | climbing roses | lavender | birdbath",
      acts=dict(solo="cutting roses | reading, bench | smelling flowers", pair="walking, garden path | tea, garden | arm in arm", groups="garden party | tea party"),
      zones=[
          Z("Rose arch", "rose arch | rose garden | climbing roses, arch", "roses | thorns | petals", solo="smelling roses | cutting roses", pair="walking under arch",
            groups="garden walk"),
          Z("Hedge path", "hedge path | garden path, hedges | boxwood hedges", "hedges | gravel | statue", solo="walking, path | strolling", pair="walking, arm in arm",
            groups="garden tour"),
          Z("Tea lawn", "garden tea table | lawn, tea set | tea, garden", "tea set | scones | lace tablecloth", solo="pouring tea | sipping tea", pair="tea, together",
            groups="tea party"),
      ]),
    P("Vegetable garden", f="gardening overalls | t-shirt, shorts | sundress, gardening gloves | straw hat, tank top", m="overalls | t-shirt | flannel shirt | straw hat, tank top",
      light="morning sun | bright daylight | golden hour | overcast", mood="happy calm", surf="floor:dirt|chair:wooden crate|table:potting bench",
      detail="tomatoes | watering can | wheelbarrow | scarecrow | trowel | dirt",
      acts=dict(solo="digging | picking tomatoes | watering plants", pair="harvest together | carrying basket | planting seedlings", groups="harvest, group"),
      zones=[
          Z("Tomato rows", "vegetable garden, tomatoes | garden beds | tomato plants", "tomatoes | stakes | basket", solo="picking tomatoes | tying stakes", pair="harvest together",
            groups="harvest, group"),
          Z("Potting bench", "potting bench | garden shed, bench | seedling trays", "pots | seedlings | soil", solo="repotting | planting seeds", pair="planting together",
            groups="seedlings, group"),
          Z("Wheelbarrow", "wheelbarrow, garden | garden, compost | garden path, wheelbarrow", "wheelbarrow | shovel | pumpkins", solo="pushing wheelbarrow | shoveling",
            pair="riding wheelbarrow", groups="garden work"),
      ]),
    P("Japanese garden", f="kimono | yukata | linen dress | cardigan, skirt", m="yukata | kimono | linen shirt | hakama",
      light="soft light | morning mist | autumn sun | lantern light", mood="calm", surf="floor:stepping stones|chair:stone bench|water:koi pond",
      detail="koi pond | stone lantern | maple tree | bamboo | moss | raked gravel",
      acts=dict(solo="feeding koi | raking gravel | meditating", pair="walking, stepping stones | tea, pavilion | feeding koi together", groups="tea ceremony, garden"),
      zones=[
          Z("Koi pond", "koi pond | pond, japanese garden | stone bridge, pond", "koi | lily pads | stone bridge", solo="feeding koi | crouching, pond", pair="bridge, together",
            groups="pond, group"),
          Z("Zen gravel", "zen garden | raked gravel | rock garden", "raked gravel | rocks | moss", solo="raking gravel | sitting, meditating", pair="sitting, zen garden",
            groups="meditation, group"),
          Z("Maple path", "japanese maple, path | stepping stones, maple | garden path, stone lantern", "red maple leaves | stone lantern | moss", solo="walking, stepping stones",
            pair="walking together, maples", groups="garden walk"),
      ]),
    P("Flower garden", f="sundress | floral dress | white dress, flower crown | blouse, skirt", m="linen shirt | t-shirt | flower crown, shirt | vest, shirt",
      light="sunny day | golden hour | soft light | morning light", mood="happy calm", surf="floor:grass|chair:bench|table:garden table",
      detail="flower beds | butterflies | bees | sunflowers | tulips | watering can",
      acts=dict(solo="picking flowers | flower crown | holding bouquet", pair="flower crown, another | picking flowers, together | lying in flowers", groups="flower picking"),
      zones=[
          Z("Sunflowers", "sunflowers, garden | sunflower patch | tall sunflowers", "sunflowers | bees | sky", solo="among sunflowers | looking up, sunflowers", pair="hiding, sunflowers",
            groups="sunflowers, group"),
          Z("Tulip beds", "tulip beds | tulips, garden | flower beds", "tulips | butterflies | path", solo="kneeling, tulips | holding tulip", pair="bouquet, giving",
            groups="flower beds, group"),
          Z("Wildflower corner", "wildflowers, garden | wild garden | meadow garden", "daisies | poppies | butterflies", solo="lying in flowers | making flower crown",
            pair="flower crown, another", groups="picnic, flowers"),
      ]),
    P("Greenhouse", f="gardening apron, sundress | overalls | linen shirt, shorts | tank top, gardening gloves", m="gardening apron, t-shirt | overalls | linen shirt | tank top",
      light="diffused light | glass roof light | morning sun | humid haze", mood="calm happy", surf="table:potting table|floor:greenhouse floor|chair:stool",
      detail="glass panes | ferns | orchids | misting | watering can | hanging plants",
      acts=dict(solo="misting plants | repotting orchid | taking notes", pair="repotting together | looking at plants | watering, together", groups="plant workshop"),
      zones=[
          Z("Orchids", "greenhouse, orchids | orchid shelves | glass house, flowers", "orchids | labels | mist", solo="misting orchids | examining flower", pair="orchids, together",
            groups="orchids, group"),
          Z("Potting table", "greenhouse potting table | greenhouse bench | pots, greenhouse", "pots | soil | seedlings", solo="repotting | planting seeds", pair="repotting together",
            groups="workshop, greenhouse"),
          Z("Hanging plants", "greenhouse, hanging plants | glass ceiling, vines | greenhouse aisle", "vines | hanging pots | condensation", solo="watering hanging plants",
            pair="walking, greenhouse", groups="greenhouse tour"),
      ]),
    P("Night garden", f="nightgown | slip dress | silk robe | evening gown", m="open shirt | robe | dark suit | linen shirt",
      light="moonlight | lanterns | fireflies | string lights", mood="calm sultry", surf="floor:grass|chair:garden swing|water:fountain",
      detail="fireflies | lanterns | night blooming flowers | fountain | moon | crickets",
      acts=dict(solo="catching fireflies | wandering, lantern | sitting, swing", pair="dancing, garden | kiss, moonlight | swinging together", groups="garden party, lanterns"),
      zones=[
          Z("Fireflies", "garden, fireflies | lawn, fireflies | night garden, fireflies", "fireflies | glass jar | grass", solo="catching fireflies | jar, fireflies",
            pair="fireflies, together", groups="fireflies, group"),
          Z("Garden swing", "garden swing, night | porch swing, garden | swing, lanterns", "lanterns | cushions | moon", solo="swinging | sitting, swing", pair="swing, together",
            groups="swing, group"),
          Z("Fountain", "garden fountain, night | stone fountain, moonlight | fountain, lanterns", "fountain | coins | moonlight", solo="sitting, fountain edge | tossing coin",
            pair="fountain, together", groups="fountain, group"),
      ]),
    P("Zen courtyard", f="linen dress | yoga pants, tank top | kimono | robe", m="linen shirt | yoga pants | yukata | robe",
      light="morning light | soft shade | bamboo shade | dappled light", mood="calm", surf="floor:stone floor|water:reflecting pool|chair:stone bench",
      detail="bamboo | reflecting pool | bonsai | incense | stone | water feature",
      acts=dict(solo="yoga | meditating | trimming bonsai", pair="yoga together | tea, courtyard | meditating together", groups="yoga class"),
      zones=[
          Z("Bamboo grove", "bamboo, courtyard | bamboo grove, garden | bamboo wall", "bamboo | shade | wind", solo="walking, bamboo | stretching, bamboo", pair="bamboo, together",
            groups="bamboo, group"),
          Z("Reflecting pool", "reflecting pool | courtyard pool | still water, garden", "still water | reflection | lilies", solo="sitting, pool edge | reflection", pair="pool edge, together",
            groups="pool, group"),
          Z("Bonsai shelf", "bonsai shelf | bonsai garden | bonsai, courtyard", "bonsai | shears | moss", solo="trimming bonsai | watering bonsai", pair="bonsai, together",
            groups="bonsai, group"),
      ]),
    P("Overgrown garden", f="white dress | cardigan, skirt | vintage dress | blouse, overalls", m="shirt, suspenders | linen shirt | cardigan | t-shirt",
      light="dappled light | overcast | golden hour | misty morning", mood="melancholy calm", surf="floor:overgrown path|chair:rusty bench|wall:stone wall",
      detail="ivy | broken statue | rusty gate | wild roses | moss | old fountain",
      acts=dict(solo="exploring | pushing gate | sitting, bench", pair="exploring together | holding hands, ruins | secret garden", groups="exploring, group"),
      zones=[
          Z("Rusty gate", "rusty gate, garden | iron gate, ivy | garden gate", "ivy | rust | keys", solo="opening gate | peeking through gate", pair="opening gate, together",
            groups="gate, group"),
          Z("Broken statue", "broken statue, garden | moss statue | stone angel, ivy", "moss | ivy | cracks", solo="touching statue | sitting, statue base", pair="statue, together",
            groups="statue, group"),
          Z("Walled corner", "stone wall, garden | walled garden | secret garden", "wild roses | moss | bench", solo="sitting, bench | picking roses", pair="secret garden, together",
            groups="secret garden, group"),
      ]),
], "watercolor, garden | photorealistic, natural light | anime illustration, scenery | film photography, garden", NSFW, "upper body | cowboy shot | full body | from side")

theme("restroom", "Restroom", [
    P("Home bathroom", f="t-shirt, shorts | bathrobe | pajamas | towel", m="t-shirt | bathrobe | boxers, t-shirt | towel",
      light="bathroom light | morning light | soft light | vanity light", mood="calm", surf="wall:tiled wall|table:sink counter|chair:toilet|floor:bath mat",
      detail="toothbrush | mirror | towels | toilet paper | plants | soap dispenser",
      acts=dict(solo="brushing teeth | looking in mirror | washing face", pair="brushing teeth, together | doing hair, another | mirror, together", groups="morning rush"),
      zones=[
          Z("Mirror", "bathroom mirror | mirror, sink | vanity mirror, bathroom", "toothbrush | towel | toiletries", solo="looking in mirror | brushing teeth", pair="mirror, together",
            groups="mirror, group"),
          Z("Toilet", "bathroom, toilet | small bathroom | toilet, tiles", "toilet paper | magazine | plant", solo="sitting on toilet lid, phone | reading, toilet", pair="talking through door",
            groups="queue, bathroom"),
          Z("Tiled corner", "tiled bathroom | bathroom, white tiles | bathroom corner", "tiles | towel rack | laundry basket", solo="leaning, tiles | drying hair", pair="drying hair, another",
            groups="crowded bathroom"),
      ]),
    P("Club restroom", f="bodycon dress | sequin dress | crop top, mini skirt | tube top, leather pants", m="black shirt | leather jacket | tank top | open shirt",
      light="neon light | red light | fluorescent light | dim light", mood="cool playful", surf="wall:graffiti wall|table:sink counter|chair:toilet|floor:floor",
      detail="graffiti | stickers | mirror selfie | lipstick | bass through wall | paper towels",
      acts=dict(solo="fixing makeup | mirror selfie | lipstick, mirror", pair="whispering, restroom | sneaking in, stall | mirror, together", groups="queue, restroom | mirror, group"),
      zones=[
          Z("Mirror row", "club restroom mirror | restroom, mirrors | bathroom mirror, neon", "lipstick | phone | paper towels", solo="fixing makeup | mirror selfie", pair="mirror, together",
            groups="mirror, group"),
          Z("Stall", "restroom stall | bathroom stall, graffiti | toilet stall", "graffiti | stickers | toilet", solo="leaning, stall door | sitting, stall", pair="sneaking in, stall",
            groups="stall, crowded"),
          Z("Neon hallway", "restroom hallway, neon | club hallway | corridor, restroom sign", "neon sign | posters | bass", solo="leaning, hallway | phone, hallway", pair="hallway, close",
            groups="queue, hallway"),
      ]),
    P("Office restroom", f="office lady, blouse | pencil skirt, blouse | suit, skirt | cardigan, slacks", m="business suit | dress shirt, necktie | vest, shirt | suit, loose necktie",
      light="fluorescent light | cold light | bright light | dim light", mood="serious tense", surf="wall:stall partition|table:sink counter|chair:toilet|floor:tiled floor",
      detail="hand dryer | paper towels | soap dispenser | mirror | marble counter | cleaning sign",
      acts=dict(solo="washing hands | fixing necktie | splashing face", pair="secret meeting | fixing tie, another | arguing, quietly", groups="gossip, restroom"),
      zones=[
          Z("Sinks", "office restroom, sinks | marble sinks | restroom counter", "soap | hand dryer | paper towels", solo="washing hands | splashing face", pair="side by side, sinks",
            groups="gossip, sinks"),
          Z("Stall", "office bathroom stall | stall, partition | toilet stall, office", "partition | lock | toilet", solo="leaning, stall | sitting, stall, phone", pair="stall, together",
            groups="stalls, row"),
          Z("Mirror", "large mirror, restroom | restroom mirror, office | mirror, fluorescent", "mirror | lipstick | comb", solo="fixing makeup | fixing necktie", pair="fixing tie, another",
            groups="mirror, group"),
      ]),
    P("Train restroom", f="travel outfit | hoodie, leggings | coat, scarf | sweater, jeans", m="hoodie | jacket, jeans | coat | flannel shirt",
      light="fluorescent light | flickering light | dim light | night", mood="tense playful", surf="wall:steel wall|table:small sink|chair:toilet",
      detail="steel sink | tiny mirror | rattling | window, blur | paper towels | warning sign",
      acts=dict(solo="splashing face | looking in mirror | swaying", pair="cramped, together | sneaking in | swaying, together", groups="queue, train"),
      zones=[
          Z("Cramped cabin", "train restroom | tiny restroom | cramped bathroom", "steel sink | mirror | warning sign", solo="splashing face | looking in mirror", pair="cramped, together",
            groups="corridor, queue"),
          Z("Frosted window", "train restroom, window | frosted window, train | small window, train", "scenery blur | frost | night", solo="looking out window | leaning, window",
            pair="window, close", groups="window, group"),
          Z("Corridor", "train corridor, restroom door | corridor, train | vestibule, train", "door | sign | window", solo="waiting, door | leaning, corridor", pair="corridor, close",
            groups="queue, corridor"),
      ]),
    P("Airplane lavatory", f="flight attendant uniform | travel outfit | sweater, leggings | dress", m="pilot uniform | hoodie | travel outfit | shirt, jeans",
      light="dim light | fluorescent light | cabin light | night", mood="tense playful", surf="wall:lavatory wall|table:tiny sink|chair:toilet",
      detail="tiny sink | occupied sign | turbulence | mirror | paper cups | porthole",
      acts=dict(solo="looking in mirror | turbulence | washing hands", pair="sneaking in | cramped, together | occupied sign", groups="queue, aisle"),
      zones=[
          Z("Lavatory", "airplane lavatory | airplane bathroom | tiny lavatory", "occupied sign | mirror | sink", solo="looking in mirror | washing hands", pair="cramped, together",
            groups="aisle, queue"),
          Z("Galley", "airplane galley | galley, curtain | galley, carts", "carts | coffee | curtain", solo="leaning, galley | making coffee", pair="galley, whispering",
            groups="galley, crew"),
          Z("Aisle", "airplane aisle | aisle, lavatory | cabin aisle, night", "seats | reading lights | blankets", solo="walking, aisle | waiting, aisle", pair="passing, aisle",
            groups="aisle, passengers"),
      ]),
    P("Gas station restroom", f="crop top, denim shorts | tank top, jeans | hoodie | leather jacket", m="leather jacket | tank top | flannel shirt | t-shirt, jeans",
      light="fluorescent light | flickering light | neon outside | night", mood="tense cool", surf="wall:dirty tiles|table:sink|chair:toilet|floor:floor",
      detail="cracked mirror | graffiti | key on keychain | flickering light | paper towels | rust",
      acts=dict(solo="washing face | looking in cracked mirror | lighting cigarette", pair="road trip stop | washing up, together | arguing, restroom", groups="road trip, group"),
      zones=[
          Z("Cracked mirror", "cracked mirror, restroom | gas station bathroom | grimy mirror", "cracks | graffiti | sink", solo="washing face | looking in mirror", pair="mirror, together",
            groups="mirror, group"),
          Z("Outside door", "restroom door, gas station | gas station, side door | back of gas station", "keychain | ice machine | neon", solo="leaning, door | smoking", pair="waiting, door",
            groups="road trip, group"),
          Z("Stall", "grimy stall | restroom stall, graffiti | single toilet room", "graffiti | rust | toilet", solo="leaning, stall | sitting, stall", pair="stall, together",
            groups="stall, crowded"),
      ]),
    P("Luxury restroom", f="evening gown | cocktail dress | satin dress | little black dress", m="tuxedo | suit | dress shirt, bow tie | velvet blazer",
      light="golden light | chandelier | warm vanity light | candlelight", mood="cool calm", surf="wall:marble wall|table:marble counter|chair:velvet stool|floor:marble floor",
      detail="marble | gold faucets | orchids | folded towels | perfume bottles | chandelier",
      acts=dict(solo="powdering nose | fixing hair | perfume", pair="whispering, powder room | fixing gown, another | toast, champagne", groups="powder room, gossip"),
      zones=[
          Z("Powder room", "powder room | vanity, powder room | gilded mirror", "perfume | powder | orchids", solo="powdering nose | fixing hair", pair="powder room, together",
            groups="powder room, group"),
          Z("Marble sinks", "marble sinks, gold | luxury restroom | marble counter, gold faucets", "gold faucets | towels | soap", solo="washing hands | leaning, marble", pair="side by side, mirror",
            groups="sinks, group"),
          Z("Lounge", "restroom lounge | velvet lounge, restroom | lounge, mirrors", "velvet | champagne | mirrors", solo="lounging, velvet | champagne", pair="lounge, together",
            groups="lounge, group"),
      ]),
    P("Locker restroom", f="sports bra, shorts | gym clothes | towel | tank top, leggings", m="tank top, shorts | towel | gym clothes | shirtless, shorts",
      light="fluorescent light | bright light | steam | dim light", mood="calm playful", surf="wall:tiled wall|table:sink|chair:bench|floor:tiled floor",
      detail="lockers | benches | steam | towels | water bottles | hand dryer",
      acts=dict(solo="drying off | changing, bench | looking in mirror", pair="towel snap | changing, together | stretching, bench", groups="locker room, team"),
      zones=[
          Z("Mirror wall", "locker room mirror | gym restroom | mirror wall, sinks", "mirrors | sinks | hair dryer", solo="drying hair | flexing, mirror", pair="mirror, together",
            groups="mirror, team"),
          Z("Bench", "locker room bench | bench, lockers | changing area", "lockers | towels | bags", solo="sitting, bench | tying shoes", pair="bench, together", groups="team, bench"),
          Z("Shower entrance", "shower entrance, locker room | tiled corridor, showers | showers, steam", "steam | tiles | towels", solo="towel, walking | drying off", pair="towels, together",
            groups="steam, group"),
      ]),
    P("Festival portable toilets", f="crop top, denim shorts | bikini top, shorts | festival outfit | sundress, boots", m="tank top, shorts | open shirt | festival outfit | shirtless, shorts",
      light="bright daylight | sunset | stage lights | night, flashlights", mood="playful happy", surf="wall:portable toilet|floor:grass",
      detail="portable toilets | mud | wristbands | glitter | queue | stage in distance",
      acts=dict(solo="waiting in line | glitter, face | holding cup", pair="waiting in line, together | laughing, queue | dancing, queue", groups="queue, festival"),
      zones=[
          Z("Queue", "festival toilets, queue | portable toilets | line, festival", "queue | wristbands | cups", solo="waiting in line | dancing, line", pair="waiting, together",
            groups="queue, festival"),
          Z("Wash station", "wash station, festival | outdoor sinks, festival | water station", "water | soap | glitter", solo="washing hands | refilling bottle", pair="splashing, water",
            groups="wash station, group"),
          Z("Back fence", "festival fence | fence, field | behind toilets, festival", "fence | grass | stage lights", solo="leaning, fence | sitting, grass", pair="sneaking off, fence",
            groups="hangout, fence"),
      ]),
], "photorealistic, flash photography | anime illustration | cinematic, film still | gritty photography", NSFW, "upper body | cowboy shot | full body | from side")

SCHOOL_F = "blouse, pencil skirt | cardigan, long skirt | school uniform, blazer | sweater vest, pleated skirt"
SCHOOL_M = "dress shirt, necktie | sweater vest, slacks | school uniform, blazer | cardigan, shirt"
SFW = ("sfw",)
theme("school", "School", [
    P("Classroom", f=SCHOOL_F, m=SCHOOL_M, levels=SFW,
      light="morning sunlight | afternoon sun | overcast | sunset, window", mood="calm happy", surf="chair:desk chair|table:school desk|wall:chalkboard",
      detail="chalkboard | desks | textbooks | window | clock | notebooks",
      acts=dict(solo="writing on chalkboard | reading, desk | looking out window", pair="studying together | passing notes | talking, desks", groups="class, lecture | group study"),
      zones=[
          Z("Chalkboard", "classroom, chalkboard | chalkboard, equations | front of classroom", "chalk | eraser | equations", solo="writing on chalkboard | pointing, chalkboard",
            pair="explaining, chalkboard", groups="lecture"),
          Z("Window seat", "classroom window | desk by window | classroom, window seat", "curtains | sakura outside | notebook", solo="looking out window | sleeping on desk",
            pair="talking, window", groups="window, group"),
          Z("After class", "empty classroom | classroom, sunset | classroom after school", "empty desks | sunset | bag", solo="packing bag | sitting on desk", pair="talking, empty classroom",
            groups="cleaning classroom"),
      ]),
    P("Library", f=SCHOOL_F, m=SCHOOL_M, levels=SFW,
      light="warm lamp light | window light | afternoon sun | quiet light", mood="calm serious", surf="chair:library chair|table:reading table|wall:bookshelf",
      detail="bookshelves | reading lamps | stacks of books | ladder | globe | dust",
      acts=dict(solo="reading | reaching for book | studying", pair="studying together | whispering, library | sharing book", groups="study group"),
      zones=[
          Z("Stacks", "library stacks | bookshelf aisle | tall bookshelves", "books | ladder | dust", solo="reaching for book | climbing ladder", pair="whispering, stacks",
            groups="stacks, group"),
          Z("Reading table", "library reading table | long table, lamps | study table", "lamps | notes | books", solo="studying, notes | reading, lamp", pair="studying together",
            groups="study group"),
          Z("Window alcove", "library window | reading nook | window alcove", "cushions | rain | book", solo="reading, window | dozing, book", pair="sharing book", groups="alcove, group"),
      ]),
    P("Rooftop", f=SCHOOL_F, m=SCHOOL_M, levels=SFW,
      light="sunny day | sunset | windy day | overcast", mood="calm happy", surf="wall:fence|floor:rooftop floor",
      detail="chain-link fence | water tank | lunch box | wind | sky | city view",
      acts=dict(solo="eating lunch | leaning on fence | lying, rooftop", pair="lunch together | confession | talking, fence", groups="lunch, rooftop"),
      zones=[
          Z("Fence", "school rooftop, fence | chain-link fence, rooftop | rooftop, city view", "fence | wind | sky", solo="leaning on fence | looking at sky", pair="confession, rooftop",
            groups="fence, group"),
          Z("Lunch spot", "school rooftop, lunch | rooftop, bento | rooftop bench", "lunch box | juice | sandwiches", solo="eating lunch | bento", pair="sharing lunch",
            groups="lunch, group"),
          Z("Water tank", "rooftop water tank | rooftop, ladder | rooftop corner", "ladder | water tank | clouds", solo="sitting, water tank | lying, sky", pair="hiding, rooftop",
            groups="rooftop, group"),
      ]),
    P("Science lab", f="lab coat, blouse | school uniform, lab coat | lab coat, sweater | lab coat, pencil skirt", m="lab coat, shirt | lab coat, necktie | school uniform, lab coat | lab coat, sweater vest",
      levels=SFW, light="fluorescent light | window light | bright light | bunsen flame", mood="serious playful", surf="table:lab bench|chair:stool|wall:periodic table",
      detail="test tubes | beakers | microscope | periodic table | safety goggles | skeleton model",
      acts=dict(solo="looking in microscope | pouring chemicals | taking notes", pair="experiment together | safety goggles, laughing | explosion, lab", groups="lab class"),
      zones=[
          Z("Lab bench", "science lab, bench | lab bench, beakers | chemistry lab", "beakers | flasks | goggles", solo="pouring chemicals | mixing", pair="experiment together",
            groups="lab class"),
          Z("Microscope", "microscope, lab | biology lab | lab, slides", "slides | microscope | specimens", solo="looking in microscope | adjusting focus", pair="microscope, sharing",
            groups="microscope, group"),
          Z("Specimen shelf", "specimen shelf | lab, jars | biology room, shelves", "jars | skeleton model | plants", solo="examining jar | dusting skeleton", pair="skeleton, joking",
            groups="specimens, group"),
      ]),
    P("Gymnasium", f="gym uniform | track suit | sportswear | jersey, shorts", m="gym uniform | track suit | jersey, shorts | t-shirt, shorts", levels=SFW,
      light="bright gym lights | window light | afternoon sun | fluorescent light", mood="happy serious", surf="floor:gym floor|wall:wall bars",
      detail="basketball hoop | volleyball net | mats | whistle | bleachers | sneakers",
      acts=dict(solo="shooting basketball | stretching | jumping rope", pair="volleyball, pair | stretching together | high five", groups="basketball game | volleyball match | team huddle"),
      zones=[
          Z("Court", "school gym, basketball court | gymnasium, court | indoor court", "basketball | hoop | lines", solo="shooting basketball | dribbling", pair="one on one",
            groups="basketball game"),
          Z("Bleachers", "gym bleachers | bleachers, gym | stands, gymnasium", "water bottles | bags | towels", solo="sitting, bleachers | drinking water", pair="resting, bleachers",
            groups="cheering, bleachers"),
          Z("Mats", "gym mats | mats, gymnasium | vaulting horse", "mats | vaulting horse | wall bars", solo="stretching, mat | handstand", pair="stretching together",
            groups="warm-up, group"),
      ]),
    P("Courtyard", f=SCHOOL_F, m=SCHOOL_M, levels=SFW,
      light="spring sun | dappled light | afternoon sun | overcast", mood="happy calm", surf="chair:bench|floor:grass",
      detail="cherry blossoms | benches | vending machine | bicycles | fountain | ginkgo leaves",
      acts=dict(solo="reading, bench | eating lunch | walking, bag", pair="walking together | lunch, bench | talking, tree", groups="lunch, courtyard | chatting, group"),
      zones=[
          Z("Cherry tree", "cherry tree, schoolyard | sakura, courtyard | cherry blossoms, school", "petals | wind | bench", solo="under cherry tree | catching petals", pair="petals, together",
            groups="hanami, group"),
          Z("Vending machine", "vending machine, school | vending machines, courtyard | drink machine", "cans | coins | light", solo="buying drink | leaning, vending machine",
            pair="sharing drink", groups="drinks, group"),
          Z("Bike racks", "bicycle racks, school | school gate, bicycles | bike parking", "bicycles | gate | helmet", solo="unlocking bicycle | walking bicycle", pair="walking bicycles together",
            groups="leaving school, group"),
      ]),
    P("Music room", f=SCHOOL_F, m=SCHOOL_M, levels=SFW,
      light="afternoon sun | warm light | window light | sunset", mood="calm happy", surf="chair:piano bench|floor:wooden floor|wall:soundproof wall",
      detail="grand piano | sheet music | music stands | violin | drums | metronome",
      acts=dict(solo="playing piano | playing violin | tuning guitar", pair="piano duet | practicing together | singing, piano", groups="band practice | choir"),
      zones=[
          Z("Piano", "music room, grand piano | piano, sunset | grand piano, window", "sheet music | metronome | sunlight", solo="playing piano | turning pages", pair="piano duet",
            groups="singing, piano"),
          Z("Band corner", "band practice, music room | drums, amplifiers | music room, instruments", "drums | amplifiers | guitars", solo="playing drums | tuning guitar",
            pair="jam session", groups="band practice"),
          Z("Choir risers", "choir risers | music room, risers | choir room", "risers | sheet music | conductor stand", solo="conducting | singing", pair="singing together", groups="choir"),
      ]),
    P("Art room", f="smock, school uniform | apron, cardigan | smock, long skirt | overalls, sweater", m="smock, school uniform | apron, shirt | smock, slacks | overalls, t-shirt",
      levels=SFW, light="north light | window light | afternoon sun | soft light", mood="calm playful", surf="chair:stool|table:art table|wall:easel wall",
      detail="easels | paint palettes | plaster busts | clay | brushes | paint splatter",
      acts=dict(solo="painting, easel | sculpting clay | sketching", pair="painting together | paint on face | portrait drawing", groups="art class"),
      zones=[
          Z("Easels", "art room, easels | easel, window | painting class", "canvases | palette | brushes", solo="painting, easel | mixing paint", pair="painting together",
            groups="art class"),
          Z("Plaster busts", "plaster busts | still life, art room | drawing class", "plaster bust | charcoal | sketchbook", solo="sketching bust | charcoal drawing", pair="portrait drawing",
            groups="drawing class"),
          Z("Pottery wheel", "pottery wheel | clay table | ceramics room", "clay | wheel | kiln", solo="pottery wheel | shaping clay", pair="pottery, together", groups="ceramics class"),
      ]),
    P("Club room", f=SCHOOL_F, m=SCHOOL_M, levels=SFW,
      light="afternoon sun | lamp light | sunset | overcast", mood="playful happy", surf="chair:folding chair|table:long table|wall:whiteboard",
      detail="whiteboard | snacks | trophies | posters | tea set | board games",
      acts=dict(solo="drinking tea | writing on whiteboard | reading manga", pair="board game | arguing, club | tea, together", groups="club meeting | planning festival"),
      zones=[
          Z("Long table", "club room, table | club room, tea | meeting table", "tea | snacks | papers", solo="drinking tea | reading", pair="board game, table", groups="club meeting"),
          Z("Whiteboard", "club room whiteboard | whiteboard, plans | club room, notes", "markers | plans | sticky notes", solo="writing on whiteboard | presenting", pair="planning together",
            groups="planning festival"),
          Z("Trophy shelf", "trophy shelf | club room, trophies | shelf, photos", "trophies | photos | ribbons", solo="looking at trophies | holding trophy", pair="photos, together",
            groups="team photo"),
      ]),
], "anime illustration, slice of life | watercolor | photorealistic, natural light | film photography", NSFW, "upper body | cowboy shot | full body | from side")
