from lib import P, Z, theme

NSFW = "photorealistic, detailed skin | hentai, anime coloring | painterly, erotic illustration | glamour photography"

theme("scifi", "Sci-fi", [
    P("Cyberpunk street", f="techwear jacket | neon bodysuit | cropped jacket, cyber implants | latex coat", m="techwear jacket | trench coat, cyber implants | hoodie, visor | leather jacket, chrome arm",
      light="neon lights | holographic signs | rain, neon | night, pink and blue", mood="cool tense", surf="wall:neon wall|floor:wet street",
      detail="holograms | rain | street food stall | drones | kanji signs | steam vents",
      acts=dict(solo="smoking, neon | hacking, wrist display | walking, rain", pair="deal, alley | walking, neon, together | sharing umbrella", groups="gang, street | crowd, neon"),
      zones=[
          Z("Neon alley", "cyberpunk alley | neon alley, rain | back street, holograms", "neon signs | puddles | cables", solo="leaning, neon sign | crouching, alley",
            pair="whispering, alley", groups="gang, alley"),
          Z("Night market", "cyberpunk market | street stalls, neon | noodle stand, rain", "noodle bar | umbrellas | robot vendor", solo="eating noodles | browsing stall",
            pair="noodles, together", groups="crowd, market"),
          Z("Megacity overpass", "megacity overpass | skybridge, city | highway, flying cars", "flying cars | skyscrapers | ads", solo="leaning, railing, city", pair="watching traffic",
            groups="crew, overpass"),
      ]),
    P("Space station", f="space suit | jumpsuit | officer uniform | lab coat", m="space suit | jumpsuit | officer uniform | engineer overalls",
      light="cold light | earthlight | console glow | emergency light", mood="calm serious", surf="wall:viewport|floor:metal floor|bed:sleep pod|chair:pilot seat",
      detail="earth, window | floating objects | cables | control panels | stars | zero gravity",
      acts=dict(solo="floating, zero gravity | repairing panel | looking at earth", pair="floating together | docking | eating, zero gravity", groups="crew, station | briefing"),
      zones=[
          Z("Observation", "observation deck, earth | cupola, station | window, earth", "earth | stars | sun", solo="hand on glass | photographing earth", pair="floating, window", groups="crew, window"),
          Z("Module", "station module | corridor, station | modules, cables", "handrails | lockers | cables", solo="floating, module", pair="passing tool", groups="crew, module"),
          Z("Airlock", "airlock | spacewalk, station | hatch, space", "hatch | tethers | helmet", solo="suiting up | spacewalk", pair="checking suit", groups="team, airlock"),
      ]),
    P("Android lab", f="lab coat | android bodysuit | technician uniform | hospital gown", m="lab coat | technician uniform | android bodysuit | scientist outfit",
      light="cold white light | blue light | monitor glow | sterile light", mood="calm tense", surf="table:lab table|bed:pod|wall:glass wall",
      detail="robot arms | wires | monitors | spare parts | glass pods | holographic display",
      acts=dict(solo="activating | lying on table | examining hand", pair="repairing android | first contact, hands | scanning", groups="research team"),
      zones=[
          Z("Assembly", "android assembly | robot factory | assembly line", "robot arms | parts | sparks", solo="assembly, robot arms", pair="assembling", groups="engineers"),
          Z("Pods", "stasis pods | glass pods, lab | android pods", "pods | fog | lights", solo="inside pod | waking, pod", pair="opening pod", groups="pods, row"),
          Z("Test room", "test chamber | white room | observation room", "one-way mirror | cameras | chair", solo="sitting, test chamber", pair="interview", groups="observation"),
      ]),
    P("Desert planet", f="desert robes | space suit | scavenger outfit | goggles, scarf", m="desert robes | space suit | scavenger outfit | goggles, scarf",
      light="twin suns | harsh sun | sunset, two moons | dust storm", mood="calm serious", surf="floor:sand|wall:wreckage",
      detail="crashed starship | two moons | dunes | droid | wreckage | sand storm",
      acts=dict(solo="scavenging | walking, dunes | looking at moons", pair="trekking together | repairing ship | sharing water", groups="caravan | scavengers"),
      zones=[
          Z("Wreck", "crashed ship, desert | wreckage, sand | starship wreck", "wreckage | sand | parts", solo="scavenging parts", pair="climbing wreck", groups="scavengers"),
          Z("Outpost", "desert outpost | trading post, desert | settlement, domes", "domes | speeders | traders", solo="trading", pair="bargaining", groups="market"),
          Z("Canyon", "alien canyon | red canyon, sky | canyon, rocks", "rock arches | sky | creatures", solo="speeder, canyon", pair="hiding, canyon", groups="chase, canyon"),
      ]),
    P("Mecha hangar", f="pilot suit | mechanic overalls | plugsuit | flight jacket", m="pilot suit | mechanic overalls | flight jacket | officer uniform",
      light="hangar lights | sparks | spotlight | warning lights", mood="serious tense", surf="floor:hangar floor|wall:mecha|chair:cockpit seat",
      detail="giant robot | cranes | sparks | tools | cables | warning stripes",
      acts=dict(solo="looking up, mecha | climbing ladder | repairing", pair="briefing | handing helmet | standing, mecha", groups="crew, hangar | launch"),
      zones=[
          Z("Hangar floor", "mecha hangar | hangar, giant robot | robot bay", "mecha | cranes | workers", solo="standing, mecha", pair="talking, hangar", groups="crew"),
          Z("Cockpit", "mecha cockpit | cockpit, screens | pilot seat", "screens | controls | helmet", solo="sitting, cockpit", pair="cockpit, two seats", groups="radio, crew"),
          Z("Launch bay", "launch bay | catapult, mecha | launch deck", "launch rails | lights | smoke", solo="ready, launch", pair="saluting", groups="launch crew"),
      ]),
    P("Utopian city", f="white bodysuit | flowing futuristic dress | sleek coat | minimalist outfit", m="white suit | futuristic coat | sleek outfit | minimalist outfit",
      light="bright daylight | soft white light | sunset, glass | bioluminescent", mood="calm happy", surf="floor:white floor|chair:bench|water:fountain",
      detail="gardens | monorail | white towers | drones | water features | glass domes",
      acts=dict(solo="walking, plaza | reading, tablet | riding monorail", pair="walking together | picnic, park | holding hands, plaza", groups="crowd, plaza | festival"),
      zones=[
          Z("Garden plaza", "futuristic garden | sky garden | plaza, plants", "trees | fountains | benches", solo="sitting, bench", pair="picnic", groups="crowd"),
          Z("Monorail", "monorail station | monorail, city | train, futuristic", "monorail | platform | city", solo="waiting, monorail", pair="riding together", groups="commuters"),
          Z("Sky tower", "sky tower, observation | tower top, clouds | penthouse, futuristic", "clouds | glass | city below", solo="looking at city", pair="balcony, together",
            groups="party, tower"),
      ]),
    P("Starship quarters", f="tank top, shorts | uniform, unzipped | robe | sleepwear", m="tank top | uniform, unzipped | robe | sleepwear",
      light="dim cabin light | starlight | blue light | warm lamp", mood="calm", surf="bed:bunk|wall:viewport|chair:chair|table:desk",
      detail="viewport, stars | personal items | holo photos | bunk | console | plants",
      acts=dict(solo="looking at stars | writing log | lying in bunk", pair="talking, bunk | watching stars, together | drinking, quarters", groups="cards game | crew hangout"),
      zones=[
          Z("Bunk", "starship bunk | crew quarters | sleeping quarters", "bunk | blanket | photos", solo="reading, bunk | stretching, bunk", pair="sitting, bunk, together", groups="crowded quarters"),
          Z("Viewport", "quarters, viewport | window, nebula | cabin window", "nebula | stars | reflection", solo="watching nebula", pair="cuddling, window", groups="window, crew"),
          Z("Mess hall", "mess hall | galley, starship | crew canteen", "trays | coffee | tables", solo="eating, tray", pair="eating together", groups="crew dinner"),
      ]),
    P("Alien jungle", f="explorer suit | space suit | tribal outfit | jumpsuit", m="explorer suit | space suit | tribal outfit | jumpsuit",
      light="bioluminescence | alien sunlight | purple light | mist", mood="tense calm", surf="floor:moss|water:pool",
      detail="glowing plants | alien creatures | giant flowers | vines | spores | strange sky",
      acts=dict(solo="scanning plant | walking, jungle | touching glowing plant", pair="exploring together | first contact | hiding", groups="expedition | first contact"),
      zones=[
          Z("Glowing grove", "bioluminescent forest | glowing jungle | alien forest, glow", "glow | spores | plants", solo="touching glow", pair="walking, glow", groups="expedition"),
          Z("Waterfall", "alien waterfall | purple waterfall | jungle falls", "waterfall | mist | rocks", solo="standing, waterfall", pair="swimming, waterfall", groups="camp, falls"),
          Z("Ruins", "alien ruins | ancient alien temple | ruins, glyphs", "glyphs | pillars | glow", solo="reading glyphs", pair="exploring ruins", groups="expedition, ruins"),
      ]),
    P("Retro future diner", f="retro space dress | waitress uniform, retro | jumpsuit, retro | bubble helmet", m="retro jumpsuit | ray gun, holster | bomber jacket | uniform, retro",
      light="neon | chrome reflections | warm light | starlight", mood="happy playful", surf="table:booth|chair:stool|wall:counter",
      detail="chrome | robot waiter | rocket | milkshake | jukebox | planet outside",
      acts=dict(solo="drinking milkshake | ordering, robot | sitting, booth", pair="booth, together | sharing milkshake | dancing, jukebox", groups="crowd, diner"),
      zones=[
          Z("Booth", "retro future diner | space diner booth | diner, planet view", "booth | rocket | planet", solo="eating fries | reading menu", pair="booth, across", groups="booth, crowd"),
          Z("Counter", "chrome counter | diner counter, robots | soda fountain", "robot | soda fountain | stools", solo="counter, stool", pair="counter, together", groups="counter, row"),
          Z("Landing pad", "landing pad, diner | parking, rockets | rocket lot", "rockets | neon | stars", solo="leaning, rocket", pair="rocket, together", groups="crew, rockets"),
      ]),
], "sci-fi concept art | cyberpunk, neon | anime illustration, sci-fi | retro sci-fi poster", NSFW, "cowboy shot | full body | wide shot | dutch angle", nonhuman="scifi")

theme("party", "Party", [
    P("Nightclub", f="sequin dress | crop top, mini skirt | bodycon dress | latex dress", m="open shirt, chain | black t-shirt | blazer, no shirt | leather jacket",
      light="strobe lights | laser lights | neon | dim light, haze", mood="playful happy", surf="wall:wall|table:bar|chair:booth",
      detail="dance floor | crowd | dj booth | glow sticks | cocktails | smoke machine",
      acts=dict(solo="dancing | drinking cocktail | hands up, dancing", pair="dancing together | grinding, dancing | kiss, dance floor", groups="crowd, dancing | vip"),
      zones=[
          Z("Dance floor", "nightclub, dance floor | club, crowd | rave, lights", "lasers | crowd | confetti", solo="dancing, crowd | spinning", pair="dancing close", groups="dancing, crowd"),
          Z("Bar", "nightclub bar | bar, neon | club bar, bottles", "bottles | bartender | shots", solo="ordering drink | leaning on bar", pair="shots together", groups="shots, group"),
          Z("VIP booth", "vip booth | club lounge | velvet booth", "champagne | sparklers | velvet", solo="lounging, booth", pair="booth, close", groups="vip, champagne"),
      ]),
    P("House party", f="t-shirt, jeans | party dress | crop top, shorts | sweater dress", m="t-shirt | hoodie | flannel shirt | polo shirt",
      light="party lights | dim lamps | string lights | fridge light", mood="playful happy", surf="chair:sofa|wall:wall|floor:floor|bed:bed|table:kitchen counter",
      detail="red cups | pizza boxes | music | balloons | streamers | phones",
      acts=dict(solo="drinking, red cup | dancing | taking selfie", pair="beer pong | dancing together | flirting, kitchen", groups="crowd, living room | drinking game"),
      zones=[
          Z("Living room", "house party, living room | party, couch | crowded room", "couch | speakers | crowd", solo="dancing, living room", pair="couch, together", groups="crowd"),
          Z("Kitchen", "party kitchen | kitchen, drinks | counter, party", "drinks | snacks | cups", solo="pouring drink", pair="talking, kitchen", groups="beer pong"),
          Z("Backyard", "backyard party | pool party, backyard | yard, string lights", "pool | lights | grill", solo="sitting, pool edge", pair="pool, together", groups="pool party"),
      ]),
    P("Masquerade", f="ball gown, mask | masquerade mask, dress | corset gown | feathered mask", m="tuxedo, mask | masquerade mask, suit | cape, mask | velvet suit",
      light="candlelight | chandelier | dim gold light | moonlight", mood="playful cool", surf="wall:wall|floor:ballroom floor|chair:chaise",
      detail="masks | chandeliers | champagne | velvet | candelabras | feathers",
      acts=dict(solo="holding mask | drinking champagne | looking over mask", pair="waltz, masks | whispering, masks | stolen kiss", groups="ball | masked crowd"),
      zones=[
          Z("Ballroom", "masquerade ballroom | grand ballroom, masks | ball, candles", "chandeliers | dancers | orchestra", solo="dancing", pair="waltz", groups="ball, dancers"),
          Z("Balcony", "palace balcony, night | balcony, moonlight | terrace, masquerade", "moon | stone railing | garden", solo="leaning, balcony", pair="secret meeting, balcony",
            groups="balcony, group"),
          Z("Salon", "private salon | velvet salon | parlor, masquerade", "velvet | candles | cards", solo="lounging, chaise", pair="cards, salon", groups="salon, guests"),
      ]),
    P("Beach party", f="bikini | sarong, bikini top | sundress | swimsuit", m="swim trunks | open shirt | tank top | hawaiian shirt",
      light="sunset | bonfire | tiki torches | string lights", mood="happy playful", surf="floor:sand|water:waves",
      detail="bonfire | tiki torches | coconuts | speakers | cooler | surfboards",
      acts=dict(solo="dancing, sand | drinking coconut | holding drink", pair="dancing together | splashing | piggyback, water", groups="beach party | limbo"),
      zones=[
          Z("Bonfire", "beach bonfire | bonfire, night | fire, beach", "fire | sparks | logs", solo="dancing, bonfire", pair="sitting, fire", groups="circle, bonfire"),
          Z("Bar", "beach bar | tiki bar | shack bar, beach", "cocktails | tiki | lights", solo="ordering, tiki bar", pair="cocktails, together", groups="bar, crowd"),
          Z("Surf", "shoreline, party | waves, night | beach, surf", "waves | moon | foam", solo="wading, night", pair="running, waves", groups="splash, group"),
      ]),
    P("Rooftop party", f="cocktail dress | jumpsuit | slip dress | sequin top", m="blazer | linen shirt | open shirt | suit",
      light="string lights | sunset | city lights | neon", mood="happy cool", surf="wall:railing|chair:lounge|water:pool",
      detail="skyline | cocktails | dj | fairy lights | pool | champagne",
      acts=dict(solo="dancing, rooftop | drinking cocktail | leaning, railing", pair="toasting | dancing together | kiss, skyline", groups="crowd, rooftop | toasting, group"),
      zones=[
          Z("Pool", "rooftop pool party | pool, skyline | rooftop pool", "pool | floats | lights", solo="sitting, pool edge", pair="pool, together", groups="pool party"),
          Z("Lounge", "rooftop lounge | lounge, couches | terrace lounge", "couches | candles | drinks", solo="lounging", pair="lounging together", groups="lounge, crowd"),
          Z("DJ deck", "dj booth, rooftop | rooftop dance floor | dj, skyline", "dj | speakers | lights", solo="dancing, dj", pair="dancing close", groups="crowd, dj"),
      ]),
    P("Karaoke", f="party dress | t-shirt, jeans | crop top, skirt | sweater", m="t-shirt | shirt, necktie | hoodie | suit, loose necktie",
      light="disco ball | neon | screen glow | colorful lights", mood="playful happy", surf="chair:sofa|table:table",
      detail="microphone | lyrics screen | tambourine | drinks | menu | disco ball",
      acts=dict(solo="singing, microphone | dancing, sofa | tambourine", pair="duet | dancing together | laughing, sofa", groups="singing together | cheering"),
      zones=[
          Z("Private room", "karaoke room | karaoke booth | private room, neon", "screen | sofa | drinks", solo="singing", pair="duet", groups="singing, group"),
          Z("Stage", "karaoke stage | bar, stage | open mic", "stage | spotlight | crowd", solo="singing, stage", pair="duet, stage", groups="crowd cheering"),
          Z("Hallway", "karaoke hallway | neon hallway | corridor, rooms", "doors | neon | menus", solo="leaning, hallway", pair="talking, hallway", groups="hallway, group"),
      ]),
    P("Pool party", f="bikini | one-piece swimsuit | swimsuit, sunglasses | cover-up", m="swim trunks | shirtless | tank top | open shirt",
      light="sunny day | sunset | underwater lights | night, pool lights", mood="happy playful", surf="water:pool|chair:lounger|floor:pool deck",
      detail="inflatable flamingo | splashes | water guns | cocktails | towels | sunglasses",
      acts=dict(solo="floating, inflatable | sunbathing | jumping into pool", pair="splashing | piggyback, water | floating together", groups="pool party | water fight"),
      zones=[
          Z("Pool", "pool party | backyard pool | villa pool", "floats | splashes | balls", solo="floating", pair="splashing", groups="pool, crowd"),
          Z("Loungers", "sun loungers | pool deck | cabana, pool", "loungers | towels | umbrellas", solo="applying sunscreen | reading, lounger", pair="sunbathing together", groups="loungers, group"),
          Z("Pool bar", "swim-up bar | pool bar | bar, poolside", "stools | cocktails | bartender", solo="drink, pool bar", pair="drinks, pool bar", groups="bar, pool"),
      ]),
    P("Festival", f="festival outfit | crop top, denim shorts | flower crown, dress | bikini top, skirt", m="tank top | festival outfit | open shirt | hawaiian shirt",
      light="stage lights | sunset | night, lasers | sunny day", mood="happy playful", surf="floor:grass",
      detail="main stage | crowd | flags | glitter | tents | food trucks",
      acts=dict(solo="dancing, crowd | crowd surfing | sitting, grass", pair="on shoulders | dancing together | glitter, another", groups="crowd | dancing, group"),
      zones=[
          Z("Main stage", "festival main stage | concert crowd | stage, lasers", "stage | lasers | crowd", solo="hands up", pair="on shoulders", groups="crowd"),
          Z("Campsite", "festival campsite | tents, festival | camp, night", "tents | lanterns | cooler", solo="sitting, tent", pair="camping, together", groups="camp"),
          Z("Food trucks", "festival food | food trucks, festival | food court, festival", "trucks | queues | lights", solo="eating", pair="sharing food", groups="queue"),
      ]),
    P("Wedding reception", f="wedding dress | bridesmaid dress | cocktail dress | evening gown", m="tuxedo | groom suit | suit | waistcoat",
      light="fairy lights | candlelight | golden hour | chandelier", mood="happy", surf="floor:dance floor|table:banquet table|chair:chair",
      detail="wedding cake | flowers | champagne | fairy lights | bouquet | confetti",
      acts=dict(solo="tossing bouquet | dancing | toasting", pair="first dance | cutting cake | toast, together", groups="toast | dancing, guests"),
      zones=[
          Z("Dance floor", "reception dance floor | wedding party | ballroom, wedding", "lights | band | guests", solo="twirling, dress | clapping", pair="first dance", groups="guests dancing"),
          Z("Head table", "head table, wedding | banquet, flowers | reception table", "cake | flowers | candles", solo="speech", pair="cutting cake", groups="toast"),
          Z("Garden", "wedding garden | garden, arch | outdoor reception", "arch | lanterns | flowers", solo="walking, garden", pair="kiss, arch", groups="garden, guests"),
      ]),
], "party photography, flash | anime illustration, vibrant | film photography, party | pop art", NSFW, "cowboy shot | full body | from above | dutch angle")

theme("bath", "Bath & shower", [
    P("Bathhouse", f="yukata | towel | bathrobe | swimsuit", m="yukata | towel around waist | bathrobe | swim trunks",
      light="steam, warm light | lantern light | soft light | morning light", mood="calm", surf="water:bath|floor:wooden floor|wall:tiled wall",
      detail="steam | wooden buckets | towels | stones | bamboo | water ripples",
      acts=dict(solo="relaxing, bath | washing hair | towel on head", pair="washing another's back | bathing together | relaxing, side by side", groups="bathing together | chatting, bath"),
      nsfw={"suggestive": {"pair": "washing another's back | towel slip"}, "nude": {"people": "soaping body | wet hair, steam"}},
      zones=[
          Z("Indoor bath", "public bath | sento, mural | bathhouse, tiles", "mount fuji mural | buckets | stools", solo="soaking, bath", pair="soaking together", groups="soaking, group"),
          Z("Wash area", "washing area, bathhouse | shower stools | wash station", "stools | soap | mirror", solo="washing, stool", pair="scrubbing back", groups="washing, row"),
          Z("Changing room", "changing room, bathhouse | locker room, bath | dressing room, wooden", "lockers | baskets | fans", solo="undressing, locker", pair="drying hair",
            groups="changing, group"),
      ]),
    P("Onsen", f="yukata | towel | bathrobe | kimono", m="yukata | towel | bathrobe | kimono",
      light="steam | moonlight | snow, lanterns | autumn light", mood="calm", surf="water:hot spring|floor:rocks",
      detail="steam | snow | maple leaves | rocks | sake tray | bamboo fence",
      acts=dict(solo="soaking, hot spring | drinking sake | relaxing, eyes closed", pair="soaking together | sake, together | relaxing, rocks", groups="soaking, group"),
      nsfw={"suggestive": {"people": "towel, hot spring | wet hair"}, "nude": {"people": "soaking, steam | sitting on rock, steam"}},
      zones=[
          Z("Outdoor spring", "outdoor hot spring | rotenburo, snow | onsen, mountains", "snow | steam | stones", solo="soaking, snow", pair="soaking, snow, together", groups="onsen, group"),
          Z("Private bath", "private onsen | wooden tub, onsen | private wooden bath", "wooden tub | towels | lanterns", solo="soaking, wooden tub",
            pair="private bath, together", groups="private bath, group"),
          Z("Inn veranda", "ryokan veranda | inn, yukata | ryokan room", "tatami | tea | garden", solo="sitting, veranda", pair="tea, veranda", groups="dinner, ryokan"),
      ]),
    P("Luxury bathroom", f="silk robe | towel | bathrobe | lingerie", m="robe | towel | bathrobe | boxer briefs",
      light="candlelight | soft light | morning light | city lights", mood="calm sultry", surf="water:bathtub|wall:marble wall|floor:marble floor",
      detail="rose petals | candles | champagne | marble | bubbles | gold faucet",
      acts=dict(solo="bubble bath | applying lotion | drinking champagne, bath", pair="bubble bath, together | champagne, bath | washing hair, another", groups="spa day"),
      zones=[
          Z("Bathtub", "freestanding bathtub | bathtub, window | bubble bath", "bubbles | petals | candles", solo="relaxing, bubbles", pair="bath, together", groups="spa, group"),
          Z("Rain shower", "rain shower | glass shower | walk-in shower, marble", "water droplets | steam | glass", solo="showering", pair="shower together", groups="shower, group"),
          Z("Vanity", "bathroom vanity | double sinks | vanity, mirror", "perfume | towels | mirror", solo="skincare | brushing hair", pair="mirror, together", groups="getting ready"),
      ]),
    P("Locker room shower", f="towel | sports bra | swimsuit | sportswear", m="towel | shorts | swim trunks | sportswear",
      light="fluorescent light | steam | bright light | dim light", mood="calm playful", surf="wall:tiled wall|floor:tiled floor|chair:bench",
      detail="lockers | steam | shampoo | sports bags | tiles | water",
      acts=dict(solo="showering | towel, drying | changing", pair="talking, showers | towel snap | changing, together", groups="team showers | changing, team"),
      zones=[
          Z("Showers", "communal shower | shower room | gym showers", "shower heads | steam | tiles", solo="rinsing hair | eyes closed, water", pair="showering, side by side", groups="team showers"),
          Z("Lockers", "locker room | lockers, bench | changing room", "lockers | bags | benches", solo="pulling on shirt | sitting, bench", pair="changing, together", groups="locker room"),
          Z("Sauna", "sauna | wooden sauna | steam room", "wooden benches | hot stones | steam", solo="sweating, sauna", pair="sauna, together", groups="sauna, group"),
      ]),
    P("Waterfall pool", f="swimsuit | bikini | sarong | wet dress", m="swim trunks | shirtless | shorts | wet shirt",
      light="sunbeam | mist | dappled light | golden hour", mood="calm playful", surf="water:pool|floor:rocks",
      detail="waterfall | mist | ferns | wet rocks | butterflies | rainbow",
      acts=dict(solo="standing under waterfall | swimming | sitting on rock", pair="swimming together | splashing | under waterfall, together", groups="swimming, group"),
      zones=[
          Z("Under the falls", "under waterfall | waterfall, pool | jungle waterfall", "waterfall | spray | rocks", solo="under waterfall", pair="under waterfall, together", groups="waterfall, group"),
          Z("Rock pool", "rock pool | natural pool | lagoon", "clear water | rocks | fish", solo="floating", pair="floating together", groups="lagoon, group"),
          Z("Bank", "river bank, ferns | mossy bank | stream bank", "moss | ferns | towels", solo="lying, bank", pair="lying, bank, together", groups="picnic, bank"),
      ]),
    P("Bathtub at home", f="towel | bathrobe | oversized shirt | pajamas", m="towel | bathrobe | t-shirt | pajamas",
      light="candlelight | soft light | warm light | night", mood="calm", surf="water:bathtub|floor:bath mat|wall:tiled wall",
      detail="bubbles | rubber duck | candles | book | bath bomb | wine glass",
      acts=dict(solo="reading, bath | bath bomb | relaxing, eyes closed", pair="bath together | washing hair, another | candle bath", groups="hot tub"),
      zones=[
          Z("Tub", "bathtub, bubbles | home bathtub | clawfoot tub", "bubbles | duck | bath bomb", solo="bubbles, bath", pair="bath, together", groups="crowded tub"),
          Z("Mirror", "bathroom mirror, steam | foggy mirror | mirror, bathroom", "foggy mirror | towels | toothbrushes", solo="wiping mirror", pair="mirror, together", groups="mirror, group"),
          Z("Window", "bathroom window, night | bath, window view | bath, rain window", "rain | moon | plants", solo="bath, window", pair="bath, window, together", groups="window, group"),
      ]),
    P("Hammam", f="towel | peshtemal | robe | swimsuit", m="towel | peshtemal | robe | swim trunks",
      light="steam, dome light | light beams | lamp light | soft light", mood="calm", surf="floor:marble slab|water:basin|wall:marble wall",
      detail="domed ceiling | star holes | marble | brass bowls | steam | soap foam",
      acts=dict(solo="lying on marble | pouring water | foam scrub", pair="scrubbing another | foam massage | relaxing together", groups="hammam, group"),
      zones=[
          Z("Hot room", "hammam hot room | marble slab, dome | turkish bath", "dome | light beams | steam", solo="lying, slab", pair="lying, slab, together", groups="hot room, group"),
          Z("Basins", "hammam basins | marble basins | wash room, brass", "basins | bowls | water", solo="filling bowl | splashing face", pair="pouring water, another", groups="washing, group"),
          Z("Rest room", "hammam lounge | tea room, cushions | rest area", "cushions | tea | lamps", solo="resting, cushions", pair="tea, together", groups="lounge, group"),
      ]),
    P("Pool shower", f="swimsuit | bikini | towel | swim cap", m="swim trunks | towel | swim briefs | shorts",
      light="sunny day | overcast | night lights | sunset", mood="playful", surf="water:shower|floor:pool deck|wall:wall",
      detail="outdoor shower | pool | towels | flip-flops | water drops | sunglasses",
      acts=dict(solo="rinsing off | towel, sunlight | wringing hair", pair="shower, together | towel, another | splashing", groups="showers, group"),
      zones=[
          Z("Outdoor shower", "outdoor shower | beach shower | poolside shower", "shower head | water | wood", solo="rinsing", pair="rinsing together", groups="queue, shower"),
          Z("Poolside", "poolside | pool edge | pool, tiles", "pool | tiles | towels", solo="sitting, pool edge", pair="pool edge, together", groups="poolside, group"),
          Z("Cabana", "cabana, towels | pool cabana | changing cabana", "curtains | towels | lounger", solo="changing, cabana", pair="cabana, together", groups="cabana, group"),
      ]),
    P("Spa", f="robe | towel | spa robe | face mask", m="robe | towel | spa robe | face mask",
      light="soft light | candlelight | dim light | warm light", mood="calm", surf="bed:massage table|water:jacuzzi|chair:lounger",
      detail="massage oil | candles | towels | stones | cucumber slices | orchids",
      acts=dict(solo="facial mask | massage | relaxing, robe", pair="couples massage | jacuzzi, together | face masks, together", groups="spa day, group"),
      zones=[
          Z("Massage room", "massage room | spa, massage table | treatment room", "oils | stones | candles", solo="massage, lying", pair="couples massage", groups="spa, group"),
          Z("Jacuzzi", "jacuzzi | hot tub, spa | whirlpool", "bubbles | jets | towels", solo="jacuzzi", pair="jacuzzi, together", groups="jacuzzi, group"),
          Z("Relax lounge", "spa lounge | relaxation room | lounge, loungers", "tea | loungers | plants", solo="lounging, robe", pair="lounging, together", groups="lounge, group"),
      ]),
], "photorealistic, soft light | anime illustration, steam | watercolor, bath | ukiyo-e", NSFW, "cowboy shot | upper body | full body | from side")
