from lib import P, Z, theme

NSFW = "photorealistic, detailed skin | hentai, anime coloring | painterly, erotic illustration | candid photography"

theme("street", "Street", [
    P("Night market", f="hoodie, shorts | tank top, denim skirt | oversized t-shirt | windbreaker, cap", m="hoodie, cargo pants | t-shirt, shorts | bomber jacket | linen shirt, sandals",
      light="lantern light | neon lights | string lights | steam, warm light", mood="happy playful", surf="table:plastic table|chair:plastic stool|wall:stall wall",
      detail="steam | paper lanterns | crowd | hand-written menus | smoke, grill | plastic bags",
      acts=dict(solo="eating street food | holding skewer | looking at viewer, smile", pair="sharing food | feeding another | walking, crowd", groups="walking through crowd | eating together"),
      zones=[
          Z("Food stalls", "night market, food stalls | street food stalls, steam | hawker stalls, night", "grill | skewers | noodles, bowl | dumplings | sauce bottles",
            solo="ordering food | blowing on food | chopsticks, eating", pair="pointing at menu | sharing skewers", groups="queue, food stall"),
          Z("Plastic tables", "street eatery, plastic tables | sidewalk tables, night | night market seating", "beer bottles | ice bucket | bowls | napkin box | motorbikes",
            solo="sitting on stool, eating | drinking beer | wiping mouth", pair="clinking glasses | sitting across table", groups="crowded table, laughing | cheers"),
          Z("Game stalls", "carnival games, market | game stalls, prizes | night market, games", "stuffed toys | balloons | ring toss | goldfish bags | prizes",
            solo="throwing ring | holding prize | aiming toy gun", pair="winning prize, another | cheering", groups="cheering, game stall"),
      ]),
    P("Subway", f="trench coat | blazer, pencil skirt | puffer jacket | hoodie, headphones", m="suit, briefcase | hoodie, headphones | overcoat | denim jacket",
      light="fluorescent light | train headlights | dim tunnel light | flickering lights", mood="calm melancholy", surf="chair:subway seat|wall:tiled wall|floor:platform",
      detail="tiled walls | subway map | graffiti | litter | turnstiles | ads, posters",
      acts=dict(solo="looking at phone | earphones, eyes closed | reading newspaper", pair="talking, subway | leaning on another, tired | sharing earphones", groups="commuters | crowd, rush hour"),
      zones=[
          Z("Platform", "subway platform | underground station, platform | metro platform, train arriving", "train arriving | yellow line | platform sign | wind, hair | bench",
            solo="waiting on platform | stepping back, yellow line | sitting on bench", pair="waiting together | goodbye, platform", groups="crowded platform"),
          Z("Train car", "subway car interior | train interior, seats | metro car, night", "hand straps | poles | windows, tunnel lights | sleeping passenger",
            solo="sitting, subway seat | holding strap | leaning on door", pair="sitting side by side, train | standing close, train", groups="packed train"),
          Z("Stairs", "subway stairs | station exit stairs | escalator, station", "escalator | exit sign | handrail | daylight above", solo="climbing stairs | running up stairs",
            pair="riding escalator together", groups="rushing up stairs"),
      ]),
    P("Back alley", f="leather jacket, boots | hoodie, ripped jeans | track jacket | crop top, cargo pants", m="leather jacket | hoodie | tank top, chains | track suit",
      light="single streetlight | neon sign, alley | dim light | flickering bulb", mood="tense cool", surf="wall:brick wall|floor:asphalt",
      detail="graffiti | trash bags | fire escape | puddles | steam vent | cats",
      acts=dict(solo="leaning on wall, smoking | hands in pockets | crouching", pair="whispering, alley | lighting cigarette, another | deal, alley", groups="gang, alley | huddled, alley"),
      zones=[
          Z("Graffiti wall", "alley, graffiti wall | brick alley, graffiti | street art wall", "spray cans | murals | tags | drips", solo="spray painting | looking at mural | crouching, spray can",
            pair="painting mural together | lookout", groups="crew, graffiti"),
          Z("Fire escape", "fire escape, alley | rusty fire escape | apartment fire escape", "metal stairs | laundry line | potted plants | window", solo="sitting on fire escape | climbing ladder",
            pair="talking, fire escape | sitting, stairs, together", groups="hanging out, fire escape"),
          Z("Dumpsters", "alley, dumpsters | service alley, back door | kitchen back door, alley", "dumpster | crates | back door | rats", solo="taking break, back door | smoking, crates",
            pair="argument, alley | hiding together", groups="smoke break, group"),
      ]),
    P("Shopping street", f="denim jacket, skirt | sundress | cardigan, jeans | beret, coat", m="polo shirt, chinos | denim jacket | hoodie | overcoat",
      light="sunny day | overcast | shop lights | evening light", mood="happy calm", surf="chair:bench|wall:storefront",
      detail="shop signs | shopping bags | pedestrians | bicycles | potted plants | balloons",
      acts=dict(solo="holding shopping bags | walking, sidewalk | eating ice cream", pair="window shopping | walking, arm in arm | ice cream, sharing", groups="shopping spree | walking together"),
      zones=[
          Z("Boutiques", "shopping street, boutiques | high street, shops | pedestrian street, storefronts", "mannequins | sale signs | awnings", solo="looking at window display | trying on sunglasses",
            pair="pointing at display", groups="crowd, shopping"),
          Z("Bookshop", "bookshop entrance | bookstore, outdoor shelves | used bookstore", "book carts | paperbacks | chalkboard sign", solo="browsing books | reading, sidewalk",
            pair="choosing books", groups="browsing, bookshop"),
          Z("Ice cream shop", "ice cream parlor | gelato shop | ice cream stand", "ice cream cones | menu board | sprinkles", solo="licking ice cream | ordering",
            pair="sharing ice cream | feeding ice cream", groups="ice cream, group"),
      ]),
    P("Old town", f="sundress, sandals | linen dress | blouse, skirt | striped shirt, shorts", m="linen shirt | polo shirt | t-shirt, shorts | henley",
      light="afternoon sun | golden hour | overcast | warm lamps", mood="calm happy", surf="wall:stone wall|chair:stone steps",
      detail="cobblestones | flower boxes | old shutters | laundry lines | vespa | church bell",
      acts=dict(solo="walking, cobblestone street | sitting on steps | taking photo", pair="getting lost, map | walking, hand in hand | taking selfie", groups="walking tour | sitting on steps, group"),
      zones=[
          Z("Narrow lane", "narrow cobblestone street | old town alley | medieval lane", "arch | lanterns | ivy | steps", solo="walking up steps | looking up",
            pair="walking, narrow street", groups="walking single file"),
          Z("Fountain square", "town square, fountain | piazza | plaza, fountain", "fountain | pigeons | cafe tables | church facade", solo="sitting on fountain edge | feeding pigeons",
            pair="tossing coin, fountain", groups="gathering, square"),
          Z("Bridge", "old stone bridge, river | bridge, canal | arched bridge", "river | boats | love locks | streetlamps", solo="leaning on railing, river | looking at water",
            pair="kiss, bridge | leaning on railing, together", groups="crossing bridge"),
      ]),
    P("Bus terminal", f="backpack, hoodie | travel coat | denim jacket, sneakers | sweater, scarf", m="backpack, jacket | flannel shirt | windbreaker | coat, scarf",
      light="fluorescent light | dawn light | night, bus headlights | overcast", mood="melancholy calm", surf="chair:bench|wall:wall|floor:floor",
      detail="departure board | luggage | bus | vending machine | tickets | clock",
      acts=dict(solo="waiting, luggage | checking ticket | sleeping on bench", pair="goodbye hug | sharing snacks | waiting together", groups="waiting crowd | queue"),
      zones=[
          Z("Waiting hall", "bus station waiting hall | terminal, benches | station hall, night", "benches | backpacks | coffee cups", solo="sitting, luggage | reading",
            pair="sitting on bench, together", groups="crowded waiting hall"),
          Z("Bus bay", "bus bay | buses, terminal | bus platform", "buses | exhaust | luggage hold", solo="boarding bus | loading luggage", pair="waving goodbye", groups="boarding queue"),
          Z("Ticket window", "ticket counter | station ticket window | kiosk", "ticket window | timetable | coins", solo="buying ticket | looking at timetable",
            pair="counting coins | arguing, ticket", groups="queue, ticket window"),
      ]),
    P("Skate park", f="crop top, baggy jeans | oversized hoodie, shorts | tank top, cargo pants | flannel, skirt", m="t-shirt, baggy jeans | hoodie | tank top, shorts | flannel shirt, beanie",
      light="sunny day | golden hour | floodlights, night | overcast", mood="playful happy", surf="floor:concrete|wall:ramp",
      detail="skateboards | graffiti | ramps | water bottles | speaker | knee pads",
      acts=dict(solo="holding skateboard | sitting on ramp | ollie", pair="high five | teaching skateboarding | sitting on ramp, together", groups="cheering, skateboarding | hanging out, ramp"),
      zones=[
          Z("Bowl", "skate bowl | concrete bowl, skate park | skate pool", "bowl | coping | graffiti", solo="skateboarding, bowl | dropping in", pair="watching, bowl edge", groups="session, bowl"),
          Z("Half pipe", "half pipe | skate ramp | vert ramp", "ramp | sky | flag", solo="mid-air, skateboard | grinding", pair="cheering another", groups="lined up, ramp"),
          Z("Street section", "skate park, rails | stairs, handrail | ledges, plaza", "handrail | ledges | stairs", solo="grinding rail | kickflip", pair="filming, phone",
            groups="crowd, skate park"),
      ]),
    P("Rainy crossing", f="raincoat | trench coat | umbrella, coat | hoodie", m="rain jacket | trench coat | umbrella, suit | hoodie",
      light="rain, neon | streetlights | overcast | night, reflections", mood="melancholy calm", surf="wall:wall",
      detail="rain | puddles | umbrellas | reflections | taxi | wet asphalt",
      acts=dict(solo="holding umbrella | looking up, rain | walking, rain", pair="sharing umbrella | running, rain | hug, rain", groups="umbrellas, crowd | crossing, rain"),
      zones=[
          Z("Crosswalk", "crosswalk, rain | intersection, rain | zebra crossing, night", "traffic light | headlights | crosswalk lines", solo="waiting, red light | crossing",
            pair="crossing, umbrella", groups="crowd crossing"),
          Z("Awning", "shop awning, rain | storefront, rain | doorway, rain", "awning | dripping water | shop light", solo="sheltering, awning | shaking umbrella",
            pair="sheltering together", groups="sheltering, crowd"),
          Z("Overpass", "pedestrian overpass, rain | footbridge, city | overpass, traffic", "car lights | railing | city view", solo="leaning on railing, rain | looking at traffic",
            pair="standing, overpass, umbrella", groups="crossing overpass"),
      ]),
    P("Laundromat", f="oversized t-shirt, shorts | hoodie, leggings | cardigan, slip dress | tank top, sweatpants", m="t-shirt, sweatpants | hoodie | flannel | tank top, shorts",
      light="fluorescent light | night, neon | warm light | flickering light", mood="calm melancholy", surf="chair:plastic chair|table:folding table|wall:washing machines",
      detail="washing machines | detergent | laundry basket | coin slot | vending machine | magazines",
      acts=dict(solo="waiting, laundry | reading magazine | sitting on machine", pair="folding laundry together | talking, laundromat | sharing snacks", groups="waiting, laundromat | chatting, laundromat"),
      zones=[
          Z("Machines", "laundromat, washing machines | coin laundry | laundry room", "spinning drum | bubbles | coins", solo="loading machine | watching drum", pair="sitting on machines",
            groups="crowded laundromat"),
          Z("Folding table", "laundromat, folding table | laundry, table | laundromat counter", "folded clothes | basket | hangers", solo="folding clothes | ironing",
            pair="folding sheets together", groups="folding, group"),
          Z("Window bench", "laundromat window, night | bench, laundromat | storefront window", "neon outside | rain | street view", solo="sitting by window | sleeping, bench",
            pair="sitting together, window", groups="waiting, window"),
      ]),
], "street photography, candid | film photography, grain | anime illustration, city | ink sketch, urban", NSFW, "cowboy shot | full body | wide shot | from side")

theme("nature", "Nature", [
    P("Forest", f="hiking outfit | flannel shirt, jeans | sundress, cardigan | raincoat, boots", m="hiking outfit | flannel shirt | outdoor jacket | henley, cargo pants",
      light="dappled sunlight | god rays | misty light | golden hour", mood="calm happy", surf="floor:moss|wall:tree trunk",
      detail="moss | ferns | mushrooms | birdsong | fallen leaves | sunbeams",
      acts=dict(solo="walking, forest path | touching tree | looking up, trees", pair="hiking together | resting, tree | holding hands, path", groups="hiking group | resting, log"),
      zones=[
          Z("Mossy trail", "forest trail, moss | old forest, path | woodland trail", "mossy rocks | roots | trail marker", solo="hiking, backpack | stepping over roots", pair="helping another, roots",
            groups="single file, trail"),
          Z("Giant trees", "giant trees, forest | redwood forest | ancient forest", "giant trunks | fog | ferns", solo="hugging tree | standing small, trees", pair="looking up together",
            groups="hand in hand, tree"),
          Z("Clearing", "forest clearing | glade, sunlight | woodland clearing", "wildflowers | deer, distance | stump", solo="sitting on stump | lying in grass",
            pair="picnic, clearing", groups="picnic, clearing | sitting in circle"),
      ]),
    P("Lake", f="swimsuit | sundress | windbreaker | sweater, shorts", m="swim trunks | t-shirt | windbreaker | flannel shirt",
      light="morning mist | golden hour | blue hour | midday sun", mood="calm happy", surf="floor:dock|water:lake",
      detail="still water | reflections | reeds | dragonflies | mountains | loons",
      acts=dict(solo="sitting on dock | skipping stones | looking at lake", pair="canoeing | sitting on dock, feet in water | fishing together", groups="swimming, lake | dock, group"),
      zones=[
          Z("Dock", "wooden dock, lake | lake pier | jetty, lake", "rowboat | rope | lantern", solo="sitting, feet in water | lying on dock", pair="sitting on dock, together",
            groups="jumping off dock"),
          Z("Shore", "lake shore, pebbles | lakeside, campfire | lakeshore, pines", "campfire | pebbles | pine trees", solo="collecting pebbles | sitting by fire",
            pair="campfire, blanket", groups="campfire, group"),
          Z("Canoe", "canoe, lake | lake, canoe, mist | kayak, lake", "paddles | mist | reflection", solo="paddling canoe | drifting", pair="paddling together",
            groups="canoes, group"),
      ]),
    P("Mountains", f="hiking outfit | puffer jacket | fleece, leggings | windbreaker", m="hiking outfit | puffer jacket | fleece | climbing harness",
      light="sunrise, peaks | golden hour, mountains | clouds, sun rays | snow glare", mood="calm serious", surf="floor:rocks|wall:rock face",
      detail="snowy peaks | clouds below | trekking poles | backpack | cairns | eagle",
      acts=dict(solo="standing on summit | resting, rock | looking at view", pair="summit celebration | helping hand, climb | sitting, view", groups="summit photo | hiking line"),
      zones=[
          Z("Summit", "mountain summit | peak, clouds below | summit, flag", "summit flag | wind | sea of clouds", solo="arms raised, summit | sitting, edge", pair="high five, summit",
            groups="summit, group photo"),
          Z("Alpine meadow", "alpine meadow | mountain meadow, flowers | high pasture", "wildflowers | cows | stream", solo="lying in meadow | picking flowers",
            pair="picnic, meadow", groups="resting, meadow"),
          Z("Ridge", "mountain ridge | ridgeline, wind | narrow ridge", "ridge | wind | drop", solo="walking ridge | balancing", pair="roped together",
            groups="line, ridge"),
      ]),
    P("Waterfall", f="swimsuit | sundress | hiking outfit | wet t-shirt, shorts", m="swim trunks | hiking outfit | t-shirt | shirtless, shorts",
      light="mist, rainbow | dappled light | sunbeam | overcast", mood="happy calm", surf="water:pool|floor:rocks",
      detail="mist | rainbow | wet rocks | ferns | spray | moss",
      acts=dict(solo="standing under waterfall | sitting on rock | wading", pair="splashing | swimming together | sitting, rock, together", groups="swimming, waterfall | jumping in"),
      zones=[
          Z("Plunge pool", "waterfall, plunge pool | jungle waterfall | swimming hole", "deep pool | falling water | lianas", solo="swimming, pool | floating",
            pair="swimming, waterfall", groups="swimming hole, group"),
          Z("Rock ledge", "rock ledge, waterfall | cliff, waterfall | behind waterfall", "water curtain | slippery rocks", solo="standing, ledge | jumping",
            pair="holding hands, jump", groups="cliff jumping"),
          Z("Stream", "mountain stream | creek, stones | brook, forest", "stepping stones | small fish | moss", solo="crossing stream | sitting, feet in water",
            pair="crossing, hand in hand", groups="wading, stream"),
      ]),
    P("Beach", f="bikini | sundress | swimsuit, sarong | t-shirt, shorts", m="swim trunks | shirtless | linen shirt | tank top, shorts",
      light="midday sun | sunset | golden hour | overcast", mood="happy playful", surf="floor:sand|water:sea",
      detail="waves | seashells | palm trees | seagulls | footprints | beach towel",
      acts=dict(solo="walking, shoreline | lying on towel | building sandcastle", pair="splashing | chasing, waves | sunbathing together", groups="beach volleyball | bonfire"),
      zones=[
          Z("Shore", "beach, shoreline | sandy beach, waves | tropical beach", "waves | foam | shells", solo="running, surf | wading", pair="running, waves",
            groups="splash fight"),
          Z("Dunes", "sand dunes, beach | dune grass | coastal dunes", "dune grass | fence | wind", solo="sitting, dune | walking, dunes", pair="lying in dunes",
            groups="dune walk"),
          Z("Tide pools", "tide pools, rocks | rocky beach | coral rocks", "starfish | crabs | seaweed", solo="crouching, tide pool | holding starfish",
            pair="exploring tide pools", groups="tide pool, group"),
      ]),
    P("Snowfield", f="winter coat, scarf | ski outfit | knit sweater | puffer jacket, beanie", m="winter coat | ski outfit | puffer jacket | knit sweater",
      light="snow glare | overcast | golden hour, snow | blue hour", mood="happy calm", surf="floor:snow",
      detail="snowflakes | breath vapor | pine trees, snow | footprints | sled | icicles",
      acts=dict(solo="catching snowflakes | making snow angel | walking, snow", pair="snowball fight | sledding together | holding hands, snow", groups="snowball fight | building snowman"),
      zones=[
          Z("Snowy field", "snowfield | snowy meadow | snow, open field", "snow | sled tracks | snowman", solo="lying in snow | throwing snow", pair="snow angels, together",
            groups="snowman, group"),
          Z("Pine forest", "snowy forest | pines, snow | winter forest", "snowy pines | owl | tracks", solo="walking, forest, snow | shaking branch", pair="walking together, snow",
            groups="snowshoe hike"),
          Z("Frozen lake", "frozen lake | ice, lake | frozen pond", "ice | skates | cracks", solo="ice skating | spinning, ice", pair="skating, hand in hand",
            groups="ice skating, group"),
      ]),
    P("Desert", f="desert scarf, linen | hiking outfit | flowing dress | tank top, shorts", m="desert scarf | linen shirt | hiking outfit | tank top",
      light="harsh sun | golden hour | starry night | dust haze", mood="calm serious", surf="floor:sand|wall:rock",
      detail="dunes | cactus | heat haze | sun-bleached bones | lizard | wind, sand",
      acts=dict(solo="walking, dunes | shading eyes | sitting, dune", pair="trekking together | sharing water | sitting, dune, together", groups="caravan | campfire, night"),
      zones=[
          Z("Dunes", "sand dunes | desert dunes, wind | dune sea", "ripples | footprints | wind", solo="climbing dune | sliding down dune", pair="climbing, hand in hand",
            groups="line, dunes"),
          Z("Oasis", "oasis, palm trees | desert oasis | spring, palms", "palms | water | camels", solo="drinking water | resting, palm", pair="resting together, oasis",
            groups="camp, oasis"),
          Z("Canyon", "canyon | slot canyon | red rock canyon", "red rock | light beams | sand", solo="looking up, canyon | touching rock", pair="exploring canyon",
            groups="hike, canyon"),
      ]),
    P("Flower fields", f="sundress | white dress, straw hat | floral dress | cardigan, skirt", m="linen shirt | white shirt | cardigan | t-shirt, jeans",
      light="spring sunlight | golden hour | overcast | morning light", mood="happy calm", surf="floor:grass",
      detail="bees | butterflies | petals in wind | flower crowns | blue sky | windmill",
      acts=dict(solo="holding bouquet | smelling flowers | twirling", pair="giving flowers | walking, flowers | flower crown, another", groups="picnic, flowers | running, flowers"),
      zones=[
          Z("Tulips", "tulip field | tulip rows | flower farm", "tulip rows | windmill | bicycle", solo="walking between rows | crouching, tulips", pair="cycling, tulips",
            groups="walking rows"),
          Z("Lavender", "lavender field | lavender rows, sunset | purple field", "lavender | bees | stone house", solo="touching lavender | basket, lavender", pair="walking, lavender",
            groups="harvest, lavender"),
          Z("Sunflowers", "sunflower field | sunflowers, sky | sunflower farm", "sunflowers | blue sky | bees", solo="hiding, sunflowers | holding sunflower", pair="peeking, sunflowers",
            groups="sunflower maze"),
      ]),
    P("Jungle", f="explorer outfit | tank top, cargo shorts | sarong | rain poncho", m="explorer outfit | tank top | cargo pants | rain poncho",
      light="green light, canopy | rain, jungle | sunbeam, mist | humid haze", mood="tense happy", surf="floor:jungle floor|water:river",
      detail="vines | parrots | giant leaves | humidity | orchids | monkeys",
      acts=dict(solo="machete, clearing path | looking around | swinging, vine", pair="exploring together | helping across river | map reading", groups="expedition | crossing river"),
      zones=[
          Z("Canopy", "jungle canopy | rope bridge, jungle | treetops", "rope bridge | birds | mist", solo="crossing rope bridge | looking down", pair="crossing bridge, together",
            groups="bridge crossing"),
          Z("River", "jungle river | river, boat | muddy river", "boat | crocodile, distance | reeds", solo="paddling | wading, river", pair="boat, together",
            groups="boat, group"),
          Z("Ruins", "jungle ruins | overgrown temple | stone ruins, vines", "stone carvings | roots | statues", solo="touching carving | climbing ruins", pair="discovering ruins",
            groups="exploring ruins"),
      ]),
], "landscape photography | national geographic style | watercolor, nature | studio ghibli style", NSFW, "full body | wide shot | from behind | cowboy shot")

theme("architecture", "Architecture", [
    P("Cathedral", f="long coat | dress, shawl | sweater, skirt | black dress", m="coat | suit | sweater | cassock",
      light="stained glass light | god rays | candlelight | dim light", mood="calm serious", surf="chair:pew|floor:stone floor|wall:pillar",
      detail="stained glass | candles | vaulted ceiling | incense smoke | pipe organ | stone saints",
      acts=dict(solo="looking up, ceiling | lighting candle | sitting, pew", pair="walking down aisle | whispering, pew | holding hands, light", groups="choir | tour group"),
      zones=[
          Z("Nave", "cathedral nave | gothic nave, arches | church interior, pews", "pews | arches | aisle", solo="walking, aisle | kneeling, pew", pair="standing, aisle",
            groups="congregation"),
          Z("Rose window", "rose window | stained glass, cathedral | colored light, floor", "colored light | dust | rose window", solo="standing in colored light | hand in light",
            pair="colored light, faces", groups="looking up, window"),
          Z("Bell tower", "bell tower | belfry | spiral stairs, tower", "bells | ropes | pigeons | city view", solo="climbing stairs | looking out, tower", pair="ringing bell",
            groups="climbing tower"),
      ]),
    P("Brutalist complex", f="trench coat | black turtleneck | oversized coat | minimalist dress", m="black coat | turtleneck | utility jacket | suit",
      light="overcast | harsh shadows | dusk | concrete, soft light", mood="cool melancholy", surf="wall:concrete wall|floor:concrete|chair:concrete steps",
      detail="raw concrete | geometric shadows | repeating windows | stairs | puddles | moss, concrete",
      acts=dict(solo="standing small, concrete | walking, stairs | leaning on concrete", pair="walking apart | sitting, concrete steps | silhouettes", groups="figures, concrete | line, stairs"),
      zones=[
          Z("Courtyard", "brutalist courtyard | concrete plaza | estate courtyard", "concrete planters | pool | pillars", solo="sitting, planter | walking across plaza",
            pair="meeting, plaza", groups="crowd, plaza"),
          Z("Stairwell", "concrete stairwell | spiral staircase, concrete | stairwell, light", "spiral | handrail | skylight", solo="looking down, stairwell | climbing stairs",
            pair="passing, stairs", groups="stairs, group"),
          Z("Walkway", "elevated walkway | concrete bridge, estate | skybridge", "railing | city | shadows", solo="walking, walkway | leaning, railing", pair="walking together, walkway",
            groups="walkway, crowd"),
      ]),
    P("Japanese temple", f="kimono | yukata | casual coat | haori, skirt", m="hakama | yukata | haori | casual jacket",
      light="morning light | lantern light | autumn light | soft rain", mood="calm", surf="floor:wooden veranda|wall:shoji|chair:stone steps",
      detail="stone lanterns | maple leaves | moss garden | koi pond | wind chime | torii gates",
      acts=dict(solo="praying | walking, path | sitting on veranda", pair="walking, torii | tea ceremony | feeding koi, together", groups="temple visit | festival"),
      zones=[
          Z("Torii path", "torii gates, path | red torii tunnel | shrine path", "torii | lanterns | steps", solo="walking, torii | looking back, torii", pair="walking, torii, together",
            groups="walking, torii, line"),
          Z("Zen garden", "zen garden | rock garden, raked gravel | temple garden", "raked gravel | rocks | moss", solo="sitting, veranda | meditating", pair="sitting, veranda, together",
            groups="sitting, veranda, row"),
          Z("Pagoda", "pagoda | temple, pagoda, maple | five-story pagoda", "pagoda | maple trees | bell", solo="ringing bell | looking up, pagoda", pair="praying together",
            groups="tourists, pagoda"),
      ]),
    P("Glass skyscraper", f="business suit | pencil skirt, blouse | trench coat | blazer dress", m="business suit | overcoat | turtleneck, blazer | shirt, necktie",
      light="reflections, glass | sunset, glass | blue hour | overcast", mood="cool serious", surf="wall:glass wall|chair:lobby bench|floor:marble floor",
      detail="glass facade | reflections | elevators | city view | steel beams | lobby art",
      acts=dict(solo="walking, lobby | looking at view | holding coffee, briefcase", pair="handshake | meeting, lobby | talking, elevator", groups="business meeting | commuters"),
      zones=[
          Z("Lobby", "skyscraper lobby | atrium, glass | corporate lobby", "atrium | escalators | security desk", solo="walking through lobby | waiting, elevator",
            pair="walking together, lobby | coffee, lobby", groups="crowd, lobby"),
          Z("Observation deck", "observation deck | skyscraper top, city | sky deck, glass floor", "glass floor | clouds | city", solo="standing on glass floor | looking down",
            pair="looking at city, together", groups="tourists, deck"),
          Z("Elevator", "glass elevator | elevator, city view | elevator interior", "elevator buttons | mirror | city lights", solo="leaning in elevator | looking at reflection",
            pair="standing close, elevator", groups="crowded elevator"),
      ]),
    P("Ancient ruins", f="explorer outfit | linen dress | tunic, sandals | scarf, coat", m="explorer outfit | linen shirt | tunic | field jacket",
      light="golden hour | harsh sun | sunset | dust, light beams", mood="calm serious", surf="floor:stone|wall:column|chair:stone block",
      detail="broken columns | weeds | lizard | inscriptions | crumbling stone | olive trees",
      acts=dict(solo="touching column | sitting, stone block | sketching ruins", pair="exploring together | reading inscription | taking photo, another", groups="tour group | excavation"),
      zones=[
          Z("Temple", "greek temple ruins | columns, ruins | acropolis", "columns | pediment | sky", solo="standing, columns | walking, columns", pair="walking, columns, together",
            groups="tour, columns"),
          Z("Amphitheater", "ancient amphitheater | roman theater | stone seats", "stone seats | stage | echo", solo="sitting, stone seats | standing, stage", pair="acting, stage",
            groups="audience, ruins"),
          Z("Excavation", "excavation site | dig site, ruins | archaeological dig", "brushes | grid strings | pottery shards", solo="brushing artifact | kneeling, dig",
            pair="digging together", groups="team, dig"),
      ]),
    P("Train station", f="travel coat | trench coat | sweater, skirt | backpack, jacket", m="overcoat | suit | backpack, jacket | sweater",
      light="skylight, steam | morning light | night, lamps | god rays", mood="calm melancholy", surf="chair:bench|wall:pillar|floor:platform",
      detail="steam | clock | departure board | suitcases | iron arches | pigeons",
      acts=dict(solo="waiting, suitcase | reading timetable | running, platform", pair="goodbye, platform | reunion hug | waiting together", groups="travelers | crowd, platform"),
      zones=[
          Z("Grand hall", "grand train station hall | station concourse | central station", "great clock | arches | crowd", solo="standing, clock | walking, concourse",
            pair="meeting, clock", groups="crowd, concourse"),
          Z("Platform", "train platform | steam train, platform | railway platform", "train | steam | luggage cart", solo="waiting, platform | boarding",
            pair="kiss, platform | waving goodbye", groups="boarding crowd"),
          Z("Waiting room", "station waiting room | wooden benches | vintage waiting room", "benches | fireplace | newspapers", solo="sitting, bench | sleeping, bench",
            pair="sitting, bench, together", groups="waiting room, crowd"),
      ]),
    P("Lighthouse", f="raincoat | knit sweater | wool coat | dress, cardigan", m="fisherman sweater | peacoat | raincoat | wool coat",
      light="lighthouse beam | storm light | sunset | fog", mood="calm melancholy", surf="floor:stone floor|wall:railing|chair:stool",
      detail="lighthouse lens | spiral stairs | waves | seagulls | logbook | fog horn",
      acts=dict(solo="looking out, sea | climbing stairs | writing logbook", pair="watching storm together | sharing tea | standing, wind", groups="keepers, lighthouse | gathering, storm"),
      zones=[
          Z("Lantern room", "lighthouse lantern room | lighthouse lens, glass | lamp room", "fresnel lens | beam | glass", solo="polishing lens | looking out window",
            pair="beam, faces", groups="lantern room, crowd"),
          Z("Gallery", "lighthouse gallery, railing | lighthouse balcony | lighthouse top, wind", "railing | waves below | wind", solo="leaning on railing, wind | looking out, binoculars",
            pair="hug, wind, railing", groups="gallery, group"),
          Z("Keeper cottage", "keeper cottage | lighthouse cottage, kitchen | cottage, stone", "stove | kettle | maps", solo="making tea | reading, lamp", pair="dinner, cottage",
            groups="cottage gathering"),
      ]),
    P("Modern villa", f="linen dress | white shirt, trousers | silk robe | knit dress", m="linen shirt | white t-shirt | knit polo | robe",
      light="soft daylight | sunset | pool reflections | evening lamps", mood="calm cool", surf="chair:lounge chair|water:pool|wall:glass wall|bed:daybed",
      detail="infinity pool | concrete | glass walls | olive tree | minimal furniture | ocean view",
      acts=dict(solo="lounging, pool | reading, lounge chair | walking, glass corridor", pair="drinks, pool | sitting, edge, pool | breakfast, terrace", groups="pool party | dinner, terrace"),
      zones=[
          Z("Pool", "infinity pool, villa | pool, ocean view | villa pool", "infinity edge | loungers | towels", solo="floating, pool | sitting, pool edge", pair="swimming together",
            groups="pool, group"),
          Z("Living room", "minimalist living room | open plan, glass walls | villa interior", "sofa | art | fireplace", solo="lounging, sofa | looking at view", pair="sofa, together",
            groups="party, living room"),
          Z("Terrace", "villa terrace, sunset | terrace, ocean | patio, villa", "dining table | candles | olive tree", solo="sitting, terrace | wine glass", pair="dinner, terrace",
            groups="dinner party"),
      ]),
    P("Abandoned factory", f="work jacket, cargo pants | hoodie | denim jacket | tank top, boots", m="work jacket | hoodie | denim jacket | tank top",
      light="light beams, dust | broken skylight | overcast | sunset, windows", mood="tense melancholy", surf="floor:concrete|wall:brick wall|chair:crate",
      detail="rust | broken windows | dust | graffiti | chains | weeds",
      acts=dict(solo="exploring | photographing ruins | sitting, crate", pair="exploring together | flashlight, dark | climbing, broken stairs", groups="urbex group | rave"),
      zones=[
          Z("Machine hall", "abandoned factory hall | old machinery | industrial hall", "machines | rust | light beams", solo="walking, machines | climbing machine",
            pair="exploring, hall", groups="exploring, group"),
          Z("Catwalk", "factory catwalk | metal walkway | steel stairs", "metal grating | railing | chains", solo="walking, catwalk | leaning, railing", pair="climbing together",
            groups="line, catwalk"),
          Z("Rooftop", "factory roof, broken skylight | rooftop, chimneys | industrial roof", "chimneys | sky | weeds", solo="sitting, roof edge | standing, roof, wind", pair="sitting together, roof",
            groups="rooftop, group"),
      ]),
], "architectural photography | cinematic, wide angle | ink and wash, architecture | matte painting", NSFW, "wide shot | full body | from below | from behind")
